# Language Modelling 2025–2026
## Word Embeddings - Lab Assignment
Students: Azaliia Agisheva, Hryhorii Samofatov


Neural models for word vector representations.
This notebook trains CBOW-style embeddings on English news corpora, evaluates them
qualitatively (cosine similarity, t-SNE) and quantitatively (Reuters classification).

## 0. Setup

Environment assertion, imports, reproducibility seeds, DEBUG mode, global configuration,
artifact directories, and shared I/O helpers. All project code is in this notebook.

In [1]:
import csv
import json
import os
import random
import re
import sys
import unicodedata
import warnings
from pathlib import Path


def configure_gpu_library_path() -> None:
    """WSL2 + pip TensorFlow: set LD_LIBRARY_PATH before importing tensorflow."""
    paths: list[str] = []
    wsl_cuda = Path("/usr/lib/wsl/lib")
    if wsl_cuda.is_dir():
        paths.append(str(wsl_cuda))
    site_packages = Path(sys.prefix) / "lib" / f"python{sys.version_info.major}.{sys.version_info.minor}" / "site-packages"
    nvidia_subdirs = [
        "nvidia/cudnn/lib",
        "nvidia/cublas/lib",
        "nvidia/cuda_runtime/lib",
        "nvidia/cusparse/lib",
        "nvidia/cusolver/lib",
        "nvidia/cufft/lib",
        "nvidia/nccl/lib",
        "nvidia/nvjitlink/lib",
        "nvidia/curand/lib",
        "nvidia/cuda_cupti/lib",
        "nvidia/cuda_nvrtc/lib",
    ]
    for sub in nvidia_subdirs:
        lib_dir = site_packages / sub
        if lib_dir.is_dir():
            paths.append(str(lib_dir))
    if paths:
        existing = os.environ.get("LD_LIBRARY_PATH", "")
        os.environ["LD_LIBRARY_PATH"] = ":".join(paths + ([existing] if existing else []))


configure_gpu_library_path()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from sklearn.manifold import TSNE
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import backend as K
from tensorflow.keras.layers import (
    Dense,
    Dropout,
    Embedding,
    GlobalMaxPooling1D,
    Input,
    Lambda,
    TextVectorization,
)
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import reuters
from tensorflow.keras.callbacks import (
    CSVLogger,
    EarlyStopping,
    ReduceLROnPlateau,
)
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tqdm.auto import tqdm

warnings.filterwarnings("ignore", category=UserWarning)

# --- Paths (project root = parent of this notebook) ---
PROJECT_ROOT = Path.cwd().resolve()
DATA_DIR = PROJECT_ROOT / "eng_news_2024"
CORPUS_30K = DATA_DIR / "eng_news_2024_30k_sentences.txt"
CORPUS_100K = DATA_DIR / "eng_news_2024_100K-sentences.txt"
TARGET_WORDS_PATH = PROJECT_ROOT / "target_words.txt"

ARTIFACTS = PROJECT_ROOT / "artifacts"
DIR_EMBEDDINGS = ARTIFACTS / "embeddings"
DIR_MODELS = ARTIFACTS / "models"
DIR_TOKENIZERS = ARTIFACTS / "tokenizers"
DIR_PLOTS = ARTIFACTS / "plots"
DIR_TABLES = ARTIFACTS / "tables"

for d in (DIR_EMBEDDINGS, DIR_MODELS, DIR_TOKENIZERS, DIR_PLOTS, DIR_TABLES):
    d.mkdir(parents=True, exist_ok=True)

# --- Conda environment (LM) ---
conda_env = os.environ.get("CONDA_DEFAULT_ENV", "")
if conda_env != "LM":
    print(
        f"WARNING: expected conda env 'LM', got {conda_env!r}. "
        "Activate with: conda activate LM"
    )
else:
    print(f"Conda environment: {conda_env}")

print(f"TensorFlow {tf.__version__}")
print("Devices:", tf.config.list_physical_devices())

# --- DEBUG mode (quick end-to-end smoke test) ---
DEBUG = False  # set False for full experiments

if DEBUG:
    DEBUG_N_SENTENCES = 1_000
    MAX_VOCAB_SIZE = 2_000
    WINDOW_SIZE = 2
    EMBEDDING_DIM = 32
    HIDDEN_DIM = 64
    BATCH_SIZE = 128
    EPOCHS = 1
    REUTERS_MAX_LEN = 64
    REUTERS_EPOCHS = 1
    REUTERS_EARLY_STOP_PATIENCE = 1
else:
    DEBUG_N_SENTENCES = None
    MAX_VOCAB_SIZE = 30_000
    WINDOW_SIZE = 2
    EMBEDDING_DIM = 100
    HIDDEN_DIM = 128
    BATCH_SIZE = 128
    EPOCHS = 10
    REUTERS_MAX_LEN = 256
    REUTERS_EPOCHS = 10
    REUTERS_EARLY_STOP_PATIENCE = 2

REUTERS_VOCAB_SIZE = 20_000
RANDOM_SEED = 42
VAL_FRACTION = 0.1
MIN_SENT_TOKENS = 5

CONFIG = {
    "debug": DEBUG,
    "debug_n_sentences": DEBUG_N_SENTENCES,
    "max_vocab_size": MAX_VOCAB_SIZE,
    "window_size": WINDOW_SIZE,
    "embedding_dim": EMBEDDING_DIM,
    "hidden_dim": HIDDEN_DIM,
    "batch_size": BATCH_SIZE,
    "epochs": EPOCHS,
    "reuters_max_len": REUTERS_MAX_LEN,
    "reuters_epochs": REUTERS_EPOCHS,
    "reuters_early_stop_patience": REUTERS_EARLY_STOP_PATIENCE,
    "reuters_vocab_size": REUTERS_VOCAB_SIZE,
    "random_seed": RANDOM_SEED,
    "val_fraction": VAL_FRACTION,
    "min_sent_tokens": MIN_SENT_TOKENS,
}
print("CONFIG:", json.dumps(CONFIG, indent=2))

# --- Reproducibility ---
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
tf.random.set_seed(RANDOM_SEED)

# --- Plot style ---
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)
plt.rcParams["figure.dpi"] = 100


def save_fig(name: str, close: bool = True) -> Path:
    """Save the current matplotlib figure to artifacts/plots/."""
    path = DIR_PLOTS / name
    if not name.endswith(".png"):
        path = path.with_suffix(".png")
    plt.tight_layout()
    plt.savefig(path, bbox_inches="tight")
    if close:
        plt.close()
    print(f"Saved figure: {path}")
    return path


def append_row(csv_path: Path, row: dict, fieldnames: list[str] | None = None) -> None:
    """Append one row to a CSV, creating the file and header if needed."""
    csv_path = Path(csv_path)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    write_header = not csv_path.exists() or csv_path.stat().st_size == 0
    if fieldnames is None:
        fieldnames = list(row.keys())
    with csv_path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        if write_header:
            writer.writeheader()
        writer.writerow(row)


def make_run_id(corpus: str, window: int, emb_dim: int, epochs: int, vocab: int) -> str:
    return f"cbow_{corpus}_win{window}_emb{emb_dim}_ep{epochs}_vocab{vocab}"


print("Setup complete.")

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779303422.750316  139530 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1779303422.798728  139530 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Conda environment: LM
TensorFlow 2.21.0
Devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
CONFIG: {
  "debug": false,
  "debug_n_sentences": null,
  "max_vocab_size": 30000,
  "window_size": 2,
  "embedding_dim": 100,
  "hidden_dim": 128,
  "batch_size": 128,
  "epochs": 10,
  "reuters_max_len": 256,
  "reuters_epochs": 10,
  "reuters_early_stop_patience": 2,
  "reuters_vocab_size": 20000,
  "random_seed": 42,
  "val_fraction": 0.1,
  "min_sent_tokens": 5
}
Setup complete.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779303423.645772  139530 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

## 1. Data Loading

Load the 30K and 100K English news corpora, compute summary statistics, and apply
DEBUG subsampling when training on a selected corpus.

In [ ]:
def load_corpus(path: Path | str, max_sentences: int | None = None) -> list[str]:
    """Load sentences from a corpus file (30K plain lines or 100K idx\\tsentence)."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Corpus not found: {path}")

    sentences: list[str] = []
    has_index: bool | None = None

    with path.open(encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.lstrip("\ufeff").strip()
            if not line:
                continue

            if has_index is None:
                parts = line.split("\t", 1)
                has_index = len(parts) == 2 and parts[0].strip().isdigit()

            if has_index:
                parts = line.split("\t", 1)
                text = parts[1].strip() if len(parts) > 1 else ""
            else:
                text = line

            if text:
                sentences.append(text)
            if max_sentences is not None and len(sentences) >= max_sentences:
                break

    return sentences


def subsample_corpus(
    sentences: list[str],
    debug: bool = DEBUG,
    n: int | None = DEBUG_N_SENTENCES,
) -> list[str]:
    """Return the first *n* sentences when DEBUG mode is enabled."""
    if debug and n is not None:
        return sentences[:n]
    return sentences


def compute_corpus_stats(sentences: list[str], corpus_name: str, subset: str = "full") -> dict:
    """Compute corpus statistics for reporting."""
    n = len(sentences)
    if n == 0:
        return {
            "corpus": corpus_name,
            "subset": subset,
            "n_sentences": 0,
            "avg_chars": 0.0,
            "avg_whitespace_tokens": 0.0,
            "unique_whitespace_tokens": 0,
            "debug": DEBUG,
        }

    char_lens = np.array([len(s) for s in sentences], dtype=np.float64)
    token_lens = np.array([len(s.split()) for s in sentences], dtype=np.float64)
    unique_tokens: set[str] = set()
    for s in sentences:
        unique_tokens.update(s.split())

    return {
        "corpus": corpus_name,
        "subset": subset,
        "n_sentences": n,
        "avg_chars": float(char_lens.mean()),
        "avg_whitespace_tokens": float(token_lens.mean()),
        "unique_whitespace_tokens": len(unique_tokens),
        "debug": DEBUG,
    }


def print_corpus_stats(stats: dict) -> None:
    print(
        f"[{stats['corpus']} / {stats['subset']}] "
        f"sentences={stats['n_sentences']:,} | "
        f"avg_chars={stats['avg_chars']:.1f} | "
        f"avg_tokens={stats['avg_whitespace_tokens']:.1f} | "
        f"unique_tokens={stats['unique_whitespace_tokens']:,}"
    )


# --- Load both corpora (full files) ---
sentences_30k_full = load_corpus(CORPUS_30K)
sentences_100k_full = load_corpus(CORPUS_100K)

# DEBUG subsamples (used later when training on a selected corpus)
sentences_30k = subsample_corpus(sentences_30k_full)
sentences_100k = subsample_corpus(sentences_100k_full)

# Active corpus for downstream stages (toggle here: "30k" or "100k")
ACTIVE_CORPUS = "30k"
sentences = sentences_30k if ACTIVE_CORPUS == "30k" else sentences_100k

# --- Statistics ---
corpus_stats_rows: list[dict] = []
for name, full, subsampled in [
    ("30k", sentences_30k_full, sentences_30k),
    ("100k", sentences_100k_full, sentences_100k),
]:
    for subset_label, data in [("full", full), ("active_subset", subsampled)]:
        stats = compute_corpus_stats(data, name, subset=subset_label)
        print_corpus_stats(stats)
        corpus_stats_rows.append(stats)

corpus_stats_df = pd.DataFrame(corpus_stats_rows)
corpus_stats_path = DIR_TABLES / "corpus_stats.csv"
corpus_stats_df.to_csv(corpus_stats_path, index=False)
print(f"\nSaved: {corpus_stats_path}")
display(corpus_stats_df)

# Sanity checks: format detection
assert len(sentences_30k_full) > 25_000, "30K corpus seems too small"
assert len(sentences_100k_full) > 95_000, "100K corpus seems too small"
assert "\t" not in sentences_30k_full[0] or not sentences_30k_full[0].split("\t")[0].isdigit()
first_100k = sentences_100k_full[0]
print(f"\nSample 30K: {sentences_30k_full[0][:120]}...")
print(f"Sample 100K: {first_100k[:120]}...")
print(f"Active corpus: {ACTIVE_CORPUS} ({len(sentences):,} sentences for training pipeline)")

[30k / full] sentences=30,000 | avg_chars=116.6 | avg_tokens=19.7 | unique_tokens=79,520
[30k / active_subset] sentences=30,000 | avg_chars=116.6 | avg_tokens=19.7 | unique_tokens=79,520
[100k / full] sentences=100,000 | avg_chars=117.0 | avg_tokens=19.8 | unique_tokens=172,454
[100k / active_subset] sentences=100,000 | avg_chars=117.0 | avg_tokens=19.8 | unique_tokens=172,454

Saved: /home/azaliia/projects/LM/practice/artifacts/tables/corpus_stats.csv

,corpus,subset,n_sentences,avg_chars,avg_whitespace_tokens,unique_whitespace_tokens,debug
0,30k,full,30000,116.620667,19.699567,79520,False
1,30k,active_subset,30000,116.620667,19.699567,79520,False
2,100k,full,100000,116.967910,19.753540,172454,False
3,100k,active_subset,100000,116.967910,19.753540,172454,False

Sample 30K: $10-$15 suggested donation goes to Falmouth Land Trust....
Sample 100K: "$100 upfront to process your application," one post read....
Active corpus: 30k (30,000 sentences for training pipeline)

## 2. Text Preprocessing

Normalize raw sentences (unicode, casing, numbers, URLs, punctuation) and drop
sentences shorter than `MIN_SENT_TOKENS` before tokenization.

In [3]:
# Regex patterns for normalization
_URL_RE = re.compile(r"https?://\S+|www\.\S+", re.IGNORECASE)
_EMAIL_RE = re.compile(r"\b[\w.-]+@[\w.-]+\.\w+\b")
_NUM_RE = re.compile(r"\d+(?:[.,]\d+)*")
# Keep apostrophes inside contractions (e.g. don't); strip other punctuation
_APOS_BOUNDARY_RE = re.compile(r"(?<!\w)'(?!\w)|(?<!\w)'(?=\w)|(?<=\w)'(?!\w)")
_NONWORD_PUNCT_RE = re.compile(r"[^\w\s']")
_WHITESPACE_RE = re.compile(r"\s+")


def clean_sentence(s: str) -> str:
    """Normalize a single sentence for whitespace tokenization."""
    text = unicodedata.normalize("NFKC", s)
    text = text.lower()
    text = _URL_RE.sub(" ", text)
    text = _EMAIL_RE.sub(" ", text)
    text = _NUM_RE.sub("<num>", text)
    text = _APOS_BOUNDARY_RE.sub(" ", text)
    text = _NONWORD_PUNCT_RE.sub(" ", text)
    text = _WHITESPACE_RE.sub(" ", text).strip()
    return text


def clean_corpus(
    raw_sentences: list[str],
    min_tokens: int = MIN_SENT_TOKENS,
) -> list[str]:
    """Clean all sentences and drop those with fewer than *min_tokens* tokens."""
    cleaned: list[str] = []
    dropped_short = 0
    dropped_empty = 0
    for raw in raw_sentences:
        text = clean_sentence(raw)
        if not text:
            dropped_empty += 1
            continue
        if len(text.split()) < min_tokens:
            dropped_short += 1
            continue
        cleaned.append(text)
    print(
        f"Cleaning: {len(raw_sentences):,} in → {len(cleaned):,} kept | "
        f"dropped empty={dropped_empty:,}, short (<{min_tokens} tokens)={dropped_short:,}"
    )
    return cleaned


# Clean the active corpus (in memory only)
raw_sentences = sentences
cleaned_sentences = clean_corpus(raw_sentences)

# Random before → after examples (reproducible)
rng = random.Random(RANDOM_SEED)
sample_indices = rng.sample(range(len(raw_sentences)), k=min(5, len(raw_sentences)))
print("\n--- 5 random before → after examples ---")
for idx in sample_indices:
    before = raw_sentences[idx]
    after = clean_sentence(before)
    print(f"\n[{idx}] BEFORE: {before[:200]}{'...' if len(before) > 200 else ''}")
    print(f"    AFTER:  {after[:200]}{'...' if len(after) > 200 else ''}")

print(f"\nActive corpus '{ACTIVE_CORPUS}': {len(cleaned_sentences):,} cleaned sentences ready for tokenization.")

Cleaning: 30,000 in → 29,687 kept | dropped empty=0, short (<5 tokens)=313

--- 5 random before → after examples ---

[20952] BEFORE: The American singer has finally spoken out about the attack saying that she is “completely in shock”.
    AFTER:  the american singer has finally spoken out about the attack saying that she is completely in shock

[3648] BEFORE: Brighton 3-2 Tottenham PLAYER RATINGS: Who was the 'worst player on the pitch in the first half but turned the game on its head in the second'?
    AFTER:  brighton num num tottenham player ratings who was the worst player on the pitch in the first half but turned the game on its head in the second

[819] BEFORE: Alabama clawed its way back to tie the game in the top of the sixth with a solo home run from Hodo.
    AFTER:  alabama clawed its way back to tie the game in the top of the sixth with a solo home run from hodo

[24299] BEFORE: The results and the South Tees Clean Air Quality Strategy, which aims to continue making improvements, were discussed at a meeting of Council's Executive on Wednesday.
    AFTER:  the results and the south tees clean air quality strategy which aims to continue making improvements were discussed at a meeting of council's executive on wednesday

[9012] BEFORE: He will win among older white women, and he will win among white, non-college-educated women.
    AFTER:  he will win among older white women and he will win among white non college educated women

Active corpus '30k': 29,687 cleaned sentences ready for tokenization.

## 3. Tokenization & Vocabulary

Build vocabulary with `TextVectorization`, save token mappings, and check target-word coverage.

In [4]:
# Vocabulary size depends on corpus and DEBUG mode
if DEBUG:
    VOCAB_MAX_TOKENS = MAX_VOCAB_SIZE
else:
    VOCAB_MAX_TOKENS = 50_000 if ACTIVE_CORPUS == "100k" else 30_000

print(f"Building vocabulary (max_tokens={VOCAB_MAX_TOKENS:,}) on corpus '{ACTIVE_CORPUS}'...")

vectorizer = TextVectorization(
    max_tokens=VOCAB_MAX_TOKENS,
    output_mode="int",
    standardize=None,  # already normalized in clean_sentence
    split="whitespace",
    output_sequence_length=None,
)
vectorizer.adapt(cleaned_sentences)

vocab = vectorizer.get_vocabulary()
vocab_size = len(vocab)
word_index = {word: idx for idx, word in enumerate(vocab)}
index_word = {idx: word for word, idx in word_index.items()}

print(f"Vocabulary size: {vocab_size:,}")
print(f"Reserved tokens: id 0 = {vocab[0]!r}, id 1 = {vocab[1]!r}")
assert vocab[0] == "", "Expected index 0 to be padding token ''"
assert vocab[1] in ("[UNK]", "[UNK]"), (
    f"Expected index 1 to be UNK token, got {vocab[1]!r}"
)
UNK_TOKEN = vocab[1]

# Save vocabulary for reuse
vocab_path = DIR_TOKENIZERS / f"{ACTIVE_CORPUS}_vocab.json"
vocab_payload = {
    "corpus": ACTIVE_CORPUS,
    "max_tokens": VOCAB_MAX_TOKENS,
    "vocab_size": vocab_size,
    "unk_token": UNK_TOKEN,
    "word_index": word_index,
}
with vocab_path.open("w", encoding="utf-8") as f:
    json.dump(vocab_payload, f, ensure_ascii=False)
print(f"Saved vocabulary: {vocab_path}")

# Target words OOV check
target_words = [
    line.strip()
    for line in TARGET_WORDS_PATH.read_text(encoding="utf-8").splitlines()
    if line.strip()
]
target_in_vocab = [w for w in target_words if w in word_index]
target_oov = [w for w in target_words if w not in word_index]

target_vocab_df = pd.DataFrame(
    {
        "word": target_words,
        "in_vocab": [w in word_index for w in target_words],
        "token_id": [word_index.get(w, UNK_TOKEN) for w in target_words],
    }
)
target_vocab_path = DIR_TABLES / f"target_words_{ACTIVE_CORPUS}.csv"
target_vocab_df.to_csv(target_vocab_path, index=False)

print(f"\nTarget words: {len(target_in_vocab)}/{len(target_words)} in vocabulary")
if target_oov:
    print(f"OOV ({len(target_oov)}): {', '.join(target_oov)}")
    print("(Excluded from cosine similarity / t-SNE in later stages.)")
else:
    print("All target words are in the vocabulary.")

display(target_vocab_df.head(10))

# Example tokenization
example = cleaned_sentences[0]
example_ids = vectorizer([example]).numpy()[0]
print(f"\nExample sentence: {example[:120]}...")
print(f"Token IDs (first 20): {example_ids[:20].tolist()}")
print(f"Decoded (first 20): {[index_word.get(int(i), UNK_TOKEN) for i in example_ids[:20]]}")

Building vocabulary (max_tokens=30,000) on corpus '30k'...
Vocabulary size: 30,000
Reserved tokens: id 0 = '', id 1 = '[UNK]'

I0000 00:00:1779303425.224820  139530 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9509 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9

Saved vocabulary: /home/azaliia/projects/LM/practice/artifacts/tokenizers/30k_vocab.json

Target words: 60/60 in vocabulary
All target words are in the vocabulary.

        word  in_vocab  token_id
0   everyone      True       493
1      music      True       496
2    running      True       598
3      worse      True      1959
4     friday      True       211
5  september      True       517
6    someone      True       711
7    getting      True       405
8   reported      True       415
9   expected      True       427

Example sentence: num num suggested donation goes to falmouth land trust...
Token IDs (first 20): [7, 7, 1651, 5126, 813, 3, 10509, 712, 612]
Decoded (first 20): [np.str_('num'), np.str_('num'), np.str_('suggested'), np.str_('donation'), np.str_('goes'), np.str_('to'), np.str_('falmouth'), np.str_('land'), np.str_('trust')]

## 4. Context–Target Sample Generation

Build CBOW training pairs: predict the target word from `2n` context words (`n` left + `n` right).

In [5]:
PAD_UNK_MAX_ID = 1  # skip padding (0) and UNK (1) as target; optional context filter
SKIP_HIGH_OOV_CONTEXT = True
OOV_CONTEXT_FRACTION = 0.5


def sentences_to_id_sequences(
    sentences: list[str],
    vec: TextVectorization,
) -> list[np.ndarray]:
    """Convert cleaned sentences to variable-length int32 token-id arrays."""
    id_seqs: list[np.ndarray] = []
    for s in tqdm(sentences, desc="Tokenizing sentences"):
        ids = vec([s]).numpy()[0].astype(np.int32)
        id_seqs.append(ids)
    return id_seqs


def count_cbow_samples(
    id_seqs: list[np.ndarray],
    n: int,
    skip_high_oov: bool = SKIP_HIGH_OOV_CONTEXT,
    oov_fraction: float = OOV_CONTEXT_FRACTION,
) -> int:
    """Count CBOW samples without materializing arrays."""
    total = 0
    ctx_len = 2 * n
    for ids in id_seqs:
        L = len(ids)
        if L < ctx_len + 1:
            continue
        for i in range(n, L - n):
            if ids[i] <= PAD_UNK_MAX_ID:
                continue
            ctx = np.concatenate((ids[i - n : i], ids[i + 1 : i + n + 1]))
            if skip_high_oov and np.mean(ctx <= PAD_UNK_MAX_ID) > oov_fraction:
                continue
            total += 1
    return total


def generate_samples(
    id_seqs: list[np.ndarray],
    n: int,
    skip_high_oov: bool = SKIP_HIGH_OOV_CONTEXT,
    oov_fraction: float = OOV_CONTEXT_FRACTION,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate CBOW (context, target) pairs.

    Returns
    -------
    X : (N, 2n) int32 context token ids
    y : (N,) int32 target token ids
    """
    ctx_len = 2 * n
    n_samples = count_cbow_samples(id_seqs, n, skip_high_oov, oov_fraction)
    X = np.empty((n_samples, ctx_len), dtype=np.int32)
    y = np.empty(n_samples, dtype=np.int32)

    idx = 0
    for ids in id_seqs:
        L = len(ids)
        if L < ctx_len + 1:
            continue
        for i in range(n, L - n):
            target = ids[i]
            if target <= PAD_UNK_MAX_ID:
                continue
            ctx = np.concatenate((ids[i - n : i], ids[i + 1 : i + n + 1]))
            if skip_high_oov and np.mean(ctx <= PAD_UNK_MAX_ID) > oov_fraction:
                continue
            X[idx] = ctx
            y[idx] = target
            idx += 1

    assert idx == n_samples, f"Filled {idx} samples, expected {n_samples}"
    return X, y


def decode_sample(
    context_ids: np.ndarray,
    target_id: int,
    index_word: dict[int, str],
) -> tuple[list[str], str]:
    ctx_words = [index_word.get(int(t), UNK_TOKEN) for t in context_ids]
    target_word = index_word.get(int(target_id), UNK_TOKEN)
    return ctx_words, target_word


def print_sample_examples(
    X: np.ndarray,
    y: np.ndarray,
    index_word: dict[int, str],
    n_examples: int = 3,
    seed: int = RANDOM_SEED,
) -> None:
    rng = np.random.default_rng(seed)
    indices = rng.choice(len(y), size=min(n_examples, len(y)), replace=False)
    print(f"\n--- {len(indices)} example (context → target) pairs ---")
    for k, j in enumerate(indices):
        ctx_words, target_word = decode_sample(X[j], y[j], index_word)
        ctx_str = " ".join(ctx_words)
        print(f"[{k + 1}] context: [{ctx_str}]  →  target: '{target_word}'")


# Tokenize cleaned corpus once
sentence_id_seqs = sentences_to_id_sequences(cleaned_sentences, vectorizer)

# Shape checks for n ∈ {2, 5, 8} on a small prefix (fast in DEBUG)
_shape_check_seqs = sentence_id_seqs[: min(50, len(sentence_id_seqs))]
print("Shape checks (first 50 sentences):")
for n_test in (2, 5, 8):
    X_test, y_test = generate_samples(_shape_check_seqs, n_test)
    assert X_test.shape == (len(y_test), 2 * n_test), (
        f"n={n_test}: expected X shape (_, {2 * n_test}), got {X_test.shape}"
    )
    assert y_test.ndim == 1, f"n={n_test}: y must be 1-D"
    print(f"  n={n_test}: X{X_test.shape}, y{y_test.shape} ({len(y_test):,} samples)")

# Main training window from CONFIG
n = WINDOW_SIZE
X, y = generate_samples(sentence_id_seqs, n)

mem_mb = (X.nbytes + y.nbytes) / (1024 ** 2)
print(
    f"\nGenerated {len(y):,} samples | window n={n} | context dim={2 * n} | "
    f"memory ≈ {mem_mb:.1f} MiB"
)

# Train / validation split (90% / 10%)
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=VAL_FRACTION,
    random_state=RANDOM_SEED,
    shuffle=True,
)
print(
    f"Train: {len(y_train):,} samples | Val: {len(y_val):,} samples "
    f"({VAL_FRACTION:.0%} hold-out)"
)

print_sample_examples(X_train, y_train, index_word, n_examples=3)

# Persist summary for the report
samples_summary = {
    "corpus": ACTIVE_CORPUS,
    "window_size": n,
    "n_samples": int(len(y)),
    "n_train": int(len(y_train)),
    "n_val": int(len(y_val)),
    "context_dim": 2 * n,
    "memory_mb": round(mem_mb, 2),
    "skip_high_oov_context": SKIP_HIGH_OOV_CONTEXT,
    "debug": DEBUG,
}
samples_summary_path = DIR_TABLES / f"cbow_samples_{ACTIVE_CORPUS}_win{n}.json"
with samples_summary_path.open("w", encoding="utf-8") as f:
    json.dump(samples_summary, f, indent=2)
print(f"Saved: {samples_summary_path}")

Tokenizing sentences:   0%|          | 0/29687 [00:00<?, ?it/s]

Shape checks (first 50 sentences):
  n=2: X(760, 4), y(760,) (760 samples)
  n=5: X(475, 10), y(475,) (475 samples)
  n=8: X(257, 16), y(257,) (257 samples)

Generated 478,154 samples | window n=2 | context dim=4 | memory ≈ 9.1 MiB
Train: 430,338 samples | Val: 47,816 samples (10% hold-out)

--- 3 example (context → target) pairs ---
[1] context: [prison with lengthy waitlist]  →  target: 'a'
[2] context: [region as iran aligned]  →  target: 'the'
[3] context: [independent tools libraries to]  →  target: 'and'
Saved: /home/azaliia/projects/LM/practice/artifacts/tables/cbow_samples_30k_win2.json

## 5. Model Architecture

CBOW model: embed context words → average → dense hidden → softmax over vocabulary.

In [ ]:
def build_cbow_model(
    vocab_size: int,
    embedding_dim: int,
    window_size: int,
    hidden_dim: int,
    learning_rate: float = 1e-3,
) -> Model:
    """
    Build and compile a CBOW word-prediction model (Functional API).

    Input: (batch, 2*window_size) context token ids
    Output: (batch, vocab_size) softmax over target word
    """
    context_len = 2 * window_size
    inputs = Input(shape=(context_len,), dtype="int32", name="context")
    embedded = Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        name="embeddings",
    )(inputs)
    averaged = Lambda(
        lambda x: K.mean(x, axis=1),
        name="context_mean",
    )(embedded)
    hidden = Dense(hidden_dim, activation="relu", name="hidden")(averaged)
    outputs = Dense(vocab_size, activation="softmax", name="target")(hidden)

    model = Model(inputs=inputs, outputs=outputs, name="cbow")
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss="sparse_categorical_crossentropy",
        metrics=[
            "sparse_categorical_accuracy",
            keras.metrics.SparseTopKCategoricalAccuracy(k=5, name="top5_acc"),
        ],
    )
    return model


def extract_embedding_matrix(model: Model) -> np.ndarray:
    """Return the learned embedding matrix from the 'embeddings' layer."""
    return model.get_layer("embeddings").get_weights()[0]

In [7]:
import time

EXPERIMENTS_CSV_PATH = DIR_TABLES / "experiments.csv"
EXPERIMENT_FIELDNAMES = [
    "run_id",
    "corpus",
    "n_sentences",
    "window_size",
    "embedding_dim",
    "vocab_size",
    "epochs",
    "batch_size",
    "train_loss",
    "val_loss",
    "val_top1_acc",
    "val_top5_acc",
    "train_time_s",
]

# Full experiment grid (plan §10.2). In DEBUG mode only #1 is executed.
CBOW_EXPERIMENT_GRID: list[dict] = [
    {"id": 1, "corpus": "30k", "window_size": 2, "embedding_dim": 100, "epochs": 5},
    {"id": 2, "corpus": "30k", "window_size": 5, "embedding_dim": 100, "epochs": 5},
    {"id": 3, "corpus": "30k", "window_size": 2, "embedding_dim": 300, "epochs": 5},
    {"id": 4, "corpus": "100k", "window_size": 2, "embedding_dim": 100, "epochs": 5},
    {"id": 5, "corpus": "100k", "window_size": 5, "embedding_dim": 100, "epochs": 5},
    {"id": 6, "corpus": "100k", "window_size": 2, "embedding_dim": 300, "epochs": 5},
    {"id": 7, "corpus": "100k", "window_size": 5, "embedding_dim": 100, "epochs": 10},
    {"id": 8, "corpus": "100k", "window_size": 8, "embedding_dim": 100, "epochs": 5},
]


def resolve_experiment_cfg(cfg: dict) -> dict:
    """Merge grid entry with DEBUG / full-run defaults."""
    c = dict(cfg)
    corpus = c["corpus"]
    if DEBUG:
        c["max_vocab_size"] = MAX_VOCAB_SIZE
        c["hidden_dim"] = HIDDEN_DIM
        c["batch_size"] = BATCH_SIZE
        c["embedding_dim"] = EMBEDDING_DIM
        c["epochs"] = EPOCHS
        c["debug_subsample"] = True
    else:
        c.setdefault("max_vocab_size", 50_000 if corpus == "100k" else 30_000)
        c.setdefault("hidden_dim", 128)
        c.setdefault("batch_size", 256)
        c.setdefault("debug_subsample", False)
    return c


def plot_training_history(history: keras.callbacks.History, run_id: str) -> Path:
    """Plot loss and accuracy curves; save to artifacts/plots/."""
    h = history.history
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(h["loss"], label="train")
    if "val_loss" in h:
        axes[0].plot(h["val_loss"], label="val")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].legend()

    if "sparse_categorical_accuracy" in h:
        axes[1].plot(h["sparse_categorical_accuracy"], label="train top-1")
        if "val_sparse_categorical_accuracy" in h:
            axes[1].plot(h["val_sparse_categorical_accuracy"], label="val top-1")
    if "top5_acc" in h:
        axes[1].plot(h["top5_acc"], label="train top-5", linestyle="--")
        if "val_top5_acc" in h:
            axes[1].plot(h["val_top5_acc"], label="val top-5", linestyle="--")
    axes[1].set_title("Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].legend()

    return save_fig(f"{run_id}_loss")


def run_experiment(cfg: dict) -> dict:
    """
    End-to-end CBOW experiment: load → preprocess → tokenize → samples → train → save.

    Returns a dict with experiment_row, run_id, model, embeddings, and vocab mappings.
    """
    cfg = resolve_experiment_cfg(cfg)
    corpus = cfg["corpus"]
    window_size = cfg["window_size"]
    embedding_dim = cfg["embedding_dim"]
    epochs = cfg["epochs"]
    max_vocab = cfg["max_vocab_size"]
    hidden_dim = cfg["hidden_dim"]
    batch_size = cfg["batch_size"]
    debug_subsample = cfg.get("debug_subsample", DEBUG)

    corpus_path = CORPUS_30K if corpus == "30k" else CORPUS_100K
    print(f"\n{'=' * 60}\nExperiment corpus={corpus}, n={window_size}, d={embedding_dim}, epochs={epochs}\n{'=' * 60}")

    raw = load_corpus(corpus_path)
    if debug_subsample and DEBUG_N_SENTENCES is not None:
        raw = raw[:DEBUG_N_SENTENCES]
    cleaned = clean_corpus(raw, min_tokens=MIN_SENT_TOKENS)

    vec = TextVectorization(
        max_tokens=max_vocab,
        output_mode="int",
        standardize=None,
        split="whitespace",
        output_sequence_length=None,
    )
    vec.adapt(cleaned)
    vocab = vec.get_vocabulary()
    v_size = len(vocab)
    w_index = {word: idx for idx, word in enumerate(vocab)}
    i_word = {idx: word for word, idx in w_index.items()}

    id_seqs = sentences_to_id_sequences(cleaned, vec)
    X_all, y_all = generate_samples(id_seqs, window_size)
    X_tr, X_va, y_tr, y_va = train_test_split(
        X_all,
        y_all,
        test_size=VAL_FRACTION,
        random_state=RANDOM_SEED,
        shuffle=True,
    )

    run_id = make_run_id(corpus, window_size, embedding_dim, epochs, v_size)
    keras.backend.clear_session()
    model = build_cbow_model(v_size, embedding_dim, window_size, hidden_dim)

    train_ds = (
        tf.data.Dataset.from_tensor_slices((X_tr, y_tr))
        .shuffle(len(y_tr), seed=RANDOM_SEED)
        .batch(batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )
    val_ds = (
        tf.data.Dataset.from_tensor_slices((X_va, y_va))
        .batch(batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )
    cb = [
        EarlyStopping(monitor="val_loss", patience=2, restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor="val_loss", patience=1, factor=0.5, verbose=1),
        CSVLogger(str(DIR_TABLES / f"training_log_{run_id}.csv")),
    ]

    t0 = time.perf_counter()
    history = model.fit(train_ds, validation_data=val_ds, epochs=epochs, callbacks=cb, verbose=1)
    train_time_s = time.perf_counter() - t0

    plot_training_history(history, run_id)
    E = extract_embedding_matrix(model)
    np.save(DIR_EMBEDDINGS / f"{run_id}_E.npy", E)
    with (DIR_EMBEDDINGS / f"{run_id}_word_index.json").open("w", encoding="utf-8") as f:
        json.dump(w_index, f, ensure_ascii=False)
    model.save(DIR_MODELS / f"{run_id}.keras")

    hist = history.history
    experiment_row = {
        "run_id": run_id,
        "corpus": corpus,
        "n_sentences": len(cleaned),
        "window_size": window_size,
        "embedding_dim": embedding_dim,
        "vocab_size": v_size,
        "epochs": len(hist.get("loss", [])),
        "batch_size": batch_size,
        "train_loss": float(hist["loss"][-1]),
        "val_loss": float(min(hist["val_loss"])),
        "val_top1_acc": float(max(hist["val_sparse_categorical_accuracy"])),
        "val_top5_acc": float(max(hist["val_top5_acc"])),
        "train_time_s": round(train_time_s, 2),
    }
    append_row(EXPERIMENTS_CSV_PATH, experiment_row, fieldnames=EXPERIMENT_FIELDNAMES)

    print(f"Done {run_id} in {train_time_s:.1f}s | val_loss={experiment_row['val_loss']:.4f}")
    return {
        "run_id": run_id,
        "experiment_row": experiment_row,
        "model": model,
        "embeddings": E,
        "word_index": w_index,
        "index_word": i_word,
        "vocab_size": v_size,
        "vectorizer": vec,
        "cfg": cfg,
    }

## 6. Experiment Runner

Run the CBOW experiment grid.

In [8]:
def run_experiment_grid(
    grid: list[dict] | None = None,
    *,
    debug_only_first: bool = DEBUG,
    skip_existing: bool = True,
) -> pd.DataFrame:
    """
    Run all configs in the grid and append rows to experiments.csv.

    Parameters
    ----------
    debug_only_first : if True (DEBUG), run only grid entry #1.
    skip_existing : skip runs whose run_id is already in experiments.csv.
    """
    grid = grid or CBOW_EXPERIMENT_GRID
    configs = grid[:1] if debug_only_first else grid

    def _cfg_key(c: dict) -> tuple:
        return (c["corpus"], c["window_size"], c["embedding_dim"], c["epochs"])

    existing_keys: set[tuple] = set()
    if skip_existing and EXPERIMENTS_CSV_PATH.exists():
        df_done = pd.read_csv(EXPERIMENTS_CSV_PATH)
        for _, row in df_done.iterrows():
            existing_keys.add(
                (row["corpus"], int(row["window_size"]), int(row["embedding_dim"]), int(row["epochs"]))
            )

    results: list[dict] = []
    for cfg in configs:
        cfg_resolved = resolve_experiment_cfg(cfg)
        if skip_existing and _cfg_key(cfg_resolved) in existing_keys:
            print(f"Skipping existing config: {_cfg_key(cfg_resolved)}")
            continue

        exp_id = cfg.get("id", "?")
        print(f"\n>>> Grid experiment #{exp_id}")
        out = run_experiment(cfg)
        results.append(out["experiment_row"])
        keras.backend.clear_session()

    df = pd.DataFrame(results)
    print(f"\nCompleted {len(results)} new experiment(s).")
    display(df)
    display(pd.read_csv(EXPERIMENTS_CSV_PATH))
    return df


# Run the grid (DEBUG → #1 only; full mode → all 8 configs)
grid_results_df = run_experiment_grid()

# Keep latest run artifacts in notebook globals for §7–§8
if len(grid_results_df) > 0:
    _latest_rid = grid_results_df.iloc[-1]["run_id"]
    RUN_ID = _latest_rid
    E_trained = np.load(DIR_EMBEDDINGS / f"{RUN_ID}_E.npy")
    with (DIR_EMBEDDINGS / f"{RUN_ID}_word_index.json").open(encoding="utf-8") as f:
        word_index = json.load(f)
    index_word = {idx: word for word, idx in word_index.items()}
    print(f"Latest grid run loaded: {RUN_ID}")

>>> Grid experiment #1

============================================================
Experiment corpus=30k, n=2, d=100, epochs=5
============================================================
Cleaning: 30,000 in → 29,687 kept | dropped empty=0, short (<5 tokens)=313

Tokenizing sentences:   0%|          | 0/29687 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779303538.292551  139931 service.cc:153] XLA service 0x73d2300968a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1779303538.292577  139931 service.cc:161]   StreamExecutor [0]: NVIDIA GeForce RTX 4080 Laptop GPU, Compute Capability 8.9 (Driver: 13.0.0; Runtime: 12.9.0; Toolkit: 12.5.0; DNN: 9.22.0)
I0000 00:00:1779303538.307734  139931 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1779303538.371204  139931 cuda_dnn.cc:461] Loaded cuDNN version 92200
I0000 00:00:1779303538.378009  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_2495155__.20
I0000 00:00:1779303538.390374  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779303538.988348  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779303539.722874  140404 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_10', 1420 bytes spill stores, 1420 bytes spill loads

I0000 00:00:1779303539.835007  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

  11/1682 ━━━━━━━━━━━━━━━━━━━━ 29s 18ms/step - loss: 10.3058 - sparse_categorical_accuracy: 0.0230 - top5_acc: 0.0645

I0000 00:00:1779303542.534812  139931 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

1679/1682 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7172 - sparse_categorical_accuracy: 0.0631 - top5_acc: 0.1793

I0000 00:00:1779303551.629021  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_2495155__.20

1682/1682 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7164 - sparse_categorical_accuracy: 0.0632 - top5_acc: 0.1793

I0000 00:00:1779303554.576052  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779303554.749113  140834 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_4', 12 bytes spill stores, 12 bytes spill loads

I0000 00:00:1779303554.793437  140861 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_4', 4 bytes spill stores, 4 bytes spill loads

I0000 00:00:1779303555.309230  140834 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_6', 1432 bytes spill stores, 1432 bytes spill loads

1682/1682 ━━━━━━━━━━━━━━━━━━━━ 19s 8ms/step - loss: 7.2294 - sparse_categorical_accuracy: 0.0782 - top5_acc: 0.1965 - val_loss: 6.8299 - val_sparse_categorical_accuracy: 0.1046 - val_top5_acc: 0.2249 - learning_rate: 0.0010
Epoch 2/5
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6.6073 - sparse_categorical_accuracy: 0.1147 - top5_acc: 0.2411 - val_loss: 6.6373 - val_sparse_categorical_accuracy: 0.1280 - val_top5_acc: 0.2570 - learning_rate: 0.0010
Epoch 3/5
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6.2637 - sparse_categorical_accuracy: 0.1468 - top5_acc: 0.2810 - val_loss: 6.5164 - val_sparse_categorical_accuracy: 0.1459 - val_top5_acc: 0.2823 - learning_rate: 0.0010
Epoch 4/5
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5.9608 - sparse_categorical_accuracy: 0.1711 - top5_acc: 0.3106 - val_loss: 6.4776 - val_sparse_categorical_accuracy: 0.1532 - val_top5_acc: 0.2922 - learning_rate: 0.0010
Epoch 5/5
1675/1682 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.6801 - sparse_categorical_accuracy: 0.1906 - top5_acc: 0.3334
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5.6863 - sparse_categorical_accuracy: 0.1886 - top5_acc: 0.3324 - val_loss: 6.4948 - val_sparse_categorical_accuracy: 0.1585 - val_top5_acc: 0.2978 - learning_rate: 0.0010
Restoring model weights from the end of the best epoch: 4.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_loss.png
Done cbow_30k_win2_emb100_ep5_vocab30000 in 60.5s | val_loss=6.4776

>>> Grid experiment #2

============================================================
Experiment corpus=30k, n=5, d=100, epochs=5
============================================================
Cleaning: 30,000 in → 29,687 kept | dropped empty=0, short (<5 tokens)=313

Tokenizing sentences:   0%|          | 0/29687 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779303656.193429  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_3790592__.20

1092/1093 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8851 - sparse_categorical_accuracy: 0.0568 - top5_acc: 0.1755

I0000 00:00:1779303662.891427  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_3790592__.20
I0000 00:00:1779303662.900027  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779303663.255751  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779303663.393319  141917 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_8', 12 bytes spill stores, 12 bytes spill loads

I0000 00:00:1779303664.265037  141908 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_10', 9796 bytes spill stores, 9816 bytes spill loads

I0000 00:00:1779303664.556634  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

1093/1093 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8846 - sparse_categorical_accuracy: 0.0568 - top5_acc: 0.1755

I0000 00:00:1779303667.854400  139932 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

1093/1093 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - loss: 7.4244 - sparse_categorical_accuracy: 0.0578 - top5_acc: 0.1809 - val_loss: 7.2133 - val_sparse_categorical_accuracy: 0.0601 - val_top5_acc: 0.1875 - learning_rate: 0.0010
Epoch 2/5
1093/1093 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6.9789 - sparse_categorical_accuracy: 0.0707 - top5_acc: 0.1985 - val_loss: 7.0833 - val_sparse_categorical_accuracy: 0.0795 - val_top5_acc: 0.2071 - learning_rate: 0.0010
Epoch 3/5
1093/1093 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6.7644 - sparse_categorical_accuracy: 0.0920 - top5_acc: 0.2179 - val_loss: 7.0249 - val_sparse_categorical_accuracy: 0.0922 - val_top5_acc: 0.2173 - learning_rate: 0.0010
Epoch 4/5
1093/1093 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6.5762 - sparse_categorical_accuracy: 0.1087 - top5_acc: 0.2347 - val_loss: 6.9955 - val_sparse_categorical_accuracy: 0.0991 - val_top5_acc: 0.2262 - learning_rate: 0.0010
Epoch 5/5
1093/1093 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6.3840 - sparse_categorical_accuracy: 0.1250 - top5_acc: 0.2527 - val_loss: 6.9877 - val_sparse_categorical_accuracy: 0.1059 - val_top5_acc: 0.2330 - learning_rate: 0.0010
Restoring model weights from the end of the best epoch: 5.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_loss.png
Done cbow_30k_win5_emb100_ep5_vocab30000 in 35.2s | val_loss=6.9877

>>> Grid experiment #3

============================================================
Experiment corpus=30k, n=2, d=300, epochs=5
============================================================
Cleaning: 30,000 in → 29,687 kept | dropped empty=0, short (<5 tokens)=313

Tokenizing sentences:   0%|          | 0/29687 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779303750.585332  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_5069686__.20
I0000 00:00:1779303750.746843  139928 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

1679/1682 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6519 - sparse_categorical_accuracy: 0.0663 - top5_acc: 0.1840

I0000 00:00:1779303761.781342  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_5069686__.20

1682/1682 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - loss: 7.1784 - sparse_categorical_accuracy: 0.0829 - top5_acc: 0.2024 - val_loss: 6.7883 - val_sparse_categorical_accuracy: 0.1093 - val_top5_acc: 0.2314 - learning_rate: 0.0010
Epoch 2/5
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6.5071 - sparse_categorical_accuracy: 0.1271 - top5_acc: 0.2562 - val_loss: 6.5555 - val_sparse_categorical_accuracy: 0.1392 - val_top5_acc: 0.2726 - learning_rate: 0.0010
Epoch 3/5
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6.0904 - sparse_categorical_accuracy: 0.1628 - top5_acc: 0.3015 - val_loss: 6.4566 - val_sparse_categorical_accuracy: 0.1541 - val_top5_acc: 0.2921 - learning_rate: 0.0010
Epoch 4/5
1678/1682 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.7281 - sparse_categorical_accuracy: 0.1890 - top5_acc: 0.3316
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5.7231 - sparse_categorical_accuracy: 0.1884 - top5_acc: 0.3327 - val_loss: 6.4598 - val_sparse_categorical_accuracy: 0.1590 - val_top5_acc: 0.3030 - learning_rate: 0.0010
Epoch 5/5
1675/1682 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3296 - sparse_categorical_accuracy: 0.2176 - top5_acc: 0.3628
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
1682/1682 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5.3287 - sparse_categorical_accuracy: 0.2160 - top5_acc: 0.3623 - val_loss: 6.5288 - val_sparse_categorical_accuracy: 0.1626 - val_top5_acc: 0.3040 - learning_rate: 5.0000e-04
Epoch 5: early stopping
Restoring model weights from the end of the best epoch: 3.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_loss.png
Done cbow_30k_win2_emb300_ep5_vocab30000 in 52.8s | val_loss=6.4566

>>> Grid experiment #4

============================================================
Experiment corpus=100k, n=2, d=100, epochs=5
============================================================
Cleaning: 100,000 in → 99,065 kept | dropped empty=0, short (<5 tokens)=935

Tokenizing sentences:   0%|          | 0/99065 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779303995.508614  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_9278992__.20
I0000 00:00:1779303995.984966  144768 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_10', 1404 bytes spill stores, 1404 bytes spill loads

I0000 00:00:1779303996.856174  144768 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_1_6', 64 bytes spill stores, 64 bytes spill loads

5638/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3027 - sparse_categorical_accuracy: 0.0850 - top5_acc: 0.2044

I0000 00:00:1779304042.367233  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_9278992__.20
I0000 00:00:1779304043.171402  145084 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_10', 10408 bytes spill stores, 10544 bytes spill loads

I0000 00:00:1779304043.196916  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304043.337097  145074 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_8', 12 bytes spill stores, 12 bytes spill loads

I0000 00:00:1779304043.825185  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304044.099664  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

5643/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3023 - sparse_categorical_accuracy: 0.0850 - top5_acc: 0.2044

I0000 00:00:1779304049.344551  145344 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_6', 1436 bytes spill stores, 1436 bytes spill loads

I0000 00:00:1779304049.375296  139932 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304049.519525  145336 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_4', 12 bytes spill stores, 12 bytes spill loads

5643/5643 ━━━━━━━━━━━━━━━━━━━━ 57s 9ms/step - loss: 6.8741 - sparse_categorical_accuracy: 0.1095 - top5_acc: 0.2350 - val_loss: 6.4687 - val_sparse_categorical_accuracy: 0.1452 - val_top5_acc: 0.2810 - learning_rate: 0.0010
Epoch 2/5
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 50s 9ms/step - loss: 6.1655 - sparse_categorical_accuracy: 0.1647 - top5_acc: 0.3061 - val_loss: 6.2316 - val_sparse_categorical_accuracy: 0.1670 - val_top5_acc: 0.3128 - learning_rate: 0.0010
Epoch 3/5
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 47s 8ms/step - loss: 5.7755 - sparse_categorical_accuracy: 0.1879 - top5_acc: 0.3369 - val_loss: 6.1653 - val_sparse_categorical_accuracy: 0.1763 - val_top5_acc: 0.3254 - learning_rate: 0.0010
Epoch 4/5
5639/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.4530 - sparse_categorical_accuracy: 0.2063 - top5_acc: 0.3593
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 46s 8ms/step - loss: 5.4601 - sparse_categorical_accuracy: 0.2048 - top5_acc: 0.3586 - val_loss: 6.1924 - val_sparse_categorical_accuracy: 0.1811 - val_top5_acc: 0.3327 - learning_rate: 0.0010
Epoch 5/5
5641/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.1404 - sparse_categorical_accuracy: 0.2246 - top5_acc: 0.3801
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 46s 8ms/step - loss: 5.1416 - sparse_categorical_accuracy: 0.2242 - top5_acc: 0.3805 - val_loss: 6.2614 - val_sparse_categorical_accuracy: 0.1837 - val_top5_acc: 0.3357 - learning_rate: 5.0000e-04
Epoch 5: early stopping
Restoring model weights from the end of the best epoch: 3.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb100_ep5_vocab50000_loss.png
Done cbow_100k_win2_emb100_ep5_vocab50000 in 246.5s | val_loss=6.1653

>>> Grid experiment #5

============================================================
Experiment corpus=100k, n=5, d=100, epochs=5
============================================================
Cleaning: 100,000 in → 99,065 kept | dropped empty=0, short (<5 tokens)=935

Tokenizing sentences:   0%|          | 0/99065 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779304430.847768  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_13598323__.20

3668/3672 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5568 - sparse_categorical_accuracy: 0.0612 - top5_acc: 0.1836

I0000 00:00:1779304449.779791  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_13598323__.20
I0000 00:00:1779304449.788549  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304450.120355  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304450.906837  147317 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_10', 1392 bytes spill stores, 1392 bytes spill loads

I0000 00:00:1779304451.133642  147316 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_1_6', 8 bytes spill stores, 8 bytes spill loads

I0000 00:00:1779304451.436824  147322 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_1_6', 160 bytes spill stores, 132 bytes spill loads

I0000 00:00:1779304451.477693  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

3672/3672 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5564 - sparse_categorical_accuracy: 0.0612 - top5_acc: 0.1836

I0000 00:00:1779304456.127002  147575 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_6', 1388 bytes spill stores, 1388 bytes spill loads

I0000 00:00:1779304456.157081  139932 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304456.326458  147546 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_4', 12 bytes spill stores, 12 bytes spill loads

I0000 00:00:1779304456.361219  147574 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_4', 4 bytes spill stores, 4 bytes spill loads

3672/3672 ━━━━━━━━━━━━━━━━━━━━ 28s 7ms/step - loss: 7.2132 - sparse_categorical_accuracy: 0.0717 - top5_acc: 0.1962 - val_loss: 6.9651 - val_sparse_categorical_accuracy: 0.0920 - val_top5_acc: 0.2200 - learning_rate: 0.0010
Epoch 2/5
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 6.7249 - sparse_categorical_accuracy: 0.1073 - top5_acc: 0.2364 - val_loss: 6.7411 - val_sparse_categorical_accuracy: 0.1159 - val_top5_acc: 0.2485 - learning_rate: 0.0010
Epoch 3/5
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 6.3891 - sparse_categorical_accuracy: 0.1347 - top5_acc: 0.2689 - val_loss: 6.6407 - val_sparse_categorical_accuracy: 0.1278 - val_top5_acc: 0.2621 - learning_rate: 0.0010
Epoch 4/5
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 6.1078 - sparse_categorical_accuracy: 0.1537 - top5_acc: 0.2895 - val_loss: 6.6239 - val_sparse_categorical_accuracy: 0.1338 - val_top5_acc: 0.2680 - learning_rate: 0.0010
Epoch 5/5
3667/3672 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8483 - sparse_categorical_accuracy: 0.1691 - top5_acc: 0.3066
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 30s 8ms/step - loss: 5.8542 - sparse_categorical_accuracy: 0.1676 - top5_acc: 0.3055 - val_loss: 6.6804 - val_sparse_categorical_accuracy: 0.1371 - val_top5_acc: 0.2706 - learning_rate: 0.0010
Restoring model weights from the end of the best epoch: 4.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep5_vocab50000_loss.png
Done cbow_100k_win5_emb100_ep5_vocab50000 in 150.3s | val_loss=6.6239

>>> Grid experiment #6

============================================================
Experiment corpus=100k, n=2, d=300, epochs=5
============================================================
Cleaning: 100,000 in → 99,065 kept | dropped empty=0, short (<5 tokens)=935

Tokenizing sentences:   0%|          | 0/99065 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779304774.541832  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_17862911__.20

5641/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2366 - sparse_categorical_accuracy: 0.0912 - top5_acc: 0.2124

I0000 00:00:1779304828.527547  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_17862911__.20
I0000 00:00:1779304828.536041  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304828.767894  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779304829.022675  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

5643/5643 ━━━━━━━━━━━━━━━━━━━━ 61s 10ms/step - loss: 6.7995 - sparse_categorical_accuracy: 0.1189 - top5_acc: 0.2471 - val_loss: 6.3796 - val_sparse_categorical_accuracy: 0.1551 - val_top5_acc: 0.2948 - learning_rate: 0.0010
Epoch 2/5
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 58s 10ms/step - loss: 6.0387 - sparse_categorical_accuracy: 0.1754 - top5_acc: 0.3205 - val_loss: 6.1696 - val_sparse_categorical_accuracy: 0.1752 - val_top5_acc: 0.3229 - learning_rate: 0.0010
Epoch 3/5
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 57s 10ms/step - loss: 5.5918 - sparse_categorical_accuracy: 0.2013 - top5_acc: 0.3536 - val_loss: 6.1527 - val_sparse_categorical_accuracy: 0.1824 - val_top5_acc: 0.3337 - learning_rate: 0.0010
Epoch 4/5
5640/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.1925 - sparse_categorical_accuracy: 0.2248 - top5_acc: 0.3810
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 58s 10ms/step - loss: 5.2098 - sparse_categorical_accuracy: 0.2220 - top5_acc: 0.3792 - val_loss: 6.2674 - val_sparse_categorical_accuracy: 0.1859 - val_top5_acc: 0.3378 - learning_rate: 0.0010
Epoch 5/5
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7929 - sparse_categorical_accuracy: 0.2490 - top5_acc: 0.4089
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
5643/5643 ━━━━━━━━━━━━━━━━━━━━ 62s 11ms/step - loss: 4.7958 - sparse_categorical_accuracy: 0.2483 - top5_acc: 0.4088 - val_loss: 6.4298 - val_sparse_categorical_accuracy: 0.1875 - val_top5_acc: 0.3389 - learning_rate: 5.0000e-04
Epoch 5: early stopping
Restoring model weights from the end of the best epoch: 3.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb300_ep5_vocab50000_loss.png
Done cbow_100k_win2_emb300_ep5_vocab50000 in 295.5s | val_loss=6.1527

>>> Grid experiment #7

============================================================
Experiment corpus=100k, n=5, d=100, epochs=10
============================================================
Cleaning: 100,000 in → 99,065 kept | dropped empty=0, short (<5 tokens)=935

Tokenizing sentences:   0%|          | 0/99065 [00:00<?, ?it/s]

Epoch 1/10

I0000 00:00:1779305258.986749  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_22182242__.20

3664/3672 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5565 - sparse_categorical_accuracy: 0.0607 - top5_acc: 0.1834

I0000 00:00:1779305279.111786  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_22182242__.20

3672/3672 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 7.2128 - sparse_categorical_accuracy: 0.0711 - top5_acc: 0.1956 - val_loss: 6.9724 - val_sparse_categorical_accuracy: 0.0915 - val_top5_acc: 0.2190 - learning_rate: 0.0010
Epoch 2/10
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 29s 8ms/step - loss: 6.7392 - sparse_categorical_accuracy: 0.1065 - top5_acc: 0.2351 - val_loss: 6.7552 - val_sparse_categorical_accuracy: 0.1141 - val_top5_acc: 0.2478 - learning_rate: 0.0010
Epoch 3/10
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 32s 9ms/step - loss: 6.4026 - sparse_categorical_accuracy: 0.1325 - top5_acc: 0.2669 - val_loss: 6.6466 - val_sparse_categorical_accuracy: 0.1278 - val_top5_acc: 0.2618 - learning_rate: 0.0010
Epoch 4/10
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 6.1194 - sparse_categorical_accuracy: 0.1511 - top5_acc: 0.2877 - val_loss: 6.6210 - val_sparse_categorical_accuracy: 0.1339 - val_top5_acc: 0.2683 - learning_rate: 0.0010
Epoch 5/10
3670/3672 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8598 - sparse_categorical_accuracy: 0.1671 - top5_acc: 0.3049
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 34s 9ms/step - loss: 5.8654 - sparse_categorical_accuracy: 0.1656 - top5_acc: 0.3043 - val_loss: 6.6697 - val_sparse_categorical_accuracy: 0.1367 - val_top5_acc: 0.2714 - learning_rate: 0.0010
Epoch 6/10
3669/3672 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5782 - sparse_categorical_accuracy: 0.1845 - top5_acc: 0.3238
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
3672/3672 ━━━━━━━━━━━━━━━━━━━━ 34s 9ms/step - loss: 5.5854 - sparse_categorical_accuracy: 0.1825 - top5_acc: 0.3231 - val_loss: 6.7419 - val_sparse_categorical_accuracy: 0.1383 - val_top5_acc: 0.2717 - learning_rate: 5.0000e-04
Epoch 6: early stopping
Restoring model weights from the end of the best epoch: 4.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep10_vocab50000_loss.png
Done cbow_100k_win5_emb100_ep10_vocab50000 in 185.0s | val_loss=6.6210

>>> Grid experiment #8

============================================================
Experiment corpus=100k, n=8, d=100, epochs=5
============================================================
Cleaning: 100,000 in → 99,065 kept | dropped empty=0, short (<5 tokens)=935

Tokenizing sentences:   0%|          | 0/99065 [00:00<?, ?it/s]

Epoch 1/5

I0000 00:00:1779305628.513128  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26467276__.20

2074/2079 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7464 - sparse_categorical_accuracy: 0.0578 - top5_acc: 0.1788

I0000 00:00:1779305641.692228  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26467276__.20
I0000 00:00:1779305641.700856  139932 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779305642.004749  139932 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779305642.150801  153848 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_8', 12 bytes spill stores, 12 bytes spill loads

I0000 00:00:1779305643.016201  153828 subprocess_compilation.cc:348] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_MatMul_10', 9728 bytes spill stores, 9768 bytes spill loads

I0000 00:00:1779305643.040601  139932 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

2079/2079 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - loss: 7.3633 - sparse_categorical_accuracy: 0.0599 - top5_acc: 0.1851 - val_loss: 7.1291 - val_sparse_categorical_accuracy: 0.0643 - val_top5_acc: 0.1981 - learning_rate: 0.0010
Epoch 2/5
2079/2079 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - loss: 6.9630 - sparse_categorical_accuracy: 0.0753 - top5_acc: 0.2053 - val_loss: 7.0190 - val_sparse_categorical_accuracy: 0.0858 - val_top5_acc: 0.2145 - learning_rate: 0.0010
Epoch 3/5
2079/2079 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - loss: 6.7411 - sparse_categorical_accuracy: 0.0963 - top5_acc: 0.2252 - val_loss: 6.9369 - val_sparse_categorical_accuracy: 0.0967 - val_top5_acc: 0.2270 - learning_rate: 0.0010
Epoch 4/5
2079/2079 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - loss: 6.5152 - sparse_categorical_accuracy: 0.1141 - top5_acc: 0.2432 - val_loss: 6.8901 - val_sparse_categorical_accuracy: 0.1047 - val_top5_acc: 0.2339 - learning_rate: 0.0010
Epoch 5/5
2079/2079 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - loss: 6.2953 - sparse_categorical_accuracy: 0.1293 - top5_acc: 0.2588 - val_loss: 6.8855 - val_sparse_categorical_accuracy: 0.1085 - val_top5_acc: 0.2369 - learning_rate: 0.0010
Restoring model weights from the end of the best epoch: 5.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win8_emb100_ep5_vocab50000_loss.png
Done cbow_100k_win8_emb100_ep5_vocab50000 in 98.0s | val_loss=6.8855

Completed 8 new experiment(s).

,run_id,corpus,n_sentences,window_size,embedding_dim,vocab_size,epochs,batch_size,train_loss,val_loss,val_top1_acc,val_top5_acc,train_time_s
0,cbow_30k_win2_emb100_ep5_vocab30000,30k,29687,2,100,30000,5,256,5.686319,6.477578,0.158483,0.297808,60.48
1,cbow_30k_win5_emb100_ep5_vocab30000,30k,29687,5,100,30000,5,256,6.384019,6.987684,0.105866,0.233034,35.24
2,cbow_30k_win2_emb300_ep5_vocab30000,30k,29687,2,300,30000,5,256,5.328689,6.456617,0.162623,0.303978,52.83
3,cbow_100k_win2_emb100_ep5_vocab50000,100k,99065,2,100,50000,5,256,5.141646,6.165301,0.183741,0.335743,246.45
4,cbow_100k_win5_emb100_ep5_vocab50000,100k,99065,5,100,50000,5,256,5.854170,6.623945,0.137074,0.270567,150.32
5,cbow_100k_win2_emb300_ep5_vocab50000,100k,99065,2,300,50000,5,256,4.795797,6.152708,0.187480,0.338889,295.47
6,cbow_100k_win5_emb100_ep10_vocab50000,100k,99065,5,100,50000,6,256,5.585392,6.620987,0.138319,0.271658,185.04
7,cbow_100k_win8_emb100_ep5_vocab50000,100k,99065,8,100,50000,5,256,6.295267,6.885544,0.108549,0.236890,98.03

,run_id,corpus,n_sentences,window_size,embedding_dim,vocab_size,epochs,batch_size,train_loss,val_loss,val_top1_acc,val_top5_acc,train_time_s
0,cbow_30k_win2_emb100_ep5_vocab30000,30k,29687,2,100,30000,5,256,5.686319,6.477578,0.158483,0.297808,60.48
1,cbow_30k_win5_emb100_ep5_vocab30000,30k,29687,5,100,30000,5,256,6.384019,6.987684,0.105866,0.233034,35.24
2,cbow_30k_win2_emb300_ep5_vocab30000,30k,29687,2,300,30000,5,256,5.328689,6.456617,0.162623,0.303978,52.83
3,cbow_100k_win2_emb100_ep5_vocab50000,100k,99065,2,100,50000,5,256,5.141646,6.165301,0.183741,0.335743,246.45
4,cbow_100k_win5_emb100_ep5_vocab50000,100k,99065,5,100,50000,5,256,5.854170,6.623945,0.137074,0.270567,150.32
5,cbow_100k_win2_emb300_ep5_vocab50000,100k,99065,2,300,50000,5,256,4.795797,6.152708,0.187480,0.338889,295.47
6,cbow_100k_win5_emb100_ep10_vocab50000,100k,99065,5,100,50000,6,256,5.585392,6.620987,0.138319,0.271658,185.04
7,cbow_100k_win8_emb100_ep5_vocab50000,100k,99065,8,100,50000,5,256,6.295267,6.885544,0.108549,0.236890,98.03

Latest grid run loaded: cbow_100k_win8_emb100_ep5_vocab50000

## 7. Qualitative Evaluation

Cosine similarity and t-SNE (before/after training) for each CBOW run in `experiments.csv`.

In [9]:
def load_run_artifacts(run_id: str) -> tuple[np.ndarray, dict, dict, int]:
    """Load embedding matrix and vocab mappings for a CBOW run."""
    E = np.load(DIR_EMBEDDINGS / f"{run_id}_E.npy")
    with (DIR_EMBEDDINGS / f"{run_id}_word_index.json").open(encoding="utf-8") as f:
        w_index = json.load(f)
    i_word = {idx: word for word, idx in w_index.items()}
    return E, w_index, i_word, E.shape[1]


def most_similar(
    word: str,
    embeddings: np.ndarray,
    word_index: dict,
    index_word: dict,
    k: int = 10,
) -> list[tuple[str, float]]:
    """Top-k cosine neighbors for *word* (excludes the query word)."""
    if word not in word_index:
        return []
    idx = word_index[word]
    vec = embeddings[idx : idx + 1]
    sims = cosine_similarity(vec, embeddings)[0]
    sims[idx] = -np.inf
    top_idx = np.argsort(sims)[-k:][::-1]
    return [(index_word[i], float(sims[i])) for i in top_idx if i in index_word]


def visualize_tsne_embeddings(
    words: list[str],
    embeddings: np.ndarray,
    word_index: dict,
    filename: str | Path | None = None,
    random_state: int = RANDOM_SEED,
) -> None:
    """t-SNE plot for selected words (from course materials)."""
    words = [w for w in words if w in word_index]
    if len(words) < 2:
        print(f"Need ≥2 in-vocab words for t-SNE, got {len(words)}")
        return
    indices = [word_index[w] for w in words]
    selected = embeddings[indices]
    perplexity = min(30, max(2, len(words) - 1))
    reduced = TSNE(n_components=2, perplexity=perplexity, random_state=random_state).fit_transform(
        selected
    )
    plt.figure(figsize=(10, 10))
    for i, word in enumerate(words):
        plt.scatter(reduced[i, 0], reduced[i, 1])
        plt.annotate(
            word,
            xy=(reduced[i, 0], reduced[i, 1]),
            xytext=(5, 2),
            textcoords="offset points",
            ha="right",
            va="bottom",
        )
    if filename:
        save_fig(Path(filename).stem, close=True)
    else:
        plt.show()


def visualize_all_tsne_embeddings(
    embeddings: np.ndarray,
    word_index: dict,
    words_to_plot: list[str],
    words_to_label: list[str] | None = None,
    filename: str | Path | None = None,
    random_state: int = RANDOM_SEED,
) -> None:
    """t-SNE for many words; label only *words_to_label* (from course materials)."""
    index_word = {idx: w for w, idx in word_index.items()}
    words_to_plot = [w for w in words_to_plot if w in word_index]
    if words_to_label is None:
        words_to_label = words_to_plot
    words_to_label = set(words_to_label).intersection(words_to_plot)
    if len(words_to_plot) < 2:
        print("Need ≥2 words for t-SNE")
        return
    indices = [word_index[w] for w in words_to_plot]
    selected = embeddings[indices]
    perplexity = min(30, max(2, len(words_to_plot) - 1))
    reduced = TSNE(n_components=2, perplexity=perplexity, random_state=random_state).fit_transform(
        selected
    )
    plt.figure(figsize=(12, 12))
    for i, idx in enumerate(indices):
        plt.scatter(reduced[i, 0], reduced[i, 1], alpha=0.5)
        if index_word[idx] in words_to_label:
            plt.annotate(
                index_word[idx],
                xy=(reduced[i, 0], reduced[i, 1]),
                xytext=(5, 2),
                textcoords="offset points",
                ha="right",
                va="bottom",
            )
    if filename:
        save_fig(Path(filename).stem, close=True)
    else:
        plt.show()


def top_frequent_words(word_index: dict, n: int = 500) -> list[str]:
    """Keras vocab: lower indices ≈ higher frequency (skip pad/UNK at 0,1)."""
    pairs = [(idx, w) for w, idx in word_index.items() if idx > 1 and w]
    pairs.sort(key=lambda x: x[0])
    return [w for _, w in pairs[:n]]


def run_qualitative_evaluation(
    run_id: str,
    exp_row: pd.Series | None = None,
    hidden_dim: int = HIDDEN_DIM,
) -> None:
    """Cosine tables + t-SNE before/after + top-500 plot for one CBOW run."""
    E_after, w_index, i_word, emb_dim = load_run_artifacts(run_id)
    if exp_row is None:
        exp_row = experiments_unique.loc[experiments_unique["run_id"] == run_id].iloc[0]
    window_size = int(exp_row["window_size"])
    vocab_size_run = int(exp_row["vocab_size"])

    target_words_list = [
        line.strip()
        for line in TARGET_WORDS_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    in_vocab_targets = [w for w in target_words_list if w in w_index]

    # --- Cosine similarity ---
    cosine_rows: list[dict] = []
    print(f"\n=== Cosine similarity ({run_id}) ===")
    for tw in target_words_list:
        if tw not in w_index:
            print(f"  {tw}: OOV (skipped)")
            continue
        neighbors = most_similar(tw, E_after, w_index, i_word, k=10)
        print(f"  {tw}: {', '.join(f'{w}({s:.3f})' for w, s in neighbors[:5])} ...")
        for rank, (nw, score) in enumerate(neighbors, start=1):
            cosine_rows.append(
                {"run_id": run_id, "target_word": tw, "rank": rank, "neighbor": nw, "cosine": score}
            )
    cosine_path = DIR_TABLES / f"cosine_{run_id}.csv"
    pd.DataFrame(cosine_rows).to_csv(cosine_path, index=False)
    print(f"Saved {cosine_path}")

    # --- t-SNE before (random init) ---
    keras.backend.clear_session()
    m_before = build_cbow_model(vocab_size_run, emb_dim, window_size, hidden_dim)
    E_before = extract_embedding_matrix(m_before)
    del m_before
    keras.backend.clear_session()

    tsne_targets = in_vocab_targets if len(in_vocab_targets) >= 2 else in_vocab_targets + ["the", "and"]
    visualize_tsne_embeddings(
        tsne_targets,
        E_before,
        w_index,
        filename=DIR_PLOTS / f"{run_id}_tsne_before",
        random_state=RANDOM_SEED,
    )
    visualize_tsne_embeddings(
        tsne_targets,
        E_after,
        w_index,
        filename=DIR_PLOTS / f"{run_id}_tsne_after",
        random_state=RANDOM_SEED,
    )

    top500 = top_frequent_words(w_index, n=500)
    visualize_all_tsne_embeddings(
        E_after,
        w_index,
        top500,
        words_to_label=in_vocab_targets,
        filename=DIR_PLOTS / f"{run_id}_tsne_top500",
        random_state=RANDOM_SEED,
    )


experiments_df = pd.read_csv(EXPERIMENTS_CSV_PATH)
experiments_unique = experiments_df.drop_duplicates(subset=["run_id"], keep="last")
print(f"Qualitative evaluation for {len(experiments_unique)} CBOW run(s)")

for _, exp_row in experiments_unique.iterrows():
    run_qualitative_evaluation(exp_row["run_id"], exp_row)

# Best run by validation top-1 accuracy (for report discussion)
best_row = experiments_unique.loc[experiments_unique["val_top1_acc"].idxmax()]
print(
    f"\nBest CBOW run (val top-1): {best_row['run_id']} "
    f"(acc={best_row['val_top1_acc']:.4f}, corpus={best_row['corpus']})"
)

Qualitative evaluation for 8 CBOW run(s)

=== Cosine similarity (cbow_30k_win2_emb100_ep5_vocab30000) ===
  everyone: anyone(0.834), recreational(0.792), tinder(0.784), larcombe(0.779), anybody(0.776) ...
  music: items(0.694), warnings(0.659), guidance(0.657), services(0.652), courses(0.646) ...
  running: happening(0.633), question(0.622), step(0.617), answer(0.614), power(0.605) ...
  worse: squeezed(0.813), happy(0.800), cool(0.790), pleased(0.785), doubled(0.766) ...
  friday: thursday(0.937), monday(0.926), wednesday(0.922), tuesday(0.916), saturday(0.839) ...
  september: february(0.927), january(0.910), december(0.908), june(0.906), october(0.904) ...
  someone: taxing(0.804), telesco(0.801), destined(0.784), gil(0.782), beijing(0.780) ...
  getting: hard(0.814), better(0.786), likely(0.772), very(0.764), difficult(0.763) ...
  reported: till(0.734), announced(0.703), revealed(0.702), denied(0.696), insisting(0.679) ...
  expected: scheduled(0.871), supposed(0.857), going(0.835), trying(0.827), unable(0.826) ...
  water: rural(0.738), pharmacy(0.671), blows(0.670), south(0.666), connectivity(0.663) ...
  summer: days(0.819), early(0.810), weeks(0.800), season(0.796), century(0.792) ...
  monday: friday(0.926), thursday(0.921), wednesday(0.890), tuesday(0.883), saturday(0.808) ...
  million: percent(0.896), billion(0.880), nearly(0.804), seconds(0.791), trillion(0.772) ...
  director: researcher(0.786), township(0.777), secretary(0.769), dte(0.769), demonization(0.749) ...
  staff: scams(0.734), others(0.729), sorts(0.720), spells(0.706), lykins(0.704) ...
  month: minute(0.890), week(0.854), century(0.830), year(0.806), billion(0.801) ...
  price: ratio(0.738), lowered(0.698), target(0.692), objective(0.683), estimates(0.678) ...
  person: guarantee(0.780), solution(0.755), present(0.727), decade(0.713), question(0.706) ...
  using: kurtz(0.761), spicing(0.750), gane(0.737), deafening(0.711), rubezic(0.708) ...
  never: else(0.764), ever(0.753), once(0.751), letang(0.736), actually(0.735) ...
  chief: executive(0.841), deputy(0.815), bola(0.794), prime(0.782), vice(0.778) ...
  police: dup(0.620), midlands(0.600), council(0.591), officers(0.588), hughes(0.584) ...
  billion: million(0.880), percent(0.878), month(0.801), minute(0.800), metres(0.794) ...
  great: huge(0.814), good(0.797), better(0.786), reasonable(0.780), lot(0.749) ...
  wanted: decided(0.880), joked(0.836), studied(0.816), want(0.816), confessed(0.802) ...
  human: landscaping(0.727), physical(0.710), stats(0.707), krista(0.704), exhaustion(0.701) ...
  community: kentucky(0.697), brunt(0.661), gallery(0.659), parmar(0.656), invaded(0.646) ...
  year: week(0.890), month(0.806), season(0.805), time(0.752), days(0.742) ...
  place: legislation(0.775), step(0.766), delay(0.763), coming(0.740), move(0.735) ...
  man: woman(0.812), journalist(0.695), commissioned(0.667), offence(0.666), kid(0.656) ...
  worked: appeared(0.825), sought(0.788), wardrobe(0.762), stayed(0.760), impressed(0.754) ...
  already: changed(0.739), predicted(0.734), suspensions(0.732), done(0.730), lost(0.728) ...
  recently: busted(0.707), donegal(0.700), rodrigues(0.697), publicly(0.696), you've(0.689) ...
  woman: man(0.812), shot(0.755), injured(0.688), collision(0.686), kid(0.683) ...
  looking: hungry(0.818), easier(0.783), primed(0.780), available(0.777), keen(0.776) ...
  saturday: sunday(0.861), thursday(0.857), friday(0.839), wednesday(0.836), tuesday(0.831) ...
  company: business(0.779), firm(0.743), retailer(0.724), world(0.702), alarm(0.689) ...
  season: week(0.837), days(0.823), year(0.805), summer(0.796), age(0.781) ...
  january: march(0.937), november(0.935), february(0.932), december(0.924), october(0.917) ...
  research: resulted(0.678), significant(0.652), new(0.645), report(0.642), surge(0.619) ...
  women: taiwan(0.727), children(0.678), men(0.663), sport(0.662), us(0.653) ...
  child: job(0.812), life(0.761), relationship(0.753), hat(0.751), role(0.730) ...
  israel: commuters(0.719), squaring(0.715), reform(0.708), boards(0.707), aurora(0.701) ...
  family: wife(0.635), daughter(0.610), son(0.554), crew(0.552), mother(0.551) ...
  death: critique(0.748), existence(0.740), prins(0.739), reruns(0.719), disposal(0.703) ...
  children: kids(0.763), patients(0.734), players(0.710), boys(0.698), men(0.692) ...
  march: january(0.937), november(0.923), february(0.915), april(0.912), october(0.905) ...
  earlier: ago(0.816), turbulent(0.751), lasted(0.744), last(0.742), nine(0.735) ...
  october: april(0.929), december(0.924), february(0.921), june(0.917), january(0.917) ...
  president: minister(0.698), christie(0.661), ahmed(0.646), chancellor(0.629), pie(0.623) ...
  better: cool(0.793), great(0.786), getting(0.786), wonderful(0.769), little(0.766) ...
  people: things(0.747), viewers(0.720), players(0.712), voters(0.703), residents(0.700) ...
  tuesday: friday(0.916), wednesday(0.915), thursday(0.904), monday(0.883), crematorium(0.843) ...
  today: pm(0.696), valued(0.691), laughed(0.678), cbs(0.677), tarleton(0.674) ...
  men: children(0.692), world(0.671), women(0.663), ranking(0.652), donations(0.636) ...
  school: park(0.667), university(0.657), college(0.652), ntpc(0.638), iowa(0.634) ...
  weeks: months(0.925), years(0.913), hours(0.874), days(0.873), decades(0.873) ...
  military: defense(0.758), yaw(0.727), commission(0.697), intelligence(0.682), peruvian(0.681) ...
  always: quite(0.878), really(0.863), actually(0.811), absolutely(0.807), definitely(0.806) ...
Saved /home/azaliia/projects/LM/practice/artifacts/tables/cosine_cbow_30k_win2_emb100_ep5_vocab30000.csv
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_tsne_before.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_tsne_after.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_tsne_top500.png

=== Cosine similarity (cbow_30k_win5_emb100_ep5_vocab30000) ===
  everyone: matters(0.787), anger(0.783), bulky(0.772), somebody(0.766), guidelines(0.766) ...
  music: families(0.718), clean(0.712), friends(0.689), rightly(0.682), elizabeth(0.678) ...
  running: previously(0.784), playing(0.751), marohn(0.748), consistently(0.742), football(0.733) ...
  worse: bed(0.876), serendipitous(0.871), tough(0.847), pregnant(0.845), sounding(0.840) ...
  friday: tuesday(0.930), thursday(0.914), monday(0.913), wednesday(0.846), rescued(0.840) ...
  september: february(0.933), march(0.898), april(0.897), june(0.874), july(0.873) ...
  someone: wouldn(0.875), myself(0.859), confidence(0.849), bokeh(0.848), stripped(0.843) ...
  getting: going(0.828), boys(0.797), hearts(0.791), walk(0.783), difficult(0.783) ...
  reported: fps(0.717), moving(0.669), mile(0.661), buffalo(0.658), meal(0.654) ...
  expected: supposed(0.800), eligible(0.776), able(0.766), study(0.761), filmmakers(0.754) ...
  water: groups(0.668), food(0.619), dismantling(0.616), genomic(0.616), processes(0.600) ...
  summer: plate(0.808), vote(0.794), parties(0.786), wrap(0.776), kings(0.773) ...
  monday: tuesday(0.915), friday(0.913), thursday(0.880), wednesday(0.869), altria(0.844) ...
  million: n(0.868), billion(0.854), cent(0.846), december(0.833), total(0.824) ...
  director: executive(0.825), judicial(0.788), rains(0.786), reserve's(0.779), insider(0.775) ...
  staff: china(0.813), players(0.810), ready(0.799), organizations(0.795), prospects(0.793) ...
  month: low(0.857), week(0.830), year(0.817), finish(0.815), opened(0.789) ...
  price: salesforce(0.771), increased(0.768), target(0.766), billion(0.761), estimates(0.748) ...
  person: truth(0.847), name(0.834), moment(0.827), persuaded(0.815), lifetime(0.814) ...
  using: currency(0.676), whilst(0.670), nigeri(0.670), panels(0.661), weightlifting(0.655) ...
  never: really(0.869), too(0.858), quite(0.837), always(0.818), thinking(0.808) ...
  chief: barack(0.797), nandre(0.793), european(0.789), arnold(0.783), executive(0.781) ...
  police: harris(0.699), presidential(0.686), scottish(0.685), reserve(0.682), arabia(0.667) ...
  billion: million(0.854), ratio(0.850), cap(0.848), n(0.844), earnings(0.843) ...
  great: hard(0.803), enjoyable(0.793), good(0.788), big(0.768), safe(0.724) ...
  wanted: tried(0.850), stoppers(0.794), straits(0.786), write(0.785), sexuality(0.777) ...
  human: strategy(0.812), benefits(0.768), tended(0.752), policies(0.750), internship(0.740) ...
  community: plan(0.771), future(0.745), environment(0.740), approach(0.738), opposite(0.711) ...
  year: week(0.890), season(0.825), month(0.817), approximately(0.778), earlier(0.773) ...
  place: walk(0.831), college(0.808), cuts(0.798), when's(0.798), prison(0.788) ...
  man: woman(0.826), shot(0.811), baby(0.794), trailer(0.793), lady(0.775) ...
  worked: rece(0.705), storms(0.701), citynews(0.699), boo(0.696), tilt(0.692) ...
  already: because(0.807), though(0.796), best(0.791), hardest(0.788), deem(0.787) ...
  recently: angeles(0.733), spiraled(0.724), texas(0.722), maker(0.718), bitcoin(0.714) ...
  woman: car(0.886), shot(0.857), robotic(0.848), man(0.826), unit(0.800) ...
  looking: stand(0.881), wait(0.867), walk(0.855), stew(0.835), going(0.833) ...
  saturday: sunday(0.853), died(0.789), noon(0.782), scored(0.772), november(0.765) ...
  company: firm(0.884), provider(0.863), stock(0.830), business(0.819), biopharmaceutical(0.811) ...
  season: days(0.872), game(0.861), week(0.857), previous(0.849), first(0.847) ...
  january: february(0.918), april(0.908), november(0.902), october(0.888), december(0.887) ...
  research: note(0.853), weight(0.840), outperform(0.788), neutral(0.783), equal(0.782) ...
  women: taken(0.675), players(0.662), people(0.655), printing(0.643), dei(0.642) ...
  child: story(0.824), flashed(0.818), window(0.814), lotus(0.799), brilliant(0.794) ...
  israel: finra(0.857), iran(0.851), julie(0.843), india(0.828), appeals(0.826) ...
  family: vehicle(0.696), reception(0.673), dog(0.664), mother(0.664), coalition(0.661) ...
  death: part(0.774), prison(0.756), swept(0.755), charge(0.749), gone(0.746) ...
  children: goals(0.756), jumping(0.731), residents(0.704), contact(0.702), allowed(0.701) ...
  march: february(0.936), april(0.913), september(0.898), october(0.895), june(0.889) ...
  earlier: ago(0.833), quarterback(0.824), proclamation(0.811), dated(0.809), week(0.795) ...
  october: february(0.928), april(0.921), march(0.895), january(0.888), daytime(0.883) ...
  president: military(0.754), michigan(0.686), leader(0.667), hormonal(0.662), mr(0.659) ...
  better: don't(0.867), seeing(0.858), gonna(0.850), ll(0.844), weird(0.839) ...
  people: residents(0.766), themselves(0.743), them(0.720), projects(0.713), money(0.698) ...
  tuesday: friday(0.930), thursday(0.918), wednesday(0.916), monday(0.915), bethel(0.842) ...
  today: bakery(0.842), early(0.837), plugged(0.836), ever(0.830), days(0.830) ...
  men: conference(0.834), injured(0.788), finished(0.781), consecutive(0.778), winners(0.776) ...
  school: paris(0.782), detroit(0.746), two(0.744), accounts(0.742), eight(0.732) ...
  weeks: hours(0.881), happened(0.874), least(0.872), millionaire(0.855), football(0.855) ...
  military: president(0.754), caused(0.695), directly(0.638), crisis(0.628), leader(0.619) ...
  always: thinking(0.854), too(0.851), what(0.839), sure(0.832), cleaned(0.830) ...
Saved /home/azaliia/projects/LM/practice/artifacts/tables/cosine_cbow_30k_win5_emb100_ep5_vocab30000.csv
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_tsne_before.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_tsne_after.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_tsne_top500.png

=== Cosine similarity (cbow_30k_win2_emb300_ep5_vocab30000) ===
  everyone: anyone(0.831), telesco(0.722), anything(0.720), fortunate(0.708), someone(0.701) ...
  music: events(0.484), owners(0.451), stations(0.451), diagnoses(0.450), art(0.442) ...
  running: desk(0.601), storytelling(0.579), call(0.577), break(0.570), divorce(0.565) ...
  worse: pleased(0.741), happy(0.718), cool(0.715), heats(0.704), squeezed(0.699) ...
  friday: wednesday(0.904), monday(0.889), tuesday(0.874), thursday(0.874), sunday(0.744) ...
  september: june(0.879), february(0.875), october(0.869), april(0.857), march(0.856) ...
  someone: struggling(0.711), everyone(0.701), god(0.689), me(0.681), beijing(0.678) ...
  getting: going(0.663), difficult(0.652), performatively(0.652), gearing(0.651), bracing(0.651) ...
  reported: launched(0.641), damaged(0.640), discharged(0.625), killed(0.621), announced(0.616) ...
  expected: unable(0.814), going(0.809), supposed(0.802), delighted(0.802), scheduled(0.798) ...
  water: ninth(0.620), preparation(0.598), pharmacy(0.591), town(0.588), ballot(0.586) ...
  summer: fourth(0.737), second(0.734), decade(0.719), week(0.715), days(0.715) ...
  monday: friday(0.889), tuesday(0.884), thursday(0.882), wednesday(0.863), saturday(0.754) ...
  million: percent(0.800), billion(0.785), mph(0.758), miles(0.743), trillion(0.733) ...
  director: servant(0.684), secretary(0.678), township(0.677), producer(0.675), demonization(0.668) ...
  staff: discussions(0.566), industries(0.525), pilgrims(0.504), republicans(0.504), patients(0.499) ...
  month: minute(0.847), week(0.828), century(0.802), billion(0.765), bout(0.715) ...
  price: objective(0.762), target(0.719), income(0.699), cent(0.645), respective(0.642) ...
  person: penalty(0.665), miracle(0.635), scary(0.622), present(0.620), point(0.599) ...
  using: overhauled(0.637), within(0.634), winterfest(0.632), peatland(0.625), mykhailo(0.618) ...
  never: ever(0.712), technically(0.707), forecasters(0.703), oh(0.675), actually(0.669) ...
  chief: ahmed(0.785), executive(0.765), prime(0.749), vice(0.746), nitish(0.737) ...
  police: cuomo(0.656), council(0.608), assad(0.603), collins(0.601), officers(0.594) ...
  billion: trillion(0.789), million(0.785), percent(0.783), month(0.765), minute(0.741) ...
  great: good(0.761), wonderful(0.712), child(0.710), limited(0.689), huge(0.681) ...
  wanted: decided(0.842), appears(0.788), want(0.786), refused(0.776), joked(0.774) ...
  human: physical(0.679), health(0.677), cooperation(0.670), technical(0.654), advocates(0.650) ...
  community: public(0.680), appreciation(0.624), forum(0.619), country(0.611), poor(0.601) ...
  year: week(0.795), month(0.715), century(0.665), ninety(0.661), summer(0.622) ...
  place: coming(0.696), attendance(0.693), delay(0.667), scary(0.663), looking(0.652) ...
  man: woman(0.791), tearfully(0.677), injured(0.663), badge(0.660), kid(0.650) ...
  worked: stayed(0.726), dwindled(0.717), appeared(0.711), narcan(0.707), gone(0.706) ...
  already: softened(0.688), suspensions(0.674), seen(0.642), lib(0.642), interestingly(0.640) ...
  recently: afp(0.647), icj(0.621), cu(0.573), thornhill(0.563), stating(0.561) ...
  woman: man(0.791), kid(0.681), tearfully(0.678), injured(0.676), motorist(0.673) ...
  looking: going(0.786), keen(0.785), petrified(0.772), proud(0.750), waiting(0.745) ...
  saturday: thursday(0.785), sunday(0.779), tuesday(0.774), monday(0.754), wednesday(0.746) ...
  company: firm(0.698), retailer(0.689), provider(0.685), world(0.664), business(0.646) ...
  season: week(0.734), days(0.722), beginning(0.711), summer(0.707), biggest(0.704) ...
  january: november(0.882), february(0.878), april(0.874), june(0.872), march(0.872) ...
  research: report(0.598), digit(0.586), anode(0.543), investing(0.541), favorability(0.525) ...
  women: men(0.669), us(0.665), involvement(0.629), residents(0.615), children(0.611) ...
  child: job(0.724), great(0.710), grinding(0.710), desk(0.704), role(0.699) ...
  israel: america(0.662), ukraine(0.637), privatization(0.630), tears(0.629), howard(0.627) ...
  family: coalition(0.610), colleagues(0.609), grandmother(0.600), supporters(0.594), poor(0.594) ...
  death: body(0.701), critique(0.692), actions(0.690), existence(0.650), disappearance(0.646) ...
  children: kids(0.689), fans(0.645), men(0.636), patients(0.629), players(0.619) ...
  march: january(0.872), june(0.865), february(0.857), september(0.856), october(0.850) ...
  earlier: ago(0.706), last(0.657), seven(0.654), later(0.654), barrels(0.654) ...
  october: february(0.878), december(0.875), june(0.869), september(0.869), january(0.856) ...
  president: minister(0.694), chief(0.679), executive(0.669), deputy(0.659), director(0.638) ...
  better: cool(0.697), reasonable(0.696), normal(0.688), safer(0.686), wonderful(0.684) ...
  people: individuals(0.733), students(0.675), voters(0.666), viewers(0.663), things(0.661) ...
  tuesday: thursday(0.899), monday(0.884), friday(0.874), wednesday(0.870), sunday(0.784) ...
  today: valued(0.646), torn(0.624), early(0.622), harrods(0.601), homecoming(0.600) ...
  men: women(0.669), children(0.636), offences(0.605), ranking(0.595), teams(0.595) ...
  school: college(0.636), office(0.635), arctic(0.631), u(0.608), parliament(0.598) ...
  weeks: months(0.863), years(0.850), decades(0.838), hours(0.834), days(0.809) ...
  military: brigid(0.619), superman(0.614), commission(0.610), yaw(0.610), rae(0.596) ...
  always: really(0.795), actually(0.773), quite(0.771), basically(0.747), definitely(0.734) ...
Saved /home/azaliia/projects/LM/practice/artifacts/tables/cosine_cbow_30k_win2_emb300_ep5_vocab30000.csv
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_tsne_before.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_tsne_after.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_tsne_top500.png

=== Cosine similarity (cbow_100k_win2_emb100_ep5_vocab50000) ===
  everyone: anyone(0.832), everybody(0.832), me(0.810), someone(0.788), anybody(0.777) ...
  music: celebrations(0.618), twists(0.562), recognition(0.558), updates(0.556), sensitivity(0.555) ...
  running: playing(0.707), turning(0.697), unemployed(0.667), paying(0.649), putting(0.636) ...
  worse: better(0.745), bigger(0.697), more(0.683), less(0.675), cheaper(0.667) ...
  friday: wednesday(0.942), tuesday(0.938), thursday(0.932), monday(0.926), saturday(0.896) ...
  september: july(0.933), april(0.929), august(0.925), december(0.918), november(0.911) ...
  someone: everyone(0.788), anyone(0.741), him(0.738), me(0.735), herself(0.712) ...
  getting: distressed(0.670), shouting(0.645), yourselves(0.639), uplifted(0.620), deliberation(0.614) ...
  reported: announced(0.616), conducted(0.586), confirmed(0.584), raises(0.573), expects(0.560) ...
  expected: scheduled(0.823), unable(0.783), ready(0.780), supposed(0.776), designed(0.774) ...
  water: pesticides(0.686), funding(0.651), reflections(0.643), buckinghamshire(0.630), prayers(0.619) ...
  summer: season(0.825), game(0.819), week(0.796), weekend(0.791), week's(0.767) ...
  monday: wednesday(0.945), tuesday(0.943), thursday(0.940), friday(0.926), saturday(0.888) ...
  million: billion(0.862), trillion(0.846), lakh(0.783), bn(0.716), mph(0.712) ...
  director: commissioner(0.707), secretary(0.703), chairperson(0.697), mayor(0.685), ceo(0.682) ...
  staff: visitors(0.643), attorneys(0.635), volunteers(0.633), jews(0.631), allies(0.626) ...
  month: week(0.914), year(0.844), minute(0.783), week's(0.744), summer(0.740) ...
  price: bismarck(0.639), ratio(0.611), parrying(0.599), target(0.598), monthly(0.593) ...
  person: question(0.716), thing(0.683), guy(0.639), poem(0.630), movie(0.629) ...
  using: affecting(0.625), upon(0.603), reprising(0.600), within(0.599), regarding(0.586) ...
  never: actually(0.748), always(0.742), surely(0.739), daddy(0.717), genuinely(0.713) ...

## 8. Reuters Classification

Train Reuters CNN classifiers: one random baseline + frozen / fine-tuned pretrained embeddings per CBOW run.

Full mode: `REUTERS_EPOCHS=10`, `REUTERS_MAX_LEN=256`, **EarlyStopping** on `val_loss` (restores best weights) and `val_accuracy`.

In [10]:
from sklearn.metrics import confusion_matrix, f1_score

REUTERS_NUM_CLASSES = 46
REUTERS_BATCH_SIZE = 128 if not DEBUG else 64
REUTERS_RESULTS_PATH = DIR_TABLES / "reuters_results.csv"
REUTERS_RESULT_FIELDS = [
    "run_id",
    "setup",
    "embedding_dim",
    "reuters_vocab_size",
    "coverage_pct",
    "test_loss",
    "test_accuracy",
    "test_macro_f1",
    "train_time_s",
]


def build_reuters_index() -> tuple[dict[int, str], dict[str, int]]:
    """Reuters word_index with Keras +3 offset; inverse id → word."""
    raw_index = reuters.get_word_index()
    index_to_word = {i + 3: w for w, i in raw_index.items()}
    index_to_word[0] = ""
    index_to_word[1] = "<START>"
    index_to_word[2] = "<UNK>"
    word_to_index = {w: i for i, w in index_to_word.items()}
    return index_to_word, word_to_index


def build_pretrained_embedding_matrix(
    E_cbow: np.ndarray,
    cbow_word_index: dict,
    reuters_index_to_word: dict[int, str],
    reuters_vocab_size: int = REUTERS_VOCAB_SIZE,
) -> tuple[np.ndarray, float]:
    """Map CBOW vectors into Reuters embedding matrix; return matrix and coverage %."""
    emb_dim = E_cbow.shape[1]
    matrix = np.random.normal(0, 0.1, (reuters_vocab_size, emb_dim)).astype(np.float32)
    found, total = 0, 0
    for rid in range(3, reuters_vocab_size):
        total += 1
        rw = reuters_index_to_word.get(rid, "")
        if not rw:
            continue
        cw = clean_sentence(rw)
        if cw in cbow_word_index:
            matrix[rid] = E_cbow[cbow_word_index[cw]]
            found += 1
    coverage = 100.0 * found / total if total else 0.0
    return matrix, coverage


def build_reuters_classifier(
    embedding_dim: int,
    embedding_matrix: np.ndarray | None = None,
    trainable_embeddings: bool = True,
    max_len: int = REUTERS_MAX_LEN,
) -> Sequential:
    """CNN text classifier (from course build_model.py)."""
    if embedding_matrix is None:
        emb = Embedding(
            input_dim=REUTERS_VOCAB_SIZE,
            output_dim=embedding_dim,
            input_length=max_len,
        )
    else:
        emb = Embedding(
            input_dim=REUTERS_VOCAB_SIZE,
            output_dim=embedding_dim,
            weights=[embedding_matrix],
            trainable=trainable_embeddings,
            input_length=max_len,
        )
    model = Sequential(
        [
            emb,
            Conv1D(128, 5, activation="relu"),
            MaxPooling1D(5),
            Conv1D(128, 5, activation="relu"),
            GlobalMaxPooling1D(),
            Dense(128, activation="relu"),
            Dropout(0.5),
            Dense(REUTERS_NUM_CLASSES, activation="softmax"),
        ]
    )
    model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
    return model


def plot_reuters_training(history: keras.callbacks.History, run_id: str, setup: str) -> Path:
    h = history.history
    plt.figure(figsize=(10, 4))
    plt.plot(h["loss"], label="train")
    plt.plot(h["val_loss"], label="val")
    plt.plot(h["accuracy"], label="train acc")
    plt.plot(h["val_accuracy"], label="val acc")
    plt.xlabel("Epoch")
    plt.legend()
    plt.title(f"Reuters {setup} — {run_id}")
    return save_fig(f"{run_id}_clf_{setup}_curves")


def plot_confusion_top_classes(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    run_id: str,
    setup: str,
    top_n: int = 10,
) -> Path:
    """Confusion matrix for the *top_n* most frequent true classes."""
    counts = np.bincount(y_true, minlength=REUTERS_NUM_CLASSES)
    top_classes = np.argsort(counts)[-top_n:]
    mask = np.isin(y_true, top_classes)
    cm = confusion_matrix(y_true[mask], y_pred[mask], labels=list(top_classes))
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", xticklabels=top_classes, yticklabels=top_classes)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title(f"Confusion (top-{top_n} classes) — {setup}")
    return save_fig(f"{run_id}_clf_{setup}_confusion")


def train_and_evaluate_reuters(
    run_id: str,
    setup: str,
    embedding_matrix: np.ndarray | None,
    trainable: bool,
    coverage_pct: float = 0.0,
    skip_if_exists: bool = True,
) -> dict | None:
    """Train one Reuters setup and append results to reuters_results.csv."""
    emb_dim = embedding_matrix.shape[1] if embedding_matrix is not None else 100

    if skip_if_exists and REUTERS_RESULTS_PATH.exists():
        done = pd.read_csv(REUTERS_RESULTS_PATH)
        if ((done["run_id"] == run_id) & (done["setup"] == setup)).any():
            print(f"Skipping existing Reuters: {run_id} / {setup}")
            return None

    print(f"\n--- Reuters {setup} | run_id={run_id} | emb_dim={emb_dim} ---")
    keras.backend.clear_session()
    model = build_reuters_classifier(emb_dim, embedding_matrix, trainable_embeddings=trainable)

    reuters_callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=REUTERS_EARLY_STOP_PATIENCE,
            restore_best_weights=True,
            verbose=1,
        ),
        EarlyStopping(
            monitor="val_accuracy",
            mode="max",
            patience=REUTERS_EARLY_STOP_PATIENCE,
            restore_best_weights=False,
            verbose=0,
        ),
    ]

    t0 = time.perf_counter()
    history = model.fit(
        X_rt_tr,
        y_rt_train_cat,
        validation_data=(X_rt_val, y_rt_val_cat),
        epochs=REUTERS_EPOCHS,
        batch_size=REUTERS_BATCH_SIZE,
        callbacks=reuters_callbacks,
        verbose=1,
    )
    train_time_s = time.perf_counter() - t0

    test_loss, test_acc = model.evaluate(X_rt_test, y_rt_test_cat, verbose=0)
    y_pred = np.argmax(model.predict(X_rt_test, verbose=0), axis=1)
    macro_f1 = f1_score(y_rt_test, y_pred, average="macro", zero_division=0)

    plot_reuters_training(history, run_id, setup)
    plot_confusion_top_classes(y_rt_test, y_pred, run_id, setup)

    row = {
        "run_id": run_id,
        "setup": setup,
        "embedding_dim": emb_dim,
        "reuters_vocab_size": REUTERS_VOCAB_SIZE,
        "coverage_pct": round(coverage_pct, 2),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_acc),
        "test_macro_f1": float(macro_f1),
        "train_time_s": round(train_time_s, 2),
    }
    append_row(REUTERS_RESULTS_PATH, row, fieldnames=REUTERS_RESULT_FIELDS)
    print(f"  test_acc={test_acc:.4f}  macro_f1={macro_f1:.4f}  coverage={coverage_pct:.1f}%")
    keras.backend.clear_session()
    return row


# Ensure experiments table exists (if §7 was skipped)
if "experiments_unique" not in globals():
    experiments_unique = pd.read_csv(EXPERIMENTS_CSV_PATH).drop_duplicates(
        subset=["run_id"], keep="last"
    )

# --- Load & preprocess Reuters ---
print("Loading Reuters dataset...")
(X_rt_train, y_rt_train), (X_rt_test, y_rt_test) = reuters.load_data(num_words=REUTERS_VOCAB_SIZE)
reuters_index_to_word, _ = build_reuters_index()

X_rt_train = pad_sequences(X_rt_train, maxlen=REUTERS_MAX_LEN, padding="post", truncating="post")
X_rt_test = pad_sequences(X_rt_test, maxlen=REUTERS_MAX_LEN, padding="post", truncating="post")

# Train/val split from training portion
X_rt_tr, X_rt_val, y_rt_tr, y_rt_val = train_test_split(
    X_rt_train,
    y_rt_train,
    test_size=VAL_FRACTION,
    random_state=RANDOM_SEED,
    stratify=y_rt_train,
)
y_rt_train_cat = to_categorical(y_rt_tr, REUTERS_NUM_CLASSES)
y_rt_val_cat = to_categorical(y_rt_val, REUTERS_NUM_CLASSES)
y_rt_test_cat = to_categorical(y_rt_test, REUTERS_NUM_CLASSES)

print(
    f"Reuters: train={len(y_rt_tr):,} val={len(y_rt_val):,} test={len(y_rt_test):,} | "
    f"max_len={REUTERS_MAX_LEN} epochs={REUTERS_EPOCHS}"
)
assert len(X_rt_tr) == len(y_rt_train_cat), "Train X/y size mismatch"
assert len(X_rt_val) == len(y_rt_val_cat), "Val X/y size mismatch"

# --- Baseline (random embeddings, dim=100) ---
BASELINE_DIM = 100
train_and_evaluate_reuters(
    "baseline_random",
    "baseline",
    embedding_matrix=None,
    trainable=True,
    coverage_pct=0.0,
)

# --- Per CBOW run: frozen + fine-tune ---
reuters_rows: list[dict] = []
for _, exp_row in experiments_unique.iterrows():
    rid = exp_row["run_id"]
    E_cbow, cbow_wi, _, _ = load_run_artifacts(rid)
    emb_matrix, coverage = build_pretrained_embedding_matrix(E_cbow, cbow_wi, reuters_index_to_word)

    for setup, trainable in [("frozen", False), ("finetune", True)]:
        row = train_and_evaluate_reuters(
            rid,
            setup,
            emb_matrix.copy(),
            trainable,
            coverage_pct=coverage,
        )
        if row:
            reuters_rows.append(row)

print("\n=== Reuters results ===")
display(pd.read_csv(REUTERS_RESULTS_PATH))

Loading Reuters dataset...
Reuters: train=8,083 val=899 test=2,246 | max_len=256 epochs=10

--- Reuters baseline | run_id=baseline_random | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779305768.102243  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26528587__.31
I0000 00:00:1779305768.591705  139930 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1779305768.851157  139930 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
W0000 00:00:1779305769.071465  155485 hlo_rematerialization.cc:3204] Can't reduce memory use below 9.10GiB (9775475697 bytes) by rematerialization; only reduced to 12.61GiB (13543401504 bytes), down from 12.61GiB (13543401504 bytes) originally
W0000 00:00:1779305779.156922  139930 bfc_allocator.cc:502] Allocator (GPU_0_bfc) ran out of memory trying to allocate 12.60GiB (rounded to 13526886912)requested by op
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
I0000 00:00:1779305779.157510  139930 bfc_allocator.cc:1049] BFCAllocator dump for GPU_0_bfc
I0000 00:00:1779305779.157523  139930 bfc_allocator.cc:1056] Bin (256): 	Total Chunks: 111, Chunks in use: 109. 27.8KiB allocated for chunks. 27.2KiB in use in bin. 693B client-requested in use in bin.
I0000 00:00:1779305779.157543  139930 bfc_allocator.cc:1056] Bin (512): 	Total Chunks: 4, Chunks in use: 1. 2.2KiB allocated for chunks. 512B in use in bin. 512B client-requested in use in bin.
I0000 00:00:1779305779.157550  139930 bfc_allocator.cc:1056] Bin (1024): 	Total Chunks: 2, Chunks in use: 1. 2.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
I0000 00:00:1779305779.157555  139930 bfc_allocator.cc:1056] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157561  139930 bfc_allocator.cc:1056] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157566  139930 bfc_allocator.cc:1056] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157571  139930 bfc_allocator.cc:1056] Bin (16384): 	Total Chunks: 3, Chunks in use: 3. 69.0KiB allocated for chunks. 69.0KiB in use in bin. 69.0KiB client-requested in use in bin.
I0000 00:00:1779305779.157577  139930 bfc_allocator.cc:1056] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157581  139930 bfc_allocator.cc:1056] Bin (65536): 	Total Chunks: 3, Chunks in use: 2. 264.5KiB allocated for chunks. 163.0KiB in use in bin. 128.0KiB client-requested in use in bin.
I0000 00:00:1779305779.157587  139930 bfc_allocator.cc:1056] Bin (131072): 	Total Chunks: 4, Chunks in use: 4. 862.5KiB allocated for chunks. 862.5KiB in use in bin. 862.4KiB client-requested in use in bin.
I0000 00:00:1779305779.157593  139930 bfc_allocator.cc:1056] Bin (262144): 	Total Chunks: 2, Chunks in use: 2. 787.0KiB allocated for chunks. 787.0KiB in use in bin. 640.0KiB client-requested in use in bin.
I0000 00:00:1779305779.157599  139930 bfc_allocator.cc:1056] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157604  139930 bfc_allocator.cc:1056] Bin (1048576): 	Total Chunks: 1, Chunks in use: 1. 1.42MiB allocated for chunks. 1.42MiB in use in bin. 1.42MiB client-requested in use in bin.
I0000 00:00:1779305779.157610  139930 bfc_allocator.cc:1056] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157615  139930 bfc_allocator.cc:1056] Bin (4194304): 	Total Chunks: 2, Chunks in use: 2. 15.26MiB allocated for chunks. 15.26MiB in use in bin. 15.26MiB client-requested in use in bin.
I0000 00:00:1779305779.157621  139930 bfc_allocator.cc:1056] Bin (8388608): 	Total Chunks: 2, Chunks in use: 2. 31.50MiB allocated for chunks. 31.50MiB in use in bin. 31.50MiB client-requested in use in bin.
I0000 00:00:1779305779.157629  139930 bfc_allocator.cc:1056] Bin (16777216): 	Total Chunks: 3, Chunks in use: 3. 62.32MiB allocated for chunks. 62.32MiB in use in bin. 60.74MiB client-requested in use in bin.
I0000 00:00:1779305779.157636  139930 bfc_allocator.cc:1056] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157641  139930 bfc_allocator.cc:1056] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157652  139930 bfc_allocator.cc:1056] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157657  139930 bfc_allocator.cc:1056] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 9.18GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305779.157663  139930 bfc_allocator.cc:1072] Bin for 12.60GiB was 256.00MiB, Chunk State:
I0000 00:00:1779305779.157668  139930 bfc_allocator.cc:1078]   Size: 9.18GiB | Requested Size: 41.32MiB | in_use: 0 | bin_num: 20, prev:   Size: 15.75MiB | Requested Size: 15.75MiB | in_use: 1 | bin_num: -1
I0000 00:00:1779305779.157680  139930 bfc_allocator.cc:1085] Next region of size 9970909184
I0000 00:00:1779305779.157686  139930 bfc_allocator.cc:1105] InUse at 70b400000 of size 1280 next 1
I0000 00:00:1779305779.157691  139930 bfc_allocator.cc:1105] InUse at 70b400500 of size 256 next 2
I0000 00:00:1779305779.157694  139930 bfc_allocator.cc:1105] InUse at 70b400600 of size 256 next 3
I0000 00:00:1779305779.157697  139930 bfc_allocator.cc:1105] InUse at 70b400700 of size 256 next 4
I0000 00:00:1779305779.157700  139930 bfc_allocator.cc:1105] InUse at 70b400800 of size 256 next 5
I0000 00:00:1779305779.157702  139930 bfc_allocator.cc:1105] InUse at 70b400900 of size 256 next 6
I0000 00:00:1779305779.157706  139930 bfc_allocator.cc:1105] InUse at 70b400a00 of size 240128 next 7
I0000 00:00:1779305779.157710  139930 bfc_allocator.cc:1105] InUse at 70b43b400 of size 23552 next 53
I0000 00:00:1779305779.157715  139930 bfc_allocator.cc:1105] InUse at 70b441000 of size 65536 next 134
I0000 00:00:1779305779.157718  139930 bfc_allocator.cc:1105] InUse at 70b451000 of size 23552 next 113
I0000 00:00:1779305779.157721  139930 bfc_allocator.cc:1105] InUse at 70b456c00 of size 23552 next 170
I0000 00:00:1779305779.157724  139930 bfc_allocator.cc:1105] Free  at 70b45c800 of size 103936 next 8
I0000 00:00:1779305779.157727  139930 bfc_allocator.cc:1105] InUse at 70b475e00 of size 256 next 9
I0000 00:00:1779305779.157730  139930 bfc_allocator.cc:1105] InUse at 70b475f00 of size 256 next 10
I0000 00:00:1779305779.157733  139930 bfc_allocator.cc:1105] InUse at 70b476000 of size 256 next 12
I0000 00:00:1779305779.157736  139930 bfc_allocator.cc:1105] InUse at 70b476100 of size 256 next 13
I0000 00:00:1779305779.157739  139930 bfc_allocator.cc:1105] InUse at 70b476200 of size 512 next 14
I0000 00:00:1779305779.157742  139930 bfc_allocator.cc:1105] InUse at 70b476400 of size 256 next 17
I0000 00:00:1779305779.157745  139930 bfc_allocator.cc:1105] InUse at 70b476500 of size 256 next 11
I0000 00:00:1779305779.157747  139930 bfc_allocator.cc:1105] InUse at 70b476600 of size 256 next 21
I0000 00:00:1779305779.157750  139930 bfc_allocator.cc:1105] InUse at 70b476700 of size 256 next 22
I0000 00:00:1779305779.157753  139930 bfc_allocator.cc:1105] InUse at 70b476800 of size 256 next 25
I0000 00:00:1779305779.157756  139930 bfc_allocator.cc:1105] InUse at 70b476900 of size 256 next 66
I0000 00:00:1779305779.157759  139930 bfc_allocator.cc:1105] InUse at 70b476a00 of size 256 next 27
I0000 00:00:1779305779.157762  139930 bfc_allocator.cc:1105] InUse at 70b476b00 of size 256 next 38
I0000 00:00:1779305779.157765  139930 bfc_allocator.cc:1105] InUse at 70b476c00 of size 256 next 29
I0000 00:00:1779305779.157767  139930 bfc_allocator.cc:1105] InUse at 70b476d00 of size 256 next 30
I0000 00:00:1779305779.157770  139930 bfc_allocator.cc:1105] InUse at 70b476e00 of size 256 next 31
I0000 00:00:1779305779.157773  139930 bfc_allocator.cc:1105] InUse at 70b476f00 of size 256 next 32
I0000 00:00:1779305779.157776  139930 bfc_allocator.cc:1105] InUse at 70b477000 of size 256 next 33
I0000 00:00:1779305779.157779  139930 bfc_allocator.cc:1105] InUse at 70b477100 of size 256 next 34
I0000 00:00:1779305779.157782  139930 bfc_allocator.cc:1105] InUse at 70b477200 of size 256 next 35
I0000 00:00:1779305779.157786  139930 bfc_allocator.cc:1105] InUse at 70b477300 of size 256 next 36
I0000 00:00:1779305779.157789  139930 bfc_allocator.cc:1105] InUse at 70b477400 of size 256 next 124
I0000 00:00:1779305779.157794  139930 bfc_allocator.cc:1105] InUse at 70b477500 of size 256 next 20
I0000 00:00:1779305779.157797  139930 bfc_allocator.cc:1105] InUse at 70b477600 of size 256 next 81
I0000 00:00:1779305779.157800  139930 bfc_allocator.cc:1105] InUse at 70b477700 of size 256 next 104
I0000 00:00:1779305779.157803  139930 bfc_allocator.cc:1105] InUse at 70b477800 of size 256 next 103
I0000 00:00:1779305779.157806  139930 bfc_allocator.cc:1105] InUse at 70b477900 of size 256 next 97
I0000 00:00:1779305779.157809  139930 bfc_allocator.cc:1105] InUse at 70b477a00 of size 256 next 98
I0000 00:00:1779305779.157812  139930 bfc_allocator.cc:1105] InUse at 70b477b00 of size 256 next 83
I0000 00:00:1779305779.157815  139930 bfc_allocator.cc:1105] InUse at 70b477c00 of size 256 next 80
I0000 00:00:1779305779.157817  139930 bfc_allocator.cc:1105] InUse at 70b477d00 of size 256 next 85
I0000 00:00:1779305779.157820  139930 bfc_allocator.cc:1105] InUse at 70b477e00 of size 256 next 135
I0000 00:00:1779305779.157823  139930 bfc_allocator.cc:1105] InUse at 70b477f00 of size 256 next 90
I0000 00:00:1779305779.157826  139930 bfc_allocator.cc:1105] InUse at 70b478000 of size 256 next 127
I0000 00:00:1779305779.157829  139930 bfc_allocator.cc:1105] InUse at 70b478100 of size 256 next 24
I0000 00:00:1779305779.157832  139930 bfc_allocator.cc:1105] InUse at 70b478200 of size 256 next 129
I0000 00:00:1779305779.157835  139930 bfc_allocator.cc:1105] InUse at 70b478300 of size 256 next 18
I0000 00:00:1779305779.157837  139930 bfc_allocator.cc:1105] Free  at 70b478400 of size 512 next 117
I0000 00:00:1779305779.157840  139930 bfc_allocator.cc:1105] InUse at 70b478600 of size 256 next 84
I0000 00:00:1779305779.157843  139930 bfc_allocator.cc:1105] InUse at 70b478700 of size 256 next 158
I0000 00:00:1779305779.157846  139930 bfc_allocator.cc:1105] Free  at 70b478800 of size 256 next 157
I0000 00:00:1779305779.157849  139930 bfc_allocator.cc:1105] InUse at 70b478900 of size 256 next 76
I0000 00:00:1779305779.157852  139930 bfc_allocator.cc:1105] InUse at 70b478a00 of size 256 next 74
I0000 00:00:1779305779.157855  139930 bfc_allocator.cc:1105] InUse at 70b478b00 of size 256 next 114
I0000 00:00:1779305779.157857  139930 bfc_allocator.cc:1105] InUse at 70b478c00 of size 256 next 96
I0000 00:00:1779305779.157860  139930 bfc_allocator.cc:1105] InUse at 70b478d00 of size 256 next 95
I0000 00:00:1779305779.157863  139930 bfc_allocator.cc:1105] InUse at 70b478e00 of size 256 next 107
I0000 00:00:1779305779.157866  139930 bfc_allocator.cc:1105] InUse at 70b478f00 of size 256 next 110
I0000 00:00:1779305779.157869  139930 bfc_allocator.cc:1105] InUse at 70b479000 of size 256 next 99
I0000 00:00:1779305779.157871  139930 bfc_allocator.cc:1105] InUse at 70b479100 of size 256 next 106
I0000 00:00:1779305779.157874  139930 bfc_allocator.cc:1105] InUse at 70b479200 of size 256 next 65
I0000 00:00:1779305779.157877  139930 bfc_allocator.cc:1105] InUse at 70b479300 of size 256 next 42
I0000 00:00:1779305779.157880  139930 bfc_allocator.cc:1105] InUse at 70b479400 of size 256 next 26
I0000 00:00:1779305779.157883  139930 bfc_allocator.cc:1105] InUse at 70b479500 of size 256 next 62
I0000 00:00:1779305779.157885  139930 bfc_allocator.cc:1105] InUse at 70b479600 of size 256 next 63
I0000 00:00:1779305779.157888  139930 bfc_allocator.cc:1105] InUse at 70b479700 of size 256 next 69
I0000 00:00:1779305779.157891  139930 bfc_allocator.cc:1105] InUse at 70b479800 of size 256 next 60
I0000 00:00:1779305779.157894  139930 bfc_allocator.cc:1105] InUse at 70b479900 of size 256 next 68
I0000 00:00:1779305779.157897  139930 bfc_allocator.cc:1105] InUse at 70b479a00 of size 256 next 67
I0000 00:00:1779305779.157899  139930 bfc_allocator.cc:1105] InUse at 70b479b00 of size 256 next 41
I0000 00:00:1779305779.157903  139930 bfc_allocator.cc:1105] InUse at 70b479c00 of size 256 next 75
I0000 00:00:1779305779.157906  139930 bfc_allocator.cc:1105] InUse at 70b479d00 of size 256 next 105
I0000 00:00:1779305779.157909  139930 bfc_allocator.cc:1105] InUse at 70b479e00 of size 256 next 45
I0000 00:00:1779305779.157912  139930 bfc_allocator.cc:1105] InUse at 70b479f00 of size 256 next 44
I0000 00:00:1779305779.157915  139930 bfc_allocator.cc:1105] InUse at 70b47a000 of size 256 next 120
I0000 00:00:1779305779.157918  139930 bfc_allocator.cc:1105] InUse at 70b47a100 of size 256 next 40
I0000 00:00:1779305779.157920  139930 bfc_allocator.cc:1105] InUse at 70b47a200 of size 256 next 64
I0000 00:00:1779305779.157924  139930 bfc_allocator.cc:1105] InUse at 70b47a300 of size 1487360 next 46
I0000 00:00:1779305779.157928  139930 bfc_allocator.cc:1105] InUse at 70b5e5500 of size 8000000 next 126
I0000 00:00:1779305779.157931  139930 bfc_allocator.cc:1105] InUse at 70bd86700 of size 8000000 next 148
I0000 00:00:1779305779.157936  139930 bfc_allocator.cc:1105] InUse at 70c527900 of size 131072 next 130
I0000 00:00:1779305779.157940  139930 bfc_allocator.cc:1105] InUse at 70c547900 of size 18690304 next 160
I0000 00:00:1779305779.157943  139930 bfc_allocator.cc:1105] InUse at 70d71aa00 of size 256 next 132
I0000 00:00:1779305779.157946  139930 bfc_allocator.cc:1105] InUse at 70d71ab00 of size 256 next 144
I0000 00:00:1779305779.157949  139930 bfc_allocator.cc:1105] InUse at 70d71ac00 of size 256 next 165
I0000 00:00:1779305779.157952  139930 bfc_allocator.cc:1105] InUse at 70d71ad00 of size 101376 next 39
I0000 00:00:1779305779.157955  139930 bfc_allocator.cc:1105] InUse at 70d733900 of size 256 next 82
I0000 00:00:1779305779.157958  139930 bfc_allocator.cc:1105] InUse at 70d733a00 of size 256 next 136
I0000 00:00:1779305779.157961  139930 bfc_allocator.cc:1105] InUse at 70d733b00 of size 256 next 112
I0000 00:00:1779305779.157970  139930 bfc_allocator.cc:1105] Free  at 70d733c00 of size 256 next 49
I0000 00:00:1779305779.157973  139930 bfc_allocator.cc:1105] InUse at 70d733d00 of size 256 next 150
I0000 00:00:1779305779.157976  139930 bfc_allocator.cc:1105] InUse at 70d733e00 of size 256 next 133
I0000 00:00:1779305779.157979  139930 bfc_allocator.cc:1105] InUse at 70d733f00 of size 256 next 16
I0000 00:00:1779305779.157982  139930 bfc_allocator.cc:1105] InUse at 70d734000 of size 256 next 57
I0000 00:00:1779305779.157984  139930 bfc_allocator.cc:1105] InUse at 70d734100 of size 256 next 86
I0000 00:00:1779305779.157987  139930 bfc_allocator.cc:1105] InUse at 70d734200 of size 256 next 115
I0000 00:00:1779305779.157990  139930 bfc_allocator.cc:1105] InUse at 70d734300 of size 256 next 59
I0000 00:00:1779305779.157993  139930 bfc_allocator.cc:1105] InUse at 70d734400 of size 256 next 146
I0000 00:00:1779305779.157996  139930 bfc_allocator.cc:1105] InUse at 70d734500 of size 256 next 140
I0000 00:00:1779305779.157998  139930 bfc_allocator.cc:1105] InUse at 70d734600 of size 256 next 138
I0000 00:00:1779305779.158001  139930 bfc_allocator.cc:1105] Free  at 70d734700 of size 1024 next 141
I0000 00:00:1779305779.158004  139930 bfc_allocator.cc:1105] InUse at 70d734b00 of size 256 next 79
I0000 00:00:1779305779.158007  139930 bfc_allocator.cc:1105] InUse at 70d734c00 of size 256 next 54
I0000 00:00:1779305779.158010  139930 bfc_allocator.cc:1105] Free  at 70d734d00 of size 512 next 145
I0000 00:00:1779305779.158013  139930 bfc_allocator.cc:1105] InUse at 70d734f00 of size 256 next 108
I0000 00:00:1779305779.158016  139930 bfc_allocator.cc:1105] InUse at 70d735000 of size 256 next 71
I0000 00:00:1779305779.158018  139930 bfc_allocator.cc:1105] InUse at 70d735100 of size 256 next 101
I0000 00:00:1779305779.158021  139930 bfc_allocator.cc:1105] InUse at 70d735200 of size 256 next 122
I0000 00:00:1779305779.158024  139930 bfc_allocator.cc:1105] InUse at 70d735300 of size 256 next 155
I0000 00:00:1779305779.158027  139930 bfc_allocator.cc:1105] InUse at 70d735400 of size 256 next 116
I0000 00:00:1779305779.158031  139930 bfc_allocator.cc:1105] Free  at 70d735500 of size 768 next 109
I0000 00:00:1779305779.158034  139930 bfc_allocator.cc:1105] InUse at 70d735800 of size 256 next 123
I0000 00:00:1779305779.158037  139930 bfc_allocator.cc:1105] InUse at 70d735900 of size 256 next 121
I0000 00:00:1779305779.158040  139930 bfc_allocator.cc:1105] InUse at 70d735a00 of size 256 next 173
I0000 00:00:1779305779.158043  139930 bfc_allocator.cc:1105] InUse at 70d735b00 of size 256 next 48
I0000 00:00:1779305779.158045  139930 bfc_allocator.cc:1105] InUse at 70d735c00 of size 256 next 137
I0000 00:00:1779305779.158048  139930 bfc_allocator.cc:1105] InUse at 70d735d00 of size 256 next 125
I0000 00:00:1779305779.158051  139930 bfc_allocator.cc:1105] InUse at 70d735e00 of size 256 next 89
I0000 00:00:1779305779.158055  139930 bfc_allocator.cc:1105] InUse at 70d735f00 of size 256 next 131
I0000 00:00:1779305779.158058  139930 bfc_allocator.cc:1105] InUse at 70d736000 of size 256 next 152
I0000 00:00:1779305779.158061  139930 bfc_allocator.cc:1105] InUse at 70d736100 of size 256 next 143
I0000 00:00:1779305779.158064  139930 bfc_allocator.cc:1105] InUse at 70d736200 of size 256 next 119
I0000 00:00:1779305779.158067  139930 bfc_allocator.cc:1105] InUse at 70d736300 of size 256 next 43
I0000 00:00:1779305779.158069  139930 bfc_allocator.cc:1105] InUse at 70d736400 of size 256 next 47
I0000 00:00:1779305779.158072  139930 bfc_allocator.cc:1105] InUse at 70d736500 of size 256 next 55
I0000 00:00:1779305779.158076  139930 bfc_allocator.cc:1105] InUse at 70d736600 of size 256000 next 100
I0000 00:00:1779305779.158080  139930 bfc_allocator.cc:1105] InUse at 70d774e00 of size 327680 next 118
I0000 00:00:1779305779.158083  139930 bfc_allocator.cc:1105] InUse at 70d7c4e00 of size 256000 next 153
I0000 00:00:1779305779.158087  139930 bfc_allocator.cc:1105] InUse at 70d803600 of size 478208 next 149
I0000 00:00:1779305779.158090  139930 bfc_allocator.cc:1105] InUse at 70d878200 of size 256 next 151
I0000 00:00:1779305779.158093  139930 bfc_allocator.cc:1105] InUse at 70d878300 of size 256 next 177
I0000 00:00:1779305779.158096  139930 bfc_allocator.cc:1105] InUse at 70d878400 of size 29884416 next 172
I0000 00:00:1779305779.158100  139930 bfc_allocator.cc:1105] InUse at 70f4f8400 of size 16777728 next 78
I0000 00:00:1779305779.158103  139930 bfc_allocator.cc:1105] InUse at 7104f8600 of size 16515072 next 94
I0000 00:00:1779305779.158106  139930 bfc_allocator.cc:1105] InUse at 7114b8600 of size 16515072 next 147
I0000 00:00:1779305779.158110  139930 bfc_allocator.cc:1105] Free  at 712478600 of size 9852975616 next 18446744073709551615
I0000 00:00:1779305779.158113  139930 bfc_allocator.cc:1110]      Summary of in-use Chunks by size:

57/64 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3318 - loss: 2.9236

I0000 00:00:1779305794.163885  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26528587__.31
I0000 00:00:1779305795.016626  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3400 - loss: 2.8686

I0000 00:00:1779305797.289868  139931 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
W0000 00:00:1779305797.663697  156126 hlo_rematerialization.cc:3204] Can't reduce memory use below 9.10GiB (9775475697 bytes) by rematerialization; only reduced to 12.61GiB (13543401504 bytes), down from 12.61GiB (13543401504 bytes) originally
W0000 00:00:1779305807.856868  139931 bfc_allocator.cc:502] Allocator (GPU_0_bfc) ran out of memory trying to allocate 12.60GiB (rounded to 13526886912)requested by op
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
I0000 00:00:1779305807.856931  139931 bfc_allocator.cc:1049] BFCAllocator dump for GPU_0_bfc
I0000 00:00:1779305807.856935  139931 bfc_allocator.cc:1056] Bin (256): 	Total Chunks: 117, Chunks in use: 116. 29.2KiB allocated for chunks. 29.0KiB in use in bin. 1.1KiB client-requested in use in bin.
I0000 00:00:1779305807.856939  139931 bfc_allocator.cc:1056] Bin (512): 	Total Chunks: 10, Chunks in use: 9. 5.2KiB allocated for chunks. 4.8KiB in use in bin. 4.5KiB client-requested in use in bin.
I0000 00:00:1779305807.856941  139931 bfc_allocator.cc:1056] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
I0000 00:00:1779305807.856942  139931 bfc_allocator.cc:1056] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856944  139931 bfc_allocator.cc:1056] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856945  139931 bfc_allocator.cc:1056] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856946  139931 bfc_allocator.cc:1056] Bin (16384): 	Total Chunks: 5, Chunks in use: 4. 115.5KiB allocated for chunks. 92.0KiB in use in bin. 92.0KiB client-requested in use in bin.
I0000 00:00:1779305807.856948  139931 bfc_allocator.cc:1056] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856949  139931 bfc_allocator.cc:1056] Bin (65536): 	Total Chunks: 4, Chunks in use: 3. 326.0KiB allocated for chunks. 227.0KiB in use in bin. 192.0KiB client-requested in use in bin.
I0000 00:00:1779305807.856951  139931 bfc_allocator.cc:1056] Bin (131072): 	Total Chunks: 7, Chunks in use: 7. 1.49MiB allocated for chunks. 1.49MiB in use in bin. 1.49MiB client-requested in use in bin.
I0000 00:00:1779305807.856952  139931 bfc_allocator.cc:1056] Bin (262144): 	Total Chunks: 4, Chunks in use: 3. 1.48MiB allocated for chunks. 1.08MiB in use in bin. 960.0KiB client-requested in use in bin.
I0000 00:00:1779305807.856954  139931 bfc_allocator.cc:1056] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856955  139931 bfc_allocator.cc:1056] Bin (1048576): 	Total Chunks: 1, Chunks in use: 1. 1.42MiB allocated for chunks. 1.42MiB in use in bin. 1.42MiB client-requested in use in bin.
I0000 00:00:1779305807.856956  139931 bfc_allocator.cc:1056] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856958  139931 bfc_allocator.cc:1056] Bin (4194304): 	Total Chunks: 3, Chunks in use: 2. 22.89MiB allocated for chunks. 15.26MiB in use in bin. 15.26MiB client-requested in use in bin.
I0000 00:00:1779305807.856959  139931 bfc_allocator.cc:1056] Bin (8388608): 	Total Chunks: 4, Chunks in use: 4. 56.96MiB allocated for chunks. 56.96MiB in use in bin. 54.88MiB client-requested in use in bin.
I0000 00:00:1779305807.856960  139931 bfc_allocator.cc:1056] Bin (16777216): 	Total Chunks: 3, Chunks in use: 3. 75.27MiB allocated for chunks. 75.27MiB in use in bin. 60.74MiB client-requested in use in bin.
I0000 00:00:1779305807.856962  139931 bfc_allocator.cc:1056] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856963  139931 bfc_allocator.cc:1056] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856964  139931 bfc_allocator.cc:1056] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856966  139931 bfc_allocator.cc:1056] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 9.13GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305807.856968  139931 bfc_allocator.cc:1072] Bin for 12.60GiB was 256.00MiB, Chunk State:
I0000 00:00:1779305807.856970  139931 bfc_allocator.cc:1078]   Size: 9.13GiB | Requested Size: 41.32MiB | in_use: 0 | bin_num: 20, prev:   Size: 15.75MiB | Requested Size: 15.75MiB | in_use: 1 | bin_num: -1
I0000 00:00:1779305807.856973  139931 bfc_allocator.cc:1085] Next region of size 9970909184
I0000 00:00:1779305807.856976  139931 bfc_allocator.cc:1105] InUse at 70b400000 of size 1280 next 1
I0000 00:00:1779305807.856977  139931 bfc_allocator.cc:1105] InUse at 70b400500 of size 256 next 2
I0000 00:00:1779305807.856978  139931 bfc_allocator.cc:1105] InUse at 70b400600 of size 256 next 3
I0000 00:00:1779305807.856978  139931 bfc_allocator.cc:1105] InUse at 70b400700 of size 256 next 4
I0000 00:00:1779305807.856979  139931 bfc_allocator.cc:1105] InUse at 70b400800 of size 256 next 5
I0000 00:00:1779305807.856980  139931 bfc_allocator.cc:1105] InUse at 70b400900 of size 256 next 6
I0000 00:00:1779305807.856981  139931 bfc_allocator.cc:1105] InUse at 70b400a00 of size 240128 next 7
I0000 00:00:1779305807.856982  139931 bfc_allocator.cc:1105] InUse at 70b43b400 of size 23552 next 53
I0000 00:00:1779305807.856983  139931 bfc_allocator.cc:1105] InUse at 70b441000 of size 65536 next 134
I0000 00:00:1779305807.856984  139931 bfc_allocator.cc:1105] InUse at 70b451000 of size 23552 next 113
I0000 00:00:1779305807.856985  139931 bfc_allocator.cc:1105] Free  at 70b456c00 of size 24064 next 51
I0000 00:00:1779305807.856986  139931 bfc_allocator.cc:1105] InUse at 70b45ca00 of size 512 next 52
I0000 00:00:1779305807.856986  139931 bfc_allocator.cc:1105] InUse at 70b45cc00 of size 512 next 23
I0000 00:00:1779305807.856987  139931 bfc_allocator.cc:1105] InUse at 70b45ce00 of size 512 next 175
I0000 00:00:1779305807.856988  139931 bfc_allocator.cc:1105] InUse at 70b45d000 of size 512 next 174
I0000 00:00:1779305807.856991  139931 bfc_allocator.cc:1105] InUse at 70b45d200 of size 101376 next 8
I0000 00:00:1779305807.856992  139931 bfc_allocator.cc:1105] InUse at 70b475e00 of size 256 next 9
I0000 00:00:1779305807.856992  139931 bfc_allocator.cc:1105] InUse at 70b475f00 of size 256 next 10
I0000 00:00:1779305807.856993  139931 bfc_allocator.cc:1105] InUse at 70b476000 of size 256 next 12
I0000 00:00:1779305807.856994  139931 bfc_allocator.cc:1105] InUse at 70b476100 of size 256 next 13
I0000 00:00:1779305807.856994  139931 bfc_allocator.cc:1105] InUse at 70b476200 of size 256 next 70
I0000 00:00:1779305807.856995  139931 bfc_allocator.cc:1105] Free  at 70b476300 of size 256 next 14
I0000 00:00:1779305807.856996  139931 bfc_allocator.cc:1105] InUse at 70b476400 of size 256 next 17
I0000 00:00:1779305807.856997  139931 bfc_allocator.cc:1105] InUse at 70b476500 of size 256 next 11
I0000 00:00:1779305807.856997  139931 bfc_allocator.cc:1105] InUse at 70b476600 of size 256 next 21
I0000 00:00:1779305807.856998  139931 bfc_allocator.cc:1105] InUse at 70b476700 of size 256 next 22
I0000 00:00:1779305807.856999  139931 bfc_allocator.cc:1105] InUse at 70b476800 of size 256 next 25
I0000 00:00:1779305807.857000  139931 bfc_allocator.cc:1105] InUse at 70b476900 of size 256 next 66
I0000 00:00:1779305807.857000  139931 bfc_allocator.cc:1105] InUse at 70b476a00 of size 256 next 27
I0000 00:00:1779305807.857001  139931 bfc_allocator.cc:1105] InUse at 70b476b00 of size 256 next 38
I0000 00:00:1779305807.857002  139931 bfc_allocator.cc:1105] InUse at 70b476c00 of size 256 next 29
I0000 00:00:1779305807.857002  139931 bfc_allocator.cc:1105] InUse at 70b476d00 of size 256 next 30
I0000 00:00:1779305807.857003  139931 bfc_allocator.cc:1105] InUse at 70b476e00 of size 256 next 31
I0000 00:00:1779305807.857004  139931 bfc_allocator.cc:1105] InUse at 70b476f00 of size 256 next 32
I0000 00:00:1779305807.857005  139931 bfc_allocator.cc:1105] InUse at 70b477000 of size 256 next 33
I0000 00:00:1779305807.857006  139931 bfc_allocator.cc:1105] InUse at 70b477100 of size 256 next 34
I0000 00:00:1779305807.857007  139931 bfc_allocator.cc:1105] InUse at 70b477200 of size 256 next 35
I0000 00:00:1779305807.857007  139931 bfc_allocator.cc:1105] InUse at 70b477300 of size 256 next 36
I0000 00:00:1779305807.857008  139931 bfc_allocator.cc:1105] InUse at 70b477400 of size 256 next 124
I0000 00:00:1779305807.857009  139931 bfc_allocator.cc:1105] InUse at 70b477500 of size 256 next 20
I0000 00:00:1779305807.857010  139931 bfc_allocator.cc:1105] InUse at 70b477600 of size 256 next 81
I0000 00:00:1779305807.857010  139931 bfc_allocator.cc:1105] InUse at 70b477700 of size 256 next 104
I0000 00:00:1779305807.857011  139931 bfc_allocator.cc:1105] InUse at 70b477800 of size 256 next 103
I0000 00:00:1779305807.857012  139931 bfc_allocator.cc:1105] InUse at 70b477900 of size 256 next 97
I0000 00:00:1779305807.857012  139931 bfc_allocator.cc:1105] InUse at 70b477a00 of size 256 next 98
I0000 00:00:1779305807.857013  139931 bfc_allocator.cc:1105] InUse at 70b477b00 of size 256 next 83
I0000 00:00:1779305807.857014  139931 bfc_allocator.cc:1105] InUse at 70b477c00 of size 256 next 80
I0000 00:00:1779305807.857015  139931 bfc_allocator.cc:1105] InUse at 70b477d00 of size 256 next 85
I0000 00:00:1779305807.857015  139931 bfc_allocator.cc:1105] InUse at 70b477e00 of size 256 next 135
I0000 00:00:1779305807.857016  139931 bfc_allocator.cc:1105] InUse at 70b477f00 of size 256 next 90
I0000 00:00:1779305807.857017  139931 bfc_allocator.cc:1105] InUse at 70b478000 of size 256 next 127
I0000 00:00:1779305807.857018  139931 bfc_allocator.cc:1105] InUse at 70b478100 of size 256 next 24
I0000 00:00:1779305807.857018  139931 bfc_allocator.cc:1105] InUse at 70b478200 of size 256 next 129
I0000 00:00:1779305807.857019  139931 bfc_allocator.cc:1105] InUse at 70b478300 of size 256 next 18
I0000 00:00:1779305807.857020  139931 bfc_allocator.cc:1105] Free  at 70b478400 of size 512 next 117
I0000 00:00:1779305807.857020  139931 bfc_allocator.cc:1105] InUse at 70b478600 of size 256 next 84
I0000 00:00:1779305807.857021  139931 bfc_allocator.cc:1105] InUse at 70b478700 of size 256 next 158
I0000 00:00:1779305807.857022  139931 bfc_allocator.cc:1105] InUse at 70b478800 of size 256 next 157
I0000 00:00:1779305807.857023  139931 bfc_allocator.cc:1105] InUse at 70b478900 of size 256 next 76
I0000 00:00:1779305807.857023  139931 bfc_allocator.cc:1105] InUse at 70b478a00 of size 256 next 74
I0000 00:00:1779305807.857024  139931 bfc_allocator.cc:1105] InUse at 70b478b00 of size 256 next 114
I0000 00:00:1779305807.857025  139931 bfc_allocator.cc:1105] InUse at 70b478c00 of size 256 next 96
I0000 00:00:1779305807.857025  139931 bfc_allocator.cc:1105] InUse at 70b478d00 of size 256 next 95
I0000 00:00:1779305807.857026  139931 bfc_allocator.cc:1105] InUse at 70b478e00 of size 256 next 107
I0000 00:00:1779305807.857027  139931 bfc_allocator.cc:1105] InUse at 70b478f00 of size 256 next 110
I0000 00:00:1779305807.857028  139931 bfc_allocator.cc:1105] InUse at 70b479000 of size 256 next 99
I0000 00:00:1779305807.857028  139931 bfc_allocator.cc:1105] InUse at 70b479100 of size 256 next 106
I0000 00:00:1779305807.857029  139931 bfc_allocator.cc:1105] InUse at 70b479200 of size 256 next 65
I0000 00:00:1779305807.857030  139931 bfc_allocator.cc:1105] InUse at 70b479300 of size 256 next 42
I0000 00:00:1779305807.857030  139931 bfc_allocator.cc:1105] InUse at 70b479400 of size 256 next 26
I0000 00:00:1779305807.857031  139931 bfc_allocator.cc:1105] InUse at 70b479500 of size 256 next 62
I0000 00:00:1779305807.857032  139931 bfc_allocator.cc:1105] InUse at 70b479600 of size 256 next 63
I0000 00:00:1779305807.857033  139931 bfc_allocator.cc:1105] InUse at 70b479700 of size 256 next 69
I0000 00:00:1779305807.857033  139931 bfc_allocator.cc:1105] InUse at 70b479800 of size 256 next 60
I0000 00:00:1779305807.857034  139931 bfc_allocator.cc:1105] InUse at 70b479900 of size 256 next 68
I0000 00:00:1779305807.857035  139931 bfc_allocator.cc:1105] InUse at 70b479a00 of size 256 next 67
I0000 00:00:1779305807.857036  139931 bfc_allocator.cc:1105] InUse at 70b479b00 of size 256 next 41
I0000 00:00:1779305807.857037  139931 bfc_allocator.cc:1105] InUse at 70b479c00 of size 256 next 75
I0000 00:00:1779305807.857037  139931 bfc_allocator.cc:1105] InUse at 70b479d00 of size 256 next 105
I0000 00:00:1779305807.857038  139931 bfc_allocator.cc:1105] InUse at 70b479e00 of size 256 next 45
I0000 00:00:1779305807.857039  139931 bfc_allocator.cc:1105] InUse at 70b479f00 of size 256 next 44
I0000 00:00:1779305807.857040  139931 bfc_allocator.cc:1105] InUse at 70b47a000 of size 256 next 120
I0000 00:00:1779305807.857040  139931 bfc_allocator.cc:1105] InUse at 70b47a100 of size 256 next 40
I0000 00:00:1779305807.857041  139931 bfc_allocator.cc:1105] InUse at 70b47a200 of size 256 next 64
I0000 00:00:1779305807.857042  139931 bfc_allocator.cc:1105] InUse at 70b47a300 of size 1487360 next 46
I0000 00:00:1779305807.857043  139931 bfc_allocator.cc:1105] Free  at 70b5e5500 of size 8000000 next 126
I0000 00:00:1779305807.857043  139931 bfc_allocator.cc:1105] InUse at 70bd86700 of size 8000000 next 148
I0000 00:00:1779305807.857044  139931 bfc_allocator.cc:1105] InUse at 70c527900 of size 131072 next 130
I0000 00:00:1779305807.857045  139931 bfc_allocator.cc:1105] InUse at 70c547900 of size 256000 next 78
I0000 00:00:1779305807.857046  139931 bfc_allocator.cc:1105] InUse at 70c586100 of size 256000 next 37
I0000 00:00:1779305807.857047  139931 bfc_allocator.cc:1105] InUse at 70c5c4900 of size 8000000 next 167
I0000 00:00:1779305807.857047  139931 bfc_allocator.cc:1105] InUse at 70cd65b00 of size 10178304 next 160
I0000 00:00:1779305807.857048  139931 bfc_allocator.cc:1105] InUse at 70d71aa00 of size 256 next 132
I0000 00:00:1779305807.857049  139931 bfc_allocator.cc:1105] InUse at 70d71ab00 of size 256 next 144
I0000 00:00:1779305807.857050  139931 bfc_allocator.cc:1105] InUse at 70d71ac00 of size 256 next 165
I0000 00:00:1779305807.857050  139931 bfc_allocator.cc:1105] Free  at 70d71ad00 of size 101376 next 39
I0000 00:00:1779305807.857051  139931 bfc_allocator.cc:1105] InUse at 70d733900 of size 256 next 82
I0000 00:00:1779305807.857052  139931 bfc_allocator.cc:1105] InUse at 70d733a00 of size 256 next 136
I0000 00:00:1779305807.857052  139931 bfc_allocator.cc:1105] InUse at 70d733b00 of size 256 next 112
I0000 00:00:1779305807.857053  139931 bfc_allocator.cc:1105] InUse at 70d733c00 of size 256 next 49
I0000 00:00:1779305807.857054  139931 bfc_allocator.cc:1105] InUse at 70d733d00 of size 256 next 150
I0000 00:00:1779305807.857055  139931 bfc_allocator.cc:1105] InUse at 70d733e00 of size 256 next 133
I0000 00:00:1779305807.857055  139931 bfc_allocator.cc:1105] InUse at 70d733f00 of size 256 next 16
I0000 00:00:1779305807.857056  139931 bfc_allocator.cc:1105] InUse at 70d734000 of size 256 next 57
I0000 00:00:1779305807.857057  139931 bfc_allocator.cc:1105] InUse at 70d734100 of size 256 next 86
I0000 00:00:1779305807.857057  139931 bfc_allocator.cc:1105] InUse at 70d734200 of size 256 next 115
I0000 00:00:1779305807.857058  139931 bfc_allocator.cc:1105] InUse at 70d734300 of size 256 next 59
I0000 00:00:1779305807.857059  139931 bfc_allocator.cc:1105] InUse at 70d734400 of size 256 next 146
I0000 00:00:1779305807.857060  139931 bfc_allocator.cc:1105] InUse at 70d734500 of size 256 next 140
I0000 00:00:1779305807.857060  139931 bfc_allocator.cc:1105] InUse at 70d734600 of size 256 next 138
I0000 00:00:1779305807.857061  139931 bfc_allocator.cc:1105] InUse at 70d734700 of size 512 next 72
I0000 00:00:1779305807.857062  139931 bfc_allocator.cc:1105] InUse at 70d734900 of size 512 next 141
I0000 00:00:1779305807.857063  139931 bfc_allocator.cc:1105] InUse at 70d734b00 of size 256 next 79
I0000 00:00:1779305807.857063  139931 bfc_allocator.cc:1105] InUse at 70d734c00 of size 256 next 54
I0000 00:00:1779305807.857064  139931 bfc_allocator.cc:1105] InUse at 70d734d00 of size 256 next 172
I0000 00:00:1779305807.857065  139931 bfc_allocator.cc:1105] InUse at 70d734e00 of size 256 next 145
I0000 00:00:1779305807.857066  139931 bfc_allocator.cc:1105] InUse at 70d734f00 of size 256 next 108
I0000 00:00:1779305807.857067  139931 bfc_allocator.cc:1105] InUse at 70d735000 of size 256 next 71
I0000 00:00:1779305807.857067  139931 bfc_allocator.cc:1105] InUse at 70d735100 of size 256 next 101
I0000 00:00:1779305807.857068  139931 bfc_allocator.cc:1105] InUse at 70d735200 of size 256 next 122
I0000 00:00:1779305807.857069  139931 bfc_allocator.cc:1105] InUse at 70d735300 of size 256 next 155
I0000 00:00:1779305807.857070  139931 bfc_allocator.cc:1105] InUse at 70d735400 of size 256 next 116
I0000 00:00:1779305807.857070  139931 bfc_allocator.cc:1105] InUse at 70d735500 of size 768 next 109
I0000 00:00:1779305807.857071  139931 bfc_allocator.cc:1105] InUse at 70d735800 of size 256 next 123
I0000 00:00:1779305807.857072  139931 bfc_allocator.cc:1105] InUse at 70d735900 of size 256 next 121
I0000 00:00:1779305807.857073  139931 bfc_allocator.cc:1105] InUse at 70d735a00 of size 256 next 173
I0000 00:00:1779305807.857073  139931 bfc_allocator.cc:1105] InUse at 70d735b00 of size 256 next 48
I0000 00:00:1779305807.857074  139931 bfc_allocator.cc:1105] InUse at 70d735c00 of size 256 next 137
I0000 00:00:1779305807.857075  139931 bfc_allocator.cc:1105] InUse at 70d735d00 of size 256 next 125
I0000 00:00:1779305807.857075  139931 bfc_allocator.cc:1105] InUse at 70d735e00 of size 256 next 89
I0000 00:00:1779305807.857076  139931 bfc_allocator.cc:1105] InUse at 70d735f00 of size 256 next 131
I0000 00:00:1779305807.857077  139931 bfc_allocator.cc:1105] InUse at 70d736000 of size 256 next 152
I0000 00:00:1779305807.857078  139931 bfc_allocator.cc:1105] InUse at 70d736100 of size 256 next 143
I0000 00:00:1779305807.857078  139931 bfc_allocator.cc:1105] InUse at 70d736200 of size 256 next 119
I0000 00:00:1779305807.857079  139931 bfc_allocator.cc:1105] InUse at 70d736300 of size 256 next 43
I0000 00:00:1779305807.857080  139931 bfc_allocator.cc:1105] InUse at 70d736400 of size 256 next 47
I0000 00:00:1779305807.857080  139931 bfc_allocator.cc:1105] InUse at 70d736500 of size 256 next 55
I0000 00:00:1779305807.857082  139931 bfc_allocator.cc:1105] InUse at 70d736600 of size 165632 next 100
I0000 00:00:1779305807.857083  139931 bfc_allocator.cc:1105] Free  at 70d75ed00 of size 418048 next 118
I0000 00:00:1779305807.857083  139931 bfc_allocator.cc:1105] InUse at 70d7c4e00 of size 256000 next 153
I0000 00:00:1779305807.857084  139931 bfc_allocator.cc:1105] InUse at 70d803600 of size 478208 next 149
I0000 00:00:1779305807.857085  139931 bfc_allocator.cc:1105] InUse at 70d878200 of size 256 next 151
I0000 00:00:1779305807.857086  139931 bfc_allocator.cc:1105] InUse at 70d878300 of size 256 next 177

64/64 ━━━━━━━━━━━━━━━━━━━━ 42s 259ms/step - accuracy: 0.4104 - loss: 2.4052 - val_accuracy: 0.5217 - val_loss: 1.8128
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5583 - loss: 1.7262 - val_accuracy: 0.6062 - val_loss: 1.5588
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6147 - loss: 1.4882 - val_accuracy: 0.6440 - val_loss: 1.4652
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6731 - loss: 1.2907 - val_accuracy: 0.6518 - val_loss: 1.3991
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7108 - loss: 1.1253 - val_accuracy: 0.6719 - val_loss: 1.3762
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7465 - loss: 0.9815 - val_accuracy: 0.6808 - val_loss: 1.3904
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7792 - loss: 0.8534 - val_accuracy: 0.6719 - val_loss: 1.4735
Epoch 7: early stopping
Restoring model weights from the end of the best epoch: 5.

I0000 00:00:1779305813.383369  139929 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/baseline_random_clf_baseline_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/baseline_random_clf_baseline_confusion.png
  test_acc=0.6754  macro_f1=0.1114  coverage=0.0%

--- Reuters frozen | run_id=cbow_30k_win2_emb100_ep5_vocab30000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779305817.632178  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26534504__.29

56/64 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3658 - loss: 2.7644

I0000 00:00:1779305819.512007  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26534504__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.4410 - loss: 2.3946 - val_accuracy: 0.4983 - val_loss: 1.9721
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5241 - loss: 1.9143 - val_accuracy: 0.5595 - val_loss: 1.7711
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5669 - loss: 1.7458 - val_accuracy: 0.5695 - val_loss: 1.7073
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5869 - loss: 1.6599 - val_accuracy: 0.5840 - val_loss: 1.6674
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6034 - loss: 1.5881 - val_accuracy: 0.6151 - val_loss: 1.6014
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6259 - loss: 1.5049 - val_accuracy: 0.6174 - val_loss: 1.5658
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6413 - loss: 1.4389 - val_accuracy: 0.6385 - val_loss: 1.5156
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6562 - loss: 1.3751 - val_accuracy: 0.6574 - val_loss: 1.4915
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6777 - loss: 1.2910 - val_accuracy: 0.6652 - val_loss: 1.4397
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6887 - loss: 1.2334 - val_accuracy: 0.6641 - val_loss: 1.4376
Restoring model weights from the end of the best epoch: 10.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_clf_frozen_confusion.png
  test_acc=0.6509  macro_f1=0.1002  coverage=58.9%

--- Reuters finetune | run_id=cbow_30k_win2_emb100_ep5_vocab30000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779305828.788219  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26541555__.31

62/64 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3579 - loss: 2.8425

I0000 00:00:1779305831.030199  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26541555__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.4497 - loss: 2.4078 - val_accuracy: 0.5150 - val_loss: 1.8942
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5447 - loss: 1.8254 - val_accuracy: 0.5840 - val_loss: 1.6855
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5977 - loss: 1.6031 - val_accuracy: 0.6296 - val_loss: 1.5541
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6542 - loss: 1.4303 - val_accuracy: 0.6741 - val_loss: 1.4401
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6983 - loss: 1.2535 - val_accuracy: 0.6919 - val_loss: 1.3271
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7323 - loss: 1.0721 - val_accuracy: 0.7008 - val_loss: 1.2697
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7594 - loss: 0.9323 - val_accuracy: 0.7186 - val_loss: 1.2842
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7803 - loss: 0.8365 - val_accuracy: 0.7264 - val_loss: 1.2847
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 6.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb100_ep5_vocab30000_clf_finetune_confusion.png
  test_acc=0.6959  macro_f1=0.1170  coverage=58.9%

--- Reuters frozen | run_id=cbow_30k_win5_emb100_ep5_vocab30000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779305840.467280  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26547808__.29

52/64 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3570 - loss: 2.8409

I0000 00:00:1779305842.478920  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26547808__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.4464 - loss: 2.3896 - val_accuracy: 0.5072 - val_loss: 1.9159
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5343 - loss: 1.8818 - val_accuracy: 0.5740 - val_loss: 1.7373
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5703 - loss: 1.7489 - val_accuracy: 0.5695 - val_loss: 1.7007
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5896 - loss: 1.6621 - val_accuracy: 0.5818 - val_loss: 1.6559
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6068 - loss: 1.5925 - val_accuracy: 0.6007 - val_loss: 1.6200
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6238 - loss: 1.5139 - val_accuracy: 0.6073 - val_loss: 1.5772
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6417 - loss: 1.4453 - val_accuracy: 0.6240 - val_loss: 1.5475
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6572 - loss: 1.3651 - val_accuracy: 0.6296 - val_loss: 1.5304
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6749 - loss: 1.3071 - val_accuracy: 0.6429 - val_loss: 1.4919
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6922 - loss: 1.2459 - val_accuracy: 0.6485 - val_loss: 1.4853
Restoring model weights from the end of the best epoch: 10.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_clf_frozen_confusion.png
  test_acc=0.6256  macro_f1=0.0860  coverage=58.9%

--- Reuters finetune | run_id=cbow_30k_win5_emb100_ep5_vocab30000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779305851.393430  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26554859__.31

60/64 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3782 - loss: 2.7535

I0000 00:00:1779305853.375164  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26554859__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - accuracy: 0.4585 - loss: 2.3385 - val_accuracy: 0.5250 - val_loss: 1.8513
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5590 - loss: 1.7948 - val_accuracy: 0.5851 - val_loss: 1.6692
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6046 - loss: 1.5919 - val_accuracy: 0.6229 - val_loss: 1.5343
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6506 - loss: 1.4106 - val_accuracy: 0.6652 - val_loss: 1.3824
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6931 - loss: 1.2283 - val_accuracy: 0.6908 - val_loss: 1.2774
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7260 - loss: 1.0671 - val_accuracy: 0.7141 - val_loss: 1.2279
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7559 - loss: 0.9387 - val_accuracy: 0.7297 - val_loss: 1.2270
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7828 - loss: 0.8257 - val_accuracy: 0.7341 - val_loss: 1.2018
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8056 - loss: 0.7330 - val_accuracy: 0.7442 - val_loss: 1.1599
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8287 - loss: 0.6483 - val_accuracy: 0.7542 - val_loss: 1.2111
Restoring model weights from the end of the best epoch: 9.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win5_emb100_ep5_vocab30000_clf_finetune_confusion.png
  test_acc=0.7489  macro_f1=0.2320  coverage=58.9%

--- Reuters frozen | run_id=cbow_30k_win2_emb300_ep5_vocab30000 | emb_dim=300 ---
Epoch 1/10

I0000 00:00:1779305864.715670  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26561802__.29
W0000 00:00:1779305864.755915  164751 hlo_rematerialization.cc:3204] Can't reduce memory use below 9.08GiB (9750085617 bytes) by rematerialization; only reduced to 37.81GiB (40597174304 bytes), down from 37.81GiB (40597174304 bytes) originally
W0000 00:00:1779305875.096474  139932 bfc_allocator.cc:502] Allocator (GPU_0_bfc) ran out of memory trying to allocate 37.79GiB (rounded to 40580659712)requested by op
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
I0000 00:00:1779305875.096688  139932 bfc_allocator.cc:1049] BFCAllocator dump for GPU_0_bfc
I0000 00:00:1779305875.096700  139932 bfc_allocator.cc:1056] Bin (256): 	Total Chunks: 215, Chunks in use: 215. 53.8KiB allocated for chunks. 53.8KiB in use in bin. 2.2KiB client-requested in use in bin.
I0000 00:00:1779305875.096712  139932 bfc_allocator.cc:1056] Bin (512): 	Total Chunks: 19, Chunks in use: 19. 9.8KiB allocated for chunks. 9.8KiB in use in bin. 9.5KiB client-requested in use in bin.
I0000 00:00:1779305875.096719  139932 bfc_allocator.cc:1056] Bin (1024): 	Total Chunks: 2, Chunks in use: 1. 3.0KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
I0000 00:00:1779305875.096725  139932 bfc_allocator.cc:1056] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096732  139932 bfc_allocator.cc:1056] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096737  139932 bfc_allocator.cc:1056] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096742  139932 bfc_allocator.cc:1056] Bin (16384): 	Total Chunks: 9, Chunks in use: 9. 207.0KiB allocated for chunks. 207.0KiB in use in bin. 207.0KiB client-requested in use in bin.
I0000 00:00:1779305875.096748  139932 bfc_allocator.cc:1056] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096753  139932 bfc_allocator.cc:1056] Bin (65536): 	Total Chunks: 8, Chunks in use: 8. 601.8KiB allocated for chunks. 601.8KiB in use in bin. 512.0KiB client-requested in use in bin.
I0000 00:00:1779305875.096759  139932 bfc_allocator.cc:1056] Bin (131072): 	Total Chunks: 10, Chunks in use: 9. 2.20MiB allocated for chunks. 2.06MiB in use in bin. 2.06MiB client-requested in use in bin.
I0000 00:00:1779305875.096766  139932 bfc_allocator.cc:1056] Bin (262144): 	Total Chunks: 7, Chunks in use: 7. 2.33MiB allocated for chunks. 2.33MiB in use in bin. 2.19MiB client-requested in use in bin.
I0000 00:00:1779305875.096772  139932 bfc_allocator.cc:1056] Bin (524288): 	Total Chunks: 3, Chunks in use: 3. 2.02MiB allocated for chunks. 2.02MiB in use in bin. 1.78MiB client-requested in use in bin.
I0000 00:00:1779305875.096777  139932 bfc_allocator.cc:1056] Bin (1048576): 	Total Chunks: 1, Chunks in use: 1. 1.54MiB allocated for chunks. 1.54MiB in use in bin. 1.42MiB client-requested in use in bin.
I0000 00:00:1779305875.096783  139932 bfc_allocator.cc:1056] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096788  139932 bfc_allocator.cc:1056] Bin (4194304): 	Total Chunks: 2, Chunks in use: 1. 14.19MiB allocated for chunks. 7.63MiB in use in bin. 7.63MiB client-requested in use in bin.
I0000 00:00:1779305875.096794  139932 bfc_allocator.cc:1056] Bin (8388608): 	Total Chunks: 5, Chunks in use: 4. 68.92MiB allocated for chunks. 59.50MiB in use in bin. 54.88MiB client-requested in use in bin.
I0000 00:00:1779305875.096799  139932 bfc_allocator.cc:1056] Bin (16777216): 	Total Chunks: 4, Chunks in use: 4. 83.67MiB allocated for chunks. 83.67MiB in use in bin. 71.37MiB client-requested in use in bin.
I0000 00:00:1779305875.096805  139932 bfc_allocator.cc:1056] Bin (33554432): 	Total Chunks: 1, Chunks in use: 1. 53.50MiB allocated for chunks. 53.50MiB in use in bin. 53.50MiB client-requested in use in bin.
I0000 00:00:1779305875.096811  139932 bfc_allocator.cc:1056] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096819  139932 bfc_allocator.cc:1056] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096825  139932 bfc_allocator.cc:1056] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 9.06GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305875.096830  139932 bfc_allocator.cc:1072] Bin for 37.79GiB was 256.00MiB, Chunk State:
I0000 00:00:1779305875.096836  139932 bfc_allocator.cc:1078]   Size: 9.06GiB | Requested Size: 91.71MiB | in_use: 0 | bin_num: 20, prev:   Size: 15.75MiB | Requested Size: 15.75MiB | in_use: 1 | bin_num: -1
I0000 00:00:1779305875.096847  139932 bfc_allocator.cc:1085] Next region of size 9970909184
I0000 00:00:1779305875.096854  139932 bfc_allocator.cc:1105] InUse at 70b400000 of size 1280 next 1
I0000 00:00:1779305875.096859  139932 bfc_allocator.cc:1105] InUse at 70b400500 of size 256 next 2
I0000 00:00:1779305875.096862  139932 bfc_allocator.cc:1105] InUse at 70b400600 of size 256 next 3
I0000 00:00:1779305875.096865  139932 bfc_allocator.cc:1105] InUse at 70b400700 of size 256 next 4
I0000 00:00:1779305875.096868  139932 bfc_allocator.cc:1105] InUse at 70b400800 of size 256 next 5
I0000 00:00:1779305875.096871  139932 bfc_allocator.cc:1105] InUse at 70b400900 of size 256 next 6
I0000 00:00:1779305875.096874  139932 bfc_allocator.cc:1105] InUse at 70b400a00 of size 240128 next 7
I0000 00:00:1779305875.096878  139932 bfc_allocator.cc:1105] InUse at 70b43b400 of size 23552 next 148
I0000 00:00:1779305875.096884  139932 bfc_allocator.cc:1105] InUse at 70b441000 of size 89344 next 28
I0000 00:00:1779305875.096887  139932 bfc_allocator.cc:1105] InUse at 70b456d00 of size 256 next 111
I0000 00:00:1779305875.096890  139932 bfc_allocator.cc:1105] InUse at 70b456e00 of size 256 next 93
I0000 00:00:1779305875.096893  139932 bfc_allocator.cc:1105] InUse at 70b456f00 of size 256 next 92
I0000 00:00:1779305875.096896  139932 bfc_allocator.cc:1105] InUse at 70b457000 of size 256 next 102
I0000 00:00:1779305875.096899  139932 bfc_allocator.cc:1105] InUse at 70b457100 of size 256 next 162
I0000 00:00:1779305875.096901  139932 bfc_allocator.cc:1105] InUse at 70b457200 of size 256 next 19
I0000 00:00:1779305875.096904  139932 bfc_allocator.cc:1105] InUse at 70b457300 of size 256 next 15
I0000 00:00:1779305875.096908  139932 bfc_allocator.cc:1105] InUse at 70b457400 of size 256 next 77
I0000 00:00:1779305875.096918  139932 bfc_allocator.cc:1105] InUse at 70b457500 of size 256 next 128
I0000 00:00:1779305875.096922  139932 bfc_allocator.cc:1105] InUse at 70b457600 of size 256 next 171
I0000 00:00:1779305875.096927  139932 bfc_allocator.cc:1105] InUse at 70b457700 of size 256 next 91
I0000 00:00:1779305875.096933  139932 bfc_allocator.cc:1105] InUse at 70b457800 of size 23552 next 169
I0000 00:00:1779305875.096940  139932 bfc_allocator.cc:1105] InUse at 70b45d400 of size 256 next 178
I0000 00:00:1779305875.096944  139932 bfc_allocator.cc:1105] InUse at 70b45d500 of size 256 next 88
I0000 00:00:1779305875.096947  139932 bfc_allocator.cc:1105] InUse at 70b45d600 of size 256 next 134
I0000 00:00:1779305875.096950  139932 bfc_allocator.cc:1105] InUse at 70b45d700 of size 256 next 179
I0000 00:00:1779305875.096953  139932 bfc_allocator.cc:1105] InUse at 70b45d800 of size 256 next 180
I0000 00:00:1779305875.096955  139932 bfc_allocator.cc:1105] InUse at 70b45d900 of size 256 next 163
I0000 00:00:1779305875.096958  139932 bfc_allocator.cc:1105] InUse at 70b45da00 of size 256 next 182
I0000 00:00:1779305875.096961  139932 bfc_allocator.cc:1105] InUse at 70b45db00 of size 256 next 156
I0000 00:00:1779305875.096964  139932 bfc_allocator.cc:1105] InUse at 70b45dc00 of size 256 next 185
I0000 00:00:1779305875.096967  139932 bfc_allocator.cc:1105] InUse at 70b45dd00 of size 256 next 100
I0000 00:00:1779305875.096971  139932 bfc_allocator.cc:1105] InUse at 70b45de00 of size 256 next 181
I0000 00:00:1779305875.096974  139932 bfc_allocator.cc:1105] InUse at 70b45df00 of size 256 next 190
I0000 00:00:1779305875.096977  139932 bfc_allocator.cc:1105] InUse at 70b45e000 of size 256 next 189
I0000 00:00:1779305875.096980  139932 bfc_allocator.cc:1105] InUse at 70b45e100 of size 256 next 118
I0000 00:00:1779305875.096983  139932 bfc_allocator.cc:1105] InUse at 70b45e200 of size 256 next 187
I0000 00:00:1779305875.096986  139932 bfc_allocator.cc:1105] InUse at 70b45e300 of size 256 next 194
I0000 00:00:1779305875.096989  139932 bfc_allocator.cc:1105] InUse at 70b45e400 of size 256 next 166
I0000 00:00:1779305875.096992  139932 bfc_allocator.cc:1105] InUse at 70b45e500 of size 256 next 195
I0000 00:00:1779305875.096995  139932 bfc_allocator.cc:1105] InUse at 70b45e600 of size 256 next 191
I0000 00:00:1779305875.096997  139932 bfc_allocator.cc:1105] InUse at 70b45e700 of size 256 next 200
I0000 00:00:1779305875.097000  139932 bfc_allocator.cc:1105] InUse at 70b45e800 of size 256 next 183
I0000 00:00:1779305875.097004  139932 bfc_allocator.cc:1105] InUse at 70b45e900 of size 512 next 142
I0000 00:00:1779305875.097007  139932 bfc_allocator.cc:1105] InUse at 70b45eb00 of size 256 next 188
I0000 00:00:1779305875.097010  139932 bfc_allocator.cc:1105] InUse at 70b45ec00 of size 256 next 228
I0000 00:00:1779305875.097013  139932 bfc_allocator.cc:1105] InUse at 70b45ed00 of size 256 next 253
I0000 00:00:1779305875.097016  139932 bfc_allocator.cc:1105] InUse at 70b45ee00 of size 256 next 201
I0000 00:00:1779305875.097018  139932 bfc_allocator.cc:1105] InUse at 70b45ef00 of size 256 next 259
I0000 00:00:1779305875.097021  139932 bfc_allocator.cc:1105] InUse at 70b45f000 of size 256 next 258
I0000 00:00:1779305875.097024  139932 bfc_allocator.cc:1105] InUse at 70b45f100 of size 512 next 206
I0000 00:00:1779305875.097027  139932 bfc_allocator.cc:1105] InUse at 70b45f300 of size 512 next 199
I0000 00:00:1779305875.097030  139932 bfc_allocator.cc:1105] InUse at 70b45f500 of size 256 next 223
I0000 00:00:1779305875.097033  139932 bfc_allocator.cc:1105] InUse at 70b45f600 of size 512 next 209
I0000 00:00:1779305875.097036  139932 bfc_allocator.cc:1105] InUse at 70b45f800 of size 512 next 192
I0000 00:00:1779305875.097039  139932 bfc_allocator.cc:1105] InUse at 70b45fa00 of size 256 next 237
I0000 00:00:1779305875.097042  139932 bfc_allocator.cc:1105] InUse at 70b45fb00 of size 256 next 198
I0000 00:00:1779305875.097045  139932 bfc_allocator.cc:1105] InUse at 70b45fc00 of size 256 next 208
I0000 00:00:1779305875.097048  139932 bfc_allocator.cc:1105] InUse at 70b45fd00 of size 256 next 232
I0000 00:00:1779305875.097050  139932 bfc_allocator.cc:1105] InUse at 70b45fe00 of size 256 next 248
I0000 00:00:1779305875.097053  139932 bfc_allocator.cc:1105] InUse at 70b45ff00 of size 256 next 260
I0000 00:00:1779305875.097056  139932 bfc_allocator.cc:1105] InUse at 70b460000 of size 256 next 174
I0000 00:00:1779305875.097059  139932 bfc_allocator.cc:1105] InUse at 70b460100 of size 256 next 225
I0000 00:00:1779305875.097062  139932 bfc_allocator.cc:1105] InUse at 70b460200 of size 256 next 207
I0000 00:00:1779305875.097065  139932 bfc_allocator.cc:1105] InUse at 70b460300 of size 256 next 243
I0000 00:00:1779305875.097067  139932 bfc_allocator.cc:1105] InUse at 70b460400 of size 256 next 219
I0000 00:00:1779305875.097070  139932 bfc_allocator.cc:1105] InUse at 70b460500 of size 256 next 224
I0000 00:00:1779305875.097073  139932 bfc_allocator.cc:1105] InUse at 70b460600 of size 256 next 221
I0000 00:00:1779305875.097076  139932 bfc_allocator.cc:1105] InUse at 70b460700 of size 256 next 229
I0000 00:00:1779305875.097079  139932 bfc_allocator.cc:1105] InUse at 70b460800 of size 256 next 227
I0000 00:00:1779305875.097082  139932 bfc_allocator.cc:1105] InUse at 70b460900 of size 256 next 226
I0000 00:00:1779305875.097085  139932 bfc_allocator.cc:1105] InUse at 70b460a00 of size 256 next 234
I0000 00:00:1779305875.097089  139932 bfc_allocator.cc:1105] InUse at 70b460b00 of size 256 next 244
I0000 00:00:1779305875.097092  139932 bfc_allocator.cc:1105] InUse at 70b460c00 of size 256 next 247
I0000 00:00:1779305875.097095  139932 bfc_allocator.cc:1105] InUse at 70b460d00 of size 256 next 246
I0000 00:00:1779305875.097097  139932 bfc_allocator.cc:1105] InUse at 70b460e00 of size 256 next 250
I0000 00:00:1779305875.097100  139932 bfc_allocator.cc:1105] InUse at 70b460f00 of size 256 next 193
I0000 00:00:1779305875.097103  139932 bfc_allocator.cc:1105] InUse at 70b461000 of size 256 next 256
I0000 00:00:1779305875.097106  139932 bfc_allocator.cc:1105] InUse at 70b461100 of size 512 next 249
I0000 00:00:1779305875.097109  139932 bfc_allocator.cc:1105] InUse at 70b461300 of size 256 next 289
I0000 00:00:1779305875.097112  139932 bfc_allocator.cc:1105] InUse at 70b461400 of size 256 next 261
I0000 00:00:1779305875.097115  139932 bfc_allocator.cc:1105] InUse at 70b461500 of size 256 next 252
I0000 00:00:1779305875.097118  139932 bfc_allocator.cc:1105] InUse at 70b461600 of size 512 next 257
I0000 00:00:1779305875.097120  139932 bfc_allocator.cc:1105] InUse at 70b461800 of size 256 next 290
I0000 00:00:1779305875.097124  139932 bfc_allocator.cc:1105] Free  at 70b461900 of size 1792 next 220
I0000 00:00:1779305875.097127  139932 bfc_allocator.cc:1105] InUse at 70b462000 of size 256 next 184
I0000 00:00:1779305875.097130  139932 bfc_allocator.cc:1105] InUse at 70b462100 of size 256 next 236
I0000 00:00:1779305875.097132  139932 bfc_allocator.cc:1105] InUse at 70b462200 of size 256 next 231
I0000 00:00:1779305875.097135  139932 bfc_allocator.cc:1105] InUse at 70b462300 of size 256 next 241
I0000 00:00:1779305875.097138  139932 bfc_allocator.cc:1105] InUse at 70b462400 of size 256 next 222
I0000 00:00:1779305875.097141  139932 bfc_allocator.cc:1105] InUse at 70b462500 of size 256 next 217
I0000 00:00:1779305875.097144  139932 bfc_allocator.cc:1105] InUse at 70b462600 of size 256 next 216
I0000 00:00:1779305875.097147  139932 bfc_allocator.cc:1105] InUse at 70b462700 of size 256 next 210
I0000 00:00:1779305875.097150  139932 bfc_allocator.cc:1105] InUse at 70b462800 of size 256 next 215
I0000 00:00:1779305875.097153  139932 bfc_allocator.cc:1105] InUse at 70b462900 of size 512 next 242
I0000 00:00:1779305875.097155  139932 bfc_allocator.cc:1105] InUse at 70b462b00 of size 512 next 203
I0000 00:00:1779305875.097158  139932 bfc_allocator.cc:1105] InUse at 70b462d00 of size 512 next 213
I0000 00:00:1779305875.097164  139932 bfc_allocator.cc:1105] InUse at 70b462f00 of size 768 next 58
I0000 00:00:1779305875.097167  139932 bfc_allocator.cc:1105] InUse at 70b463200 of size 256 next 154
I0000 00:00:1779305875.097170  139932 bfc_allocator.cc:1105] InUse at 70b463300 of size 256 next 52
I0000 00:00:1779305875.097173  139932 bfc_allocator.cc:1105] InUse at 70b463400 of size 512 next 53
I0000 00:00:1779305875.097176  139932 bfc_allocator.cc:1105] InUse at 70b463600 of size 512 next 51
I0000 00:00:1779305875.097179  139932 bfc_allocator.cc:1105] InUse at 70b463800 of size 512 next 167
I0000 00:00:1779305875.097181  139932 bfc_allocator.cc:1105] InUse at 70b463a00 of size 512 next 50
I0000 00:00:1779305875.097185  139932 bfc_allocator.cc:1105] InUse at 70b463c00 of size 74240 next 8
I0000 00:00:1779305875.097188  139932 bfc_allocator.cc:1105] InUse at 70b475e00 of size 256 next 9
I0000 00:00:1779305875.097191  139932 bfc_allocator.cc:1105] InUse at 70b475f00 of size 256 next 10
I0000 00:00:1779305875.097194  139932 bfc_allocator.cc:1105] InUse at 70b476000 of size 256 next 12
I0000 00:00:1779305875.097196  139932 bfc_allocator.cc:1105] InUse at 70b476100 of size 256 next 13
I0000 00:00:1779305875.097199  139932 bfc_allocator.cc:1105] InUse at 70b476200 of size 256 next 70
I0000 00:00:1779305875.097202  139932 bfc_allocator.cc:1105] InUse at 70b476300 of size 256 next 14
I0000 00:00:1779305875.097205  139932 bfc_allocator.cc:1105] InUse at 70b476400 of size 256 next 17
I0000 00:00:1779305875.097209  139932 bfc_allocator.cc:1105] InUse at 70b476500 of size 256 next 11
I0000 00:00:1779305875.097212  139932 bfc_allocator.cc:1105] InUse at 70b476600 of size 256 next 21
I0000 00:00:1779305875.097215  139932 bfc_allocator.cc:1105] InUse at 70b476700 of size 256 next 22
I0000 00:00:1779305875.097218  139932 bfc_allocator.cc:1105] InUse at 70b476800 of size 256 next 25
I0000 00:00:1779305875.097221  139932 bfc_allocator.cc:1105] InUse at 70b476900 of size 256 next 66
I0000 00:00:1779305875.097224  139932 bfc_allocator.cc:1105] InUse at 70b476a00 of size 256 next 27
I0000 00:00:1779305875.097226  139932 bfc_allocator.cc:1105] InUse at 70b476b00 of size 256 next 38
I0000 00:00:1779305875.097229  139932 bfc_allocator.cc:1105] InUse at 70b476c00 of size 256 next 29
I0000 00:00:1779305875.097232  139932 bfc_allocator.cc:1105] InUse at 70b476d00 of size 256 next 30
I0000 00:00:1779305875.097235  139932 bfc_allocator.cc:1105] InUse at 70b476e00 of size 256 next 31
I0000 00:00:1779305875.097238  139932 bfc_allocator.cc:1105] InUse at 70b476f00 of size 256 next 32
I0000 00:00:1779305875.097241  139932 bfc_allocator.cc:1105] InUse at 70b477000 of size 256 next 33
I0000 00:00:1779305875.097244  139932 bfc_allocator.cc:1105] InUse at 70b477100 of size 256 next 34
I0000 00:00:1779305875.097247  139932 bfc_allocator.cc:1105] InUse at 70b477200 of size 256 next 35
I0000 00:00:1779305875.097249  139932 bfc_allocator.cc:1105] InUse at 70b477300 of size 256 next 36
I0000 00:00:1779305875.097252  139932 bfc_allocator.cc:1105] InUse at 70b477400 of size 256 next 124
I0000 00:00:1779305875.097255  139932 bfc_allocator.cc:1105] InUse at 70b477500 of size 256 next 20
I0000 00:00:1779305875.097258  139932 bfc_allocator.cc:1105] InUse at 70b477600 of size 256 next 81
I0000 00:00:1779305875.097261  139932 bfc_allocator.cc:1105] InUse at 70b477700 of size 256 next 104
I0000 00:00:1779305875.097264  139932 bfc_allocator.cc:1105] InUse at 70b477800 of size 256 next 103
I0000 00:00:1779305875.097267  139932 bfc_allocator.cc:1105] InUse at 70b477900 of size 256 next 97
I0000 00:00:1779305875.097269  139932 bfc_allocator.cc:1105] InUse at 70b477a00 of size 256 next 98
I0000 00:00:1779305875.097272  139932 bfc_allocator.cc:1105] InUse at 70b477b00 of size 256 next 83
I0000 00:00:1779305875.097275  139932 bfc_allocator.cc:1105] InUse at 70b477c00 of size 256 next 80
I0000 00:00:1779305875.097278  139932 bfc_allocator.cc:1105] InUse at 70b477d00 of size 256 next 85
I0000 00:00:1779305875.097281  139932 bfc_allocator.cc:1105] InUse at 70b477e00 of size 256 next 135
I0000 00:00:1779305875.097284  139932 bfc_allocator.cc:1105] InUse at 70b477f00 of size 256 next 90
I0000 00:00:1779305875.097287  139932 bfc_allocator.cc:1105] InUse at 70b478000 of size 256 next 127
I0000 00:00:1779305875.097289  139932 bfc_allocator.cc:1105] InUse at 70b478100 of size 256 next 24
I0000 00:00:1779305875.097292  139932 bfc_allocator.cc:1105] InUse at 70b478200 of size 256 next 129
I0000 00:00:1779305875.097295  139932 bfc_allocator.cc:1105] InUse at 70b478300 of size 256 next 18
I0000 00:00:1779305875.097298  139932 bfc_allocator.cc:1105] InUse at 70b478400 of size 256 next 161
I0000 00:00:1779305875.097301  139932 bfc_allocator.cc:1105] InUse at 70b478500 of size 256 next 117

62/64 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3744 - loss: 2.7363

I0000 00:00:1779305887.763422  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26561802__.29
W0000 00:00:1779305887.796162  164956 hlo_rematerialization.cc:3204] Can't reduce memory use below 9.11GiB (9779510026 bytes) by rematerialization; only reduced to 18.90GiB (20293165088 bytes), down from 18.90GiB (20293165088 bytes) originally
W0000 00:00:1779305897.863533  139931 bfc_allocator.cc:502] Allocator (GPU_0_bfc) ran out of memory trying to allocate 18.90GiB (rounded to 20292397568)requested by op
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
I0000 00:00:1779305897.863942  139931 bfc_allocator.cc:1049] BFCAllocator dump for GPU_0_bfc
I0000 00:00:1779305897.863958  139931 bfc_allocator.cc:1056] Bin (256): 	Total Chunks: 225, Chunks in use: 224. 56.2KiB allocated for chunks. 56.0KiB in use in bin. 2.6KiB client-requested in use in bin.
I0000 00:00:1779305897.863972  139931 bfc_allocator.cc:1056] Bin (512): 	Total Chunks: 28, Chunks in use: 27. 14.8KiB allocated for chunks. 14.0KiB in use in bin. 13.5KiB client-requested in use in bin.
I0000 00:00:1779305897.863979  139931 bfc_allocator.cc:1056] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
I0000 00:00:1779305897.863987  139931 bfc_allocator.cc:1056] Bin (2048): 	Total Chunks: 1, Chunks in use: 1. 3.5KiB allocated for chunks. 3.5KiB in use in bin. 3.4KiB client-requested in use in bin.
I0000 00:00:1779305897.863993  139931 bfc_allocator.cc:1056] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864000  139931 bfc_allocator.cc:1056] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864006  139931 bfc_allocator.cc:1056] Bin (16384): 	Total Chunks: 10, Chunks in use: 10. 226.0KiB allocated for chunks. 226.0KiB in use in bin. 226.0KiB client-requested in use in bin.
I0000 00:00:1779305897.864109  139931 bfc_allocator.cc:1056] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864124  139931 bfc_allocator.cc:1056] Bin (65536): 	Total Chunks: 10, Chunks in use: 9. 715.5KiB allocated for chunks. 651.0KiB in use in bin. 576.0KiB client-requested in use in bin.
I0000 00:00:1779305897.864135  139931 bfc_allocator.cc:1056] Bin (131072): 	Total Chunks: 9, Chunks in use: 8. 2.08MiB allocated for chunks. 1.94MiB in use in bin. 1.94MiB client-requested in use in bin.
I0000 00:00:1779305897.864145  139931 bfc_allocator.cc:1056] Bin (262144): 	Total Chunks: 9, Chunks in use: 8. 2.98MiB allocated for chunks. 2.64MiB in use in bin. 2.50MiB client-requested in use in bin.
I0000 00:00:1779305897.864152  139931 bfc_allocator.cc:1056] Bin (524288): 	Total Chunks: 7, Chunks in use: 7. 4.95MiB allocated for chunks. 4.95MiB in use in bin. 4.71MiB client-requested in use in bin.
I0000 00:00:1779305897.864158  139931 bfc_allocator.cc:1056] Bin (1048576): 	Total Chunks: 1, Chunks in use: 1. 1.54MiB allocated for chunks. 1.54MiB in use in bin. 1.42MiB client-requested in use in bin.
I0000 00:00:1779305897.864164  139931 bfc_allocator.cc:1056] Bin (2097152): 	Total Chunks: 1, Chunks in use: 0. 2.95MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864171  139931 bfc_allocator.cc:1056] Bin (4194304): 	Total Chunks: 1, Chunks in use: 1. 7.63MiB allocated for chunks. 7.63MiB in use in bin. 7.63MiB client-requested in use in bin.
I0000 00:00:1779305897.864177  139931 bfc_allocator.cc:1056] Bin (8388608): 	Total Chunks: 5, Chunks in use: 4. 68.92MiB allocated for chunks. 59.50MiB in use in bin. 54.88MiB client-requested in use in bin.
I0000 00:00:1779305897.864209  139931 bfc_allocator.cc:1056] Bin (16777216): 	Total Chunks: 4, Chunks in use: 3. 83.67MiB allocated for chunks. 64.64MiB in use in bin. 62.79MiB client-requested in use in bin.
I0000 00:00:1779305897.864217  139931 bfc_allocator.cc:1056] Bin (33554432): 	Total Chunks: 1, Chunks in use: 0. 53.50MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864224  139931 bfc_allocator.cc:1056] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864235  139931 bfc_allocator.cc:1056] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864241  139931 bfc_allocator.cc:1056] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 9.06GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305897.864248  139931 bfc_allocator.cc:1072] Bin for 18.90GiB was 256.00MiB, Chunk State:
I0000 00:00:1779305897.864255  139931 bfc_allocator.cc:1078]   Size: 9.06GiB | Requested Size: 167.68MiB | in_use: 0 | bin_num: 20, prev:   Size: 15.75MiB | Requested Size: 15.75MiB | in_use: 1 | bin_num: -1
I0000 00:00:1779305897.864268  139931 bfc_allocator.cc:1085] Next region of size 9970909184
I0000 00:00:1779305897.864277  139931 bfc_allocator.cc:1105] InUse at 70b400000 of size 1280 next 1
I0000 00:00:1779305897.864281  139931 bfc_allocator.cc:1105] InUse at 70b400500 of size 256 next 2
I0000 00:00:1779305897.864285  139931 bfc_allocator.cc:1105] InUse at 70b400600 of size 256 next 3
I0000 00:00:1779305897.864288  139931 bfc_allocator.cc:1105] InUse at 70b400700 of size 256 next 4
I0000 00:00:1779305897.864291  139931 bfc_allocator.cc:1105] InUse at 70b400800 of size 256 next 5
I0000 00:00:1779305897.864295  139931 bfc_allocator.cc:1105] InUse at 70b400900 of size 256 next 6
I0000 00:00:1779305897.864298  139931 bfc_allocator.cc:1105] InUse at 70b400a00 of size 240128 next 7
I0000 00:00:1779305897.864303  139931 bfc_allocator.cc:1105] InUse at 70b43b400 of size 23552 next 148
I0000 00:00:1779305897.864307  139931 bfc_allocator.cc:1105] InUse at 70b441000 of size 89344 next 28
I0000 00:00:1779305897.864310  139931 bfc_allocator.cc:1105] InUse at 70b456d00 of size 256 next 111
I0000 00:00:1779305897.864313  139931 bfc_allocator.cc:1105] InUse at 70b456e00 of size 256 next 93
I0000 00:00:1779305897.864317  139931 bfc_allocator.cc:1105] InUse at 70b456f00 of size 256 next 92
I0000 00:00:1779305897.864320  139931 bfc_allocator.cc:1105] InUse at 70b457000 of size 256 next 102
I0000 00:00:1779305897.864323  139931 bfc_allocator.cc:1105] InUse at 70b457100 of size 256 next 162
I0000 00:00:1779305897.864326  139931 bfc_allocator.cc:1105] InUse at 70b457200 of size 256 next 19
I0000 00:00:1779305897.864329  139931 bfc_allocator.cc:1105] InUse at 70b457300 of size 256 next 15
I0000 00:00:1779305897.864333  139931 bfc_allocator.cc:1105] InUse at 70b457400 of size 256 next 77
I0000 00:00:1779305897.864336  139931 bfc_allocator.cc:1105] InUse at 70b457500 of size 256 next 128
I0000 00:00:1779305897.864339  139931 bfc_allocator.cc:1105] InUse at 70b457600 of size 256 next 171
I0000 00:00:1779305897.864342  139931 bfc_allocator.cc:1105] InUse at 70b457700 of size 256 next 91
I0000 00:00:1779305897.864345  139931 bfc_allocator.cc:1105] InUse at 70b457800 of size 23552 next 169
I0000 00:00:1779305897.864348  139931 bfc_allocator.cc:1105] InUse at 70b45d400 of size 256 next 178
I0000 00:00:1779305897.864352  139931 bfc_allocator.cc:1105] InUse at 70b45d500 of size 256 next 88
I0000 00:00:1779305897.864355  139931 bfc_allocator.cc:1105] InUse at 70b45d600 of size 256 next 134
I0000 00:00:1779305897.864358  139931 bfc_allocator.cc:1105] InUse at 70b45d700 of size 256 next 179
I0000 00:00:1779305897.864361  139931 bfc_allocator.cc:1105] InUse at 70b45d800 of size 256 next 180
I0000 00:00:1779305897.864364  139931 bfc_allocator.cc:1105] InUse at 70b45d900 of size 256 next 163
I0000 00:00:1779305897.864368  139931 bfc_allocator.cc:1105] InUse at 70b45da00 of size 256 next 182
I0000 00:00:1779305897.864371  139931 bfc_allocator.cc:1105] InUse at 70b45db00 of size 256 next 156
I0000 00:00:1779305897.864374  139931 bfc_allocator.cc:1105] InUse at 70b45dc00 of size 256 next 185
I0000 00:00:1779305897.864411  139931 bfc_allocator.cc:1105] InUse at 70b45dd00 of size 256 next 100
I0000 00:00:1779305897.864421  139931 bfc_allocator.cc:1105] InUse at 70b45de00 of size 256 next 181
I0000 00:00:1779305897.864425  139931 bfc_allocator.cc:1105] InUse at 70b45df00 of size 256 next 190
I0000 00:00:1779305897.864429  139931 bfc_allocator.cc:1105] InUse at 70b45e000 of size 256 next 189
I0000 00:00:1779305897.864432  139931 bfc_allocator.cc:1105] InUse at 70b45e100 of size 256 next 118
I0000 00:00:1779305897.864435  139931 bfc_allocator.cc:1105] InUse at 70b45e200 of size 256 next 187
I0000 00:00:1779305897.864438  139931 bfc_allocator.cc:1105] InUse at 70b45e300 of size 256 next 194
I0000 00:00:1779305897.864441  139931 bfc_allocator.cc:1105] InUse at 70b45e400 of size 256 next 166
I0000 00:00:1779305897.864444  139931 bfc_allocator.cc:1105] InUse at 70b45e500 of size 256 next 195
I0000 00:00:1779305897.864448  139931 bfc_allocator.cc:1105] InUse at 70b45e600 of size 256 next 191
I0000 00:00:1779305897.864451  139931 bfc_allocator.cc:1105] InUse at 70b45e700 of size 256 next 200
I0000 00:00:1779305897.864454  139931 bfc_allocator.cc:1105] InUse at 70b45e800 of size 256 next 183
I0000 00:00:1779305897.864463  139931 bfc_allocator.cc:1105] InUse at 70b45e900 of size 512 next 142
I0000 00:00:1779305897.864466  139931 bfc_allocator.cc:1105] InUse at 70b45eb00 of size 256 next 188
I0000 00:00:1779305897.864469  139931 bfc_allocator.cc:1105] InUse at 70b45ec00 of size 256 next 228
I0000 00:00:1779305897.864472  139931 bfc_allocator.cc:1105] InUse at 70b45ed00 of size 256 next 253
I0000 00:00:1779305897.864476  139931 bfc_allocator.cc:1105] InUse at 70b45ee00 of size 256 next 201
I0000 00:00:1779305897.864479  139931 bfc_allocator.cc:1105] InUse at 70b45ef00 of size 256 next 259
I0000 00:00:1779305897.864482  139931 bfc_allocator.cc:1105] InUse at 70b45f000 of size 256 next 258
I0000 00:00:1779305897.864485  139931 bfc_allocator.cc:1105] InUse at 70b45f100 of size 512 next 206
I0000 00:00:1779305897.864489  139931 bfc_allocator.cc:1105] InUse at 70b45f300 of size 512 next 199
I0000 00:00:1779305897.864492  139931 bfc_allocator.cc:1105] InUse at 70b45f500 of size 256 next 223
I0000 00:00:1779305897.864495  139931 bfc_allocator.cc:1105] InUse at 70b45f600 of size 512 next 209
I0000 00:00:1779305897.864498  139931 bfc_allocator.cc:1105] InUse at 70b45f800 of size 512 next 192
I0000 00:00:1779305897.864502  139931 bfc_allocator.cc:1105] InUse at 70b45fa00 of size 256 next 237
I0000 00:00:1779305897.864505  139931 bfc_allocator.cc:1105] InUse at 70b45fb00 of size 256 next 198
I0000 00:00:1779305897.864508  139931 bfc_allocator.cc:1105] InUse at 70b45fc00 of size 256 next 208
I0000 00:00:1779305897.864511  139931 bfc_allocator.cc:1105] InUse at 70b45fd00 of size 256 next 232
I0000 00:00:1779305897.864514  139931 bfc_allocator.cc:1105] InUse at 70b45fe00 of size 256 next 248
I0000 00:00:1779305897.864518  139931 bfc_allocator.cc:1105] InUse at 70b45ff00 of size 256 next 260
I0000 00:00:1779305897.864521  139931 bfc_allocator.cc:1105] InUse at 70b460000 of size 256 next 174
I0000 00:00:1779305897.864524  139931 bfc_allocator.cc:1105] InUse at 70b460100 of size 256 next 225
I0000 00:00:1779305897.864527  139931 bfc_allocator.cc:1105] InUse at 70b460200 of size 256 next 207
I0000 00:00:1779305897.864531  139931 bfc_allocator.cc:1105] InUse at 70b460300 of size 256 next 243
I0000 00:00:1779305897.864534  139931 bfc_allocator.cc:1105] InUse at 70b460400 of size 256 next 219
I0000 00:00:1779305897.864537  139931 bfc_allocator.cc:1105] InUse at 70b460500 of size 256 next 224
I0000 00:00:1779305897.864540  139931 bfc_allocator.cc:1105] InUse at 70b460600 of size 256 next 221
I0000 00:00:1779305897.864543  139931 bfc_allocator.cc:1105] InUse at 70b460700 of size 256 next 229
I0000 00:00:1779305897.864547  139931 bfc_allocator.cc:1105] InUse at 70b460800 of size 256 next 227
I0000 00:00:1779305897.864550  139931 bfc_allocator.cc:1105] InUse at 70b460900 of size 256 next 226
I0000 00:00:1779305897.864553  139931 bfc_allocator.cc:1105] InUse at 70b460a00 of size 256 next 234
I0000 00:00:1779305897.864557  139931 bfc_allocator.cc:1105] InUse at 70b460b00 of size 256 next 244
I0000 00:00:1779305897.864561  139931 bfc_allocator.cc:1105] InUse at 70b460c00 of size 256 next 247
I0000 00:00:1779305897.864564  139931 bfc_allocator.cc:1105] InUse at 70b460d00 of size 256 next 246
I0000 00:00:1779305897.864567  139931 bfc_allocator.cc:1105] InUse at 70b460e00 of size 256 next 250
I0000 00:00:1779305897.864571  139931 bfc_allocator.cc:1105] InUse at 70b460f00 of size 256 next 193
I0000 00:00:1779305897.864574  139931 bfc_allocator.cc:1105] InUse at 70b461000 of size 256 next 256
I0000 00:00:1779305897.864577  139931 bfc_allocator.cc:1105] InUse at 70b461100 of size 256 next 265
I0000 00:00:1779305897.864580  139931 bfc_allocator.cc:1105] InUse at 70b461200 of size 256 next 249
I0000 00:00:1779305897.864584  139931 bfc_allocator.cc:1105] InUse at 70b461300 of size 256 next 289
I0000 00:00:1779305897.864587  139931 bfc_allocator.cc:1105] InUse at 70b461400 of size 256 next 261
I0000 00:00:1779305897.864591  139931 bfc_allocator.cc:1105] Free  at 70b461500 of size 256 next 252
I0000 00:00:1779305897.864594  139931 bfc_allocator.cc:1105] InUse at 70b461600 of size 512 next 257
I0000 00:00:1779305897.864597  139931 bfc_allocator.cc:1105] InUse at 70b461800 of size 256 next 290
I0000 00:00:1779305897.864600  139931 bfc_allocator.cc:1105] InUse at 70b461900 of size 256 next 277
I0000 00:00:1779305897.864604  139931 bfc_allocator.cc:1105] Free  at 70b461a00 of size 768 next 285
I0000 00:00:1779305897.864608  139931 bfc_allocator.cc:1105] InUse at 70b461d00 of size 768 next 220
I0000 00:00:1779305897.864611  139931 bfc_allocator.cc:1105] InUse at 70b462000 of size 256 next 184
I0000 00:00:1779305897.864614  139931 bfc_allocator.cc:1105] InUse at 70b462100 of size 256 next 236
I0000 00:00:1779305897.864618  139931 bfc_allocator.cc:1105] InUse at 70b462200 of size 256 next 231
I0000 00:00:1779305897.864621  139931 bfc_allocator.cc:1105] InUse at 70b462300 of size 256 next 241
I0000 00:00:1779305897.864624  139931 bfc_allocator.cc:1105] InUse at 70b462400 of size 256 next 222
I0000 00:00:1779305897.864627  139931 bfc_allocator.cc:1105] InUse at 70b462500 of size 256 next 217
I0000 00:00:1779305897.864630  139931 bfc_allocator.cc:1105] InUse at 70b462600 of size 256 next 216
I0000 00:00:1779305897.864634  139931 bfc_allocator.cc:1105] InUse at 70b462700 of size 256 next 210
I0000 00:00:1779305897.864637  139931 bfc_allocator.cc:1105] InUse at 70b462800 of size 256 next 215
I0000 00:00:1779305897.864640  139931 bfc_allocator.cc:1105] InUse at 70b462900 of size 512 next 242
I0000 00:00:1779305897.864643  139931 bfc_allocator.cc:1105] InUse at 70b462b00 of size 512 next 203
I0000 00:00:1779305897.864646  139931 bfc_allocator.cc:1105] InUse at 70b462d00 of size 512 next 213
I0000 00:00:1779305897.864649  139931 bfc_allocator.cc:1105] InUse at 70b462f00 of size 768 next 58
I0000 00:00:1779305897.864653  139931 bfc_allocator.cc:1105] InUse at 70b463200 of size 256 next 154
I0000 00:00:1779305897.864656  139931 bfc_allocator.cc:1105] InUse at 70b463300 of size 256 next 52
I0000 00:00:1779305897.864659  139931 bfc_allocator.cc:1105] InUse at 70b463400 of size 512 next 53
I0000 00:00:1779305897.864662  139931 bfc_allocator.cc:1105] InUse at 70b463600 of size 512 next 51
I0000 00:00:1779305897.864665  139931 bfc_allocator.cc:1105] InUse at 70b463800 of size 512 next 167
I0000 00:00:1779305897.864669  139931 bfc_allocator.cc:1105] InUse at 70b463a00 of size 512 next 50
I0000 00:00:1779305897.864673  139931 bfc_allocator.cc:1105] InUse at 70b463c00 of size 74240 next 8
I0000 00:00:1779305897.864676  139931 bfc_allocator.cc:1105] InUse at 70b475e00 of size 256 next 9
I0000 00:00:1779305897.864680  139931 bfc_allocator.cc:1105] InUse at 70b475f00 of size 256 next 10
I0000 00:00:1779305897.864683  139931 bfc_allocator.cc:1105] InUse at 70b476000 of size 256 next 12
I0000 00:00:1779305897.864686  139931 bfc_allocator.cc:1105] InUse at 70b476100 of size 256 next 13
I0000 00:00:1779305897.864691  139931 bfc_allocator.cc:1105] InUse at 70b476200 of size 256 next 70
I0000 00:00:1779305897.864694  139931 bfc_allocator.cc:1105] InUse at 70b476300 of size 256 next 14
I0000 00:00:1779305897.864697  139931 bfc_allocator.cc:1105] InUse at 70b476400 of size 256 next 17
I0000 00:00:1779305897.864701  139931 bfc_allocator.cc:1105] InUse at 70b476500 of size 256 next 11
I0000 00:00:1779305897.864704  139931 bfc_allocator.cc:1105] InUse at 70b476600 of size 256 next 21
I0000 00:00:1779305897.864707  139931 bfc_allocator.cc:1105] InUse at 70b476700 of size 256 next 22
I0000 00:00:1779305897.864710  139931 bfc_allocator.cc:1105] InUse at 70b476800 of size 256 next 25
I0000 00:00:1779305897.864713  139931 bfc_allocator.cc:1105] InUse at 70b476900 of size 256 next 66
I0000 00:00:1779305897.864717  139931 bfc_allocator.cc:1105] InUse at 70b476a00 of size 256 next 27
I0000 00:00:1779305897.864720  139931 bfc_allocator.cc:1105] InUse at 70b476b00 of size 256 next 38
I0000 00:00:1779305897.864723  139931 bfc_allocator.cc:1105] InUse at 70b476c00 of size 256 next 29
I0000 00:00:1779305897.864726  139931 bfc_allocator.cc:1105] InUse at 70b476d00 of size 256 next 30
I0000 00:00:1779305897.864729  139931 bfc_allocator.cc:1105] InUse at 70b476e00 of size 256 next 31
I0000 00:00:1779305897.864733  139931 bfc_allocator.cc:1105] InUse at 70b476f00 of size 256 next 32
I0000 00:00:1779305897.864736  139931 bfc_allocator.cc:1105] InUse at 70b477000 of size 256 next 33
I0000 00:00:1779305897.864739  139931 bfc_allocator.cc:1105] InUse at 70b477100 of size 256 next 34
I0000 00:00:1779305897.864742  139931 bfc_allocator.cc:1105] InUse at 70b477200 of size 256 next 35
I0000 00:00:1779305897.864745  139931 bfc_allocator.cc:1105] InUse at 70b477300 of size 256 next 36
I0000 00:00:1779305897.864748  139931 bfc_allocator.cc:1105] InUse at 70b477400 of size 256 next 124
I0000 00:00:1779305897.864751  139931 bfc_allocator.cc:1105] InUse at 70b477500 of size 256 next 20
I0000 00:00:1779305897.864755  139931 bfc_allocator.cc:1105] InUse at 70b477600 of size 256 next 81
I0000 00:00:1779305897.864758  139931 bfc_allocator.cc:1105] InUse at 70b477700 of size 256 next 104
I0000 00:00:1779305897.864761  139931 bfc_allocator.cc:1105] InUse at 70b477800 of size 256 next 103
I0000 00:00:1779305897.864764  139931 bfc_allocator.cc:1105] InUse at 70b477900 of size 256 next 97
I0000 00:00:1779305897.864767  139931 bfc_allocator.cc:1105] InUse at 70b477a00 of size 256 next 98
I0000 00:00:1779305897.864770  139931 bfc_allocator.cc:1105] InUse at 70b477b00 of size 256 next 83
I0000 00:00:1779305897.864773  139931 bfc_allocator.cc:1105] InUse at 70b477c00 of size 256 next 80
I0000 00:00:1779305897.864777  139931 bfc_allocator.cc:1105] InUse at 70b477d00 of size 256 next 85
I0000 00:00:1779305897.864780  139931 bfc_allocator.cc:1105] InUse at 70b477e00 of size 256 next 135
I0000 00:00:1779305897.864783  139931 bfc_allocator.cc:1105] InUse at 70b477f00 of size 256 next 90
I0000 00:00:1779305897.864786  139931 bfc_allocator.cc:1105] InUse at 70b478000 of size 256 next 127
I0000 00:00:1779305897.864789  139931 bfc_allocator.cc:1105] InUse at 70b478100 of size 256 next 24
I0000 00:00:1779305897.864792  139931 bfc_allocator.cc:1105] InUse at 70b478200 of size 256 next 129

64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 353ms/step - accuracy: 0.3768 - loss: 2.7245

W0000 00:00:1779305909.373159  165208 hlo_rematerialization.cc:3204] Can't reduce memory use below 9.08GiB (9750085617 bytes) by rematerialization; only reduced to 37.81GiB (40597174304 bytes), down from 37.81GiB (40597174304 bytes) originally
W0000 00:00:1779305919.718039  139931 bfc_allocator.cc:502] Allocator (GPU_0_bfc) ran out of memory trying to allocate 37.79GiB (rounded to 40580659712)requested by op
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
I0000 00:00:1779305919.718353  139931 bfc_allocator.cc:1049] BFCAllocator dump for GPU_0_bfc
I0000 00:00:1779305919.718373  139931 bfc_allocator.cc:1056] Bin (256): 	Total Chunks: 224, Chunks in use: 224. 56.0KiB allocated for chunks. 56.0KiB in use in bin. 2.6KiB client-requested in use in bin.
I0000 00:00:1779305919.718390  139931 bfc_allocator.cc:1056] Bin (512): 	Total Chunks: 29, Chunks in use: 27. 15.0KiB allocated for chunks. 14.0KiB in use in bin. 13.5KiB client-requested in use in bin.
I0000 00:00:1779305919.718399  139931 bfc_allocator.cc:1056] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
I0000 00:00:1779305919.718407  139931 bfc_allocator.cc:1056] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718416  139931 bfc_allocator.cc:1056] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718422  139931 bfc_allocator.cc:1056] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718428  139931 bfc_allocator.cc:1056] Bin (16384): 	Total Chunks: 10, Chunks in use: 10. 230.0KiB allocated for chunks. 230.0KiB in use in bin. 230.0KiB client-requested in use in bin.
I0000 00:00:1779305919.718437  139931 bfc_allocator.cc:1056] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718443  139931 bfc_allocator.cc:1056] Bin (65536): 	Total Chunks: 10, Chunks in use: 9. 715.0KiB allocated for chunks. 651.0KiB in use in bin. 576.0KiB client-requested in use in bin.
I0000 00:00:1779305919.718451  139931 bfc_allocator.cc:1056] Bin (131072): 	Total Chunks: 11, Chunks in use: 10. 2.42MiB allocated for chunks. 2.24MiB in use in bin. 2.22MiB client-requested in use in bin.
I0000 00:00:1779305919.718459  139931 bfc_allocator.cc:1056] Bin (262144): 	Total Chunks: 8, Chunks in use: 8. 2.64MiB allocated for chunks. 2.64MiB in use in bin. 2.50MiB client-requested in use in bin.
I0000 00:00:1779305919.718466  139931 bfc_allocator.cc:1056] Bin (524288): 	Total Chunks: 7, Chunks in use: 6. 4.95MiB allocated for chunks. 4.22MiB in use in bin. 3.97MiB client-requested in use in bin.
I0000 00:00:1779305919.718473  139931 bfc_allocator.cc:1056] Bin (1048576): 	Total Chunks: 1, Chunks in use: 1. 1.54MiB allocated for chunks. 1.54MiB in use in bin. 1.42MiB client-requested in use in bin.
I0000 00:00:1779305919.718480  139931 bfc_allocator.cc:1056] Bin (2097152): 	Total Chunks: 2, Chunks in use: 1. 5.29MiB allocated for chunks. 2.34MiB in use in bin. 2.34MiB client-requested in use in bin.
I0000 00:00:1779305919.718487  139931 bfc_allocator.cc:1056] Bin (4194304): 	Total Chunks: 2, Chunks in use: 1. 14.71MiB allocated for chunks. 7.63MiB in use in bin. 7.63MiB client-requested in use in bin.
I0000 00:00:1779305919.718494  139931 bfc_allocator.cc:1056] Bin (8388608): 	Total Chunks: 5, Chunks in use: 5. 75.25MiB allocated for chunks. 75.25MiB in use in bin. 70.63MiB client-requested in use in bin.
I0000 00:00:1779305919.718502  139931 bfc_allocator.cc:1056] Bin (16777216): 	Total Chunks: 4, Chunks in use: 4. 83.67MiB allocated for chunks. 83.67MiB in use in bin. 71.37MiB client-requested in use in bin.
I0000 00:00:1779305919.718509  139931 bfc_allocator.cc:1056] Bin (33554432): 	Total Chunks: 1, Chunks in use: 1. 53.50MiB allocated for chunks. 53.50MiB in use in bin. 53.50MiB client-requested in use in bin.
I0000 00:00:1779305919.718516  139931 bfc_allocator.cc:1056] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718522  139931 bfc_allocator.cc:1056] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718533  139931 bfc_allocator.cc:1056] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 9.05GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305919.718541  139931 bfc_allocator.cc:1072] Bin for 37.79GiB was 256.00MiB, Chunk State:
I0000 00:00:1779305919.718547  139931 bfc_allocator.cc:1078]   Size: 9.05GiB | Requested Size: 91.71MiB | in_use: 0 | bin_num: 20, prev:   Size: 15.75MiB | Requested Size: 15.75MiB | in_use: 1 | bin_num: -1
I0000 00:00:1779305919.718561  139931 bfc_allocator.cc:1085] Next region of size 9970909184
I0000 00:00:1779305919.718569  139931 bfc_allocator.cc:1105] InUse at 70b400000 of size 1280 next 1
I0000 00:00:1779305919.718575  139931 bfc_allocator.cc:1105] InUse at 70b400500 of size 256 next 2
I0000 00:00:1779305919.718579  139931 bfc_allocator.cc:1105] InUse at 70b400600 of size 256 next 3
I0000 00:00:1779305919.718582  139931 bfc_allocator.cc:1105] InUse at 70b400700 of size 256 next 4
I0000 00:00:1779305919.718586  139931 bfc_allocator.cc:1105] InUse at 70b400800 of size 256 next 5
I0000 00:00:1779305919.718590  139931 bfc_allocator.cc:1105] InUse at 70b400900 of size 256 next 6
I0000 00:00:1779305919.718594  139931 bfc_allocator.cc:1105] InUse at 70b400a00 of size 240128 next 7
I0000 00:00:1779305919.718599  139931 bfc_allocator.cc:1105] InUse at 70b43b400 of size 23552 next 148
I0000 00:00:1779305919.718604  139931 bfc_allocator.cc:1105] InUse at 70b441000 of size 89344 next 28
I0000 00:00:1779305919.718608  139931 bfc_allocator.cc:1105] InUse at 70b456d00 of size 256 next 111
I0000 00:00:1779305919.718619  139931 bfc_allocator.cc:1105] InUse at 70b456e00 of size 256 next 93
I0000 00:00:1779305919.718623  139931 bfc_allocator.cc:1105] InUse at 70b456f00 of size 256 next 92
I0000 00:00:1779305919.718626  139931 bfc_allocator.cc:1105] InUse at 70b457000 of size 256 next 102
I0000 00:00:1779305919.718630  139931 bfc_allocator.cc:1105] InUse at 70b457100 of size 256 next 162
I0000 00:00:1779305919.718633  139931 bfc_allocator.cc:1105] InUse at 70b457200 of size 256 next 19
I0000 00:00:1779305919.718637  139931 bfc_allocator.cc:1105] InUse at 70b457300 of size 256 next 15
I0000 00:00:1779305919.718641  139931 bfc_allocator.cc:1105] InUse at 70b457400 of size 256 next 77
I0000 00:00:1779305919.718644  139931 bfc_allocator.cc:1105] InUse at 70b457500 of size 256 next 128
I0000 00:00:1779305919.718711  139931 bfc_allocator.cc:1105] InUse at 70b457600 of size 256 next 171
I0000 00:00:1779305919.718748  139931 bfc_allocator.cc:1105] InUse at 70b457700 of size 256 next 91
I0000 00:00:1779305919.718755  139931 bfc_allocator.cc:1105] InUse at 70b457800 of size 23552 next 169
I0000 00:00:1779305919.718760  139931 bfc_allocator.cc:1105] InUse at 70b45d400 of size 256 next 178
I0000 00:00:1779305919.718764  139931 bfc_allocator.cc:1105] InUse at 70b45d500 of size 256 next 88
I0000 00:00:1779305919.718767  139931 bfc_allocator.cc:1105] InUse at 70b45d600 of size 256 next 134
I0000 00:00:1779305919.718771  139931 bfc_allocator.cc:1105] InUse at 70b45d700 of size 256 next 179
I0000 00:00:1779305919.718775  139931 bfc_allocator.cc:1105] InUse at 70b45d800 of size 256 next 180
I0000 00:00:1779305919.718778  139931 bfc_allocator.cc:1105] InUse at 70b45d900 of size 256 next 163
I0000 00:00:1779305919.718782  139931 bfc_allocator.cc:1105] InUse at 70b45da00 of size 256 next 182
I0000 00:00:1779305919.718785  139931 bfc_allocator.cc:1105] InUse at 70b45db00 of size 256 next 156
I0000 00:00:1779305919.718789  139931 bfc_allocator.cc:1105] InUse at 70b45dc00 of size 256 next 185
I0000 00:00:1779305919.718792  139931 bfc_allocator.cc:1105] InUse at 70b45dd00 of size 256 next 100
I0000 00:00:1779305919.718796  139931 bfc_allocator.cc:1105] InUse at 70b45de00 of size 256 next 181
I0000 00:00:1779305919.718799  139931 bfc_allocator.cc:1105] InUse at 70b45df00 of size 256 next 190
I0000 00:00:1779305919.718805  139931 bfc_allocator.cc:1105] InUse at 70b45e000 of size 256 next 189
I0000 00:00:1779305919.718809  139931 bfc_allocator.cc:1105] InUse at 70b45e100 of size 256 next 118
I0000 00:00:1779305919.718813  139931 bfc_allocator.cc:1105] InUse at 70b45e200 of size 256 next 187
I0000 00:00:1779305919.718816  139931 bfc_allocator.cc:1105] InUse at 70b45e300 of size 256 next 194
I0000 00:00:1779305919.718820  139931 bfc_allocator.cc:1105] InUse at 70b45e400 of size 256 next 166
I0000 00:00:1779305919.718824  139931 bfc_allocator.cc:1105] InUse at 70b45e500 of size 256 next 195
I0000 00:00:1779305919.718827  139931 bfc_allocator.cc:1105] InUse at 70b45e600 of size 256 next 191
I0000 00:00:1779305919.718832  139931 bfc_allocator.cc:1105] InUse at 70b45e700 of size 256 next 200
I0000 00:00:1779305919.718836  139931 bfc_allocator.cc:1105] InUse at 70b45e800 of size 256 next 183
I0000 00:00:1779305919.718840  139931 bfc_allocator.cc:1105] InUse at 70b45e900 of size 512 next 142
I0000 00:00:1779305919.718844  139931 bfc_allocator.cc:1105] InUse at 70b45eb00 of size 256 next 188
I0000 00:00:1779305919.718847  139931 bfc_allocator.cc:1105] InUse at 70b45ec00 of size 256 next 228
I0000 00:00:1779305919.718851  139931 bfc_allocator.cc:1105] InUse at 70b45ed00 of size 256 next 253
I0000 00:00:1779305919.718854  139931 bfc_allocator.cc:1105] InUse at 70b45ee00 of size 256 next 201
I0000 00:00:1779305919.718858  139931 bfc_allocator.cc:1105] InUse at 70b45ef00 of size 256 next 259
I0000 00:00:1779305919.718861  139931 bfc_allocator.cc:1105] InUse at 70b45f000 of size 256 next 258
I0000 00:00:1779305919.718865  139931 bfc_allocator.cc:1105] InUse at 70b45f100 of size 512 next 206
I0000 00:00:1779305919.718869  139931 bfc_allocator.cc:1105] InUse at 70b45f300 of size 512 next 199
I0000 00:00:1779305919.718872  139931 bfc_allocator.cc:1105] InUse at 70b45f500 of size 256 next 223
I0000 00:00:1779305919.718876  139931 bfc_allocator.cc:1105] InUse at 70b45f600 of size 512 next 209
I0000 00:00:1779305919.718880  139931 bfc_allocator.cc:1105] InUse at 70b45f800 of size 512 next 192
I0000 00:00:1779305919.718883  139931 bfc_allocator.cc:1105] InUse at 70b45fa00 of size 256 next 237
I0000 00:00:1779305919.718887  139931 bfc_allocator.cc:1105] InUse at 70b45fb00 of size 256 next 198
I0000 00:00:1779305919.718890  139931 bfc_allocator.cc:1105] InUse at 70b45fc00 of size 256 next 208
I0000 00:00:1779305919.718894  139931 bfc_allocator.cc:1105] InUse at 70b45fd00 of size 256 next 232
I0000 00:00:1779305919.718897  139931 bfc_allocator.cc:1105] InUse at 70b45fe00 of size 256 next 248
I0000 00:00:1779305919.718901  139931 bfc_allocator.cc:1105] InUse at 70b45ff00 of size 256 next 260
I0000 00:00:1779305919.718904  139931 bfc_allocator.cc:1105] InUse at 70b460000 of size 256 next 174
I0000 00:00:1779305919.718908  139931 bfc_allocator.cc:1105] InUse at 70b460100 of size 256 next 225
I0000 00:00:1779305919.718911  139931 bfc_allocator.cc:1105] InUse at 70b460200 of size 256 next 207
I0000 00:00:1779305919.718915  139931 bfc_allocator.cc:1105] InUse at 70b460300 of size 256 next 243
I0000 00:00:1779305919.718918  139931 bfc_allocator.cc:1105] InUse at 70b460400 of size 256 next 219
I0000 00:00:1779305919.718922  139931 bfc_allocator.cc:1105] InUse at 70b460500 of size 256 next 224
I0000 00:00:1779305919.718925  139931 bfc_allocator.cc:1105] InUse at 70b460600 of size 256 next 221
I0000 00:00:1779305919.718929  139931 bfc_allocator.cc:1105] InUse at 70b460700 of size 256 next 229
I0000 00:00:1779305919.718933  139931 bfc_allocator.cc:1105] InUse at 70b460800 of size 256 next 227
I0000 00:00:1779305919.718936  139931 bfc_allocator.cc:1105] InUse at 70b460900 of size 256 next 226
I0000 00:00:1779305919.718940  139931 bfc_allocator.cc:1105] InUse at 70b460a00 of size 256 next 234
I0000 00:00:1779305919.718943  139931 bfc_allocator.cc:1105] InUse at 70b460b00 of size 256 next 244
I0000 00:00:1779305919.718947  139931 bfc_allocator.cc:1105] InUse at 70b460c00 of size 256 next 247
I0000 00:00:1779305919.718952  139931 bfc_allocator.cc:1105] InUse at 70b460d00 of size 256 next 246
I0000 00:00:1779305919.718955  139931 bfc_allocator.cc:1105] InUse at 70b460e00 of size 256 next 250
I0000 00:00:1779305919.718959  139931 bfc_allocator.cc:1105] InUse at 70b460f00 of size 256 next 193
I0000 00:00:1779305919.718962  139931 bfc_allocator.cc:1105] InUse at 70b461000 of size 256 next 256
I0000 00:00:1779305919.718966  139931 bfc_allocator.cc:1105] InUse at 70b461100 of size 256 next 265
I0000 00:00:1779305919.718969  139931 bfc_allocator.cc:1105] InUse at 70b461200 of size 256 next 249
I0000 00:00:1779305919.718973  139931 bfc_allocator.cc:1105] InUse at 70b461300 of size 256 next 289
I0000 00:00:1779305919.718976  139931 bfc_allocator.cc:1105] InUse at 70b461400 of size 256 next 261
I0000 00:00:1779305919.718980  139931 bfc_allocator.cc:1105] InUse at 70b461500 of size 256 next 252
I0000 00:00:1779305919.718984  139931 bfc_allocator.cc:1105] InUse at 70b461600 of size 512 next 257
I0000 00:00:1779305919.718987  139931 bfc_allocator.cc:1105] InUse at 70b461800 of size 256 next 290
I0000 00:00:1779305919.718991  139931 bfc_allocator.cc:1105] InUse at 70b461900 of size 256 next 277
I0000 00:00:1779305919.718994  139931 bfc_allocator.cc:1105] InUse at 70b461a00 of size 256 next 272
I0000 00:00:1779305919.718998  139931 bfc_allocator.cc:1105] InUse at 70b461b00 of size 256 next 310
I0000 00:00:1779305919.719001  139931 bfc_allocator.cc:1105] InUse at 70b461c00 of size 256 next 285
I0000 00:00:1779305919.719008  139931 bfc_allocator.cc:1105] InUse at 70b461d00 of size 768 next 220
I0000 00:00:1779305919.719011  139931 bfc_allocator.cc:1105] InUse at 70b462000 of size 256 next 184
I0000 00:00:1779305919.719015  139931 bfc_allocator.cc:1105] InUse at 70b462100 of size 256 next 236
I0000 00:00:1779305919.719019  139931 bfc_allocator.cc:1105] InUse at 70b462200 of size 256 next 231
I0000 00:00:1779305919.719022  139931 bfc_allocator.cc:1105] InUse at 70b462300 of size 256 next 241
I0000 00:00:1779305919.719026  139931 bfc_allocator.cc:1105] InUse at 70b462400 of size 256 next 222
I0000 00:00:1779305919.719029  139931 bfc_allocator.cc:1105] InUse at 70b462500 of size 256 next 217
I0000 00:00:1779305919.719033  139931 bfc_allocator.cc:1105] InUse at 70b462600 of size 256 next 216
I0000 00:00:1779305919.719037  139931 bfc_allocator.cc:1105] InUse at 70b462700 of size 256 next 210
I0000 00:00:1779305919.719040  139931 bfc_allocator.cc:1105] InUse at 70b462800 of size 256 next 215
I0000 00:00:1779305919.719044  139931 bfc_allocator.cc:1105] InUse at 70b462900 of size 512 next 242
I0000 00:00:1779305919.719055  139931 bfc_allocator.cc:1105] InUse at 70b462b00 of size 512 next 203
I0000 00:00:1779305919.719059  139931 bfc_allocator.cc:1105] InUse at 70b462d00 of size 512 next 213
I0000 00:00:1779305919.719062  139931 bfc_allocator.cc:1105] InUse at 70b462f00 of size 768 next 58
I0000 00:00:1779305919.719066  139931 bfc_allocator.cc:1105] InUse at 70b463200 of size 256 next 154
I0000 00:00:1779305919.719069  139931 bfc_allocator.cc:1105] InUse at 70b463300 of size 256 next 52
I0000 00:00:1779305919.719073  139931 bfc_allocator.cc:1105] InUse at 70b463400 of size 512 next 53
I0000 00:00:1779305919.719076  139931 bfc_allocator.cc:1105] InUse at 70b463600 of size 512 next 51
I0000 00:00:1779305919.719080  139931 bfc_allocator.cc:1105] InUse at 70b463800 of size 512 next 167
I0000 00:00:1779305919.719083  139931 bfc_allocator.cc:1105] InUse at 70b463a00 of size 512 next 50
I0000 00:00:1779305919.719088  139931 bfc_allocator.cc:1105] InUse at 70b463c00 of size 74240 next 8
I0000 00:00:1779305919.719092  139931 bfc_allocator.cc:1105] InUse at 70b475e00 of size 256 next 9
I0000 00:00:1779305919.719096  139931 bfc_allocator.cc:1105] InUse at 70b475f00 of size 256 next 10
I0000 00:00:1779305919.719099  139931 bfc_allocator.cc:1105] InUse at 70b476000 of size 256 next 12
I0000 00:00:1779305919.719103  139931 bfc_allocator.cc:1105] InUse at 70b476100 of size 256 next 13
I0000 00:00:1779305919.719108  139931 bfc_allocator.cc:1105] InUse at 70b476200 of size 256 next 70
I0000 00:00:1779305919.719111  139931 bfc_allocator.cc:1105] InUse at 70b476300 of size 256 next 14
I0000 00:00:1779305919.719115  139931 bfc_allocator.cc:1105] InUse at 70b476400 of size 256 next 17
I0000 00:00:1779305919.719119  139931 bfc_allocator.cc:1105] InUse at 70b476500 of size 256 next 11
I0000 00:00:1779305919.719122  139931 bfc_allocator.cc:1105] InUse at 70b476600 of size 256 next 21
I0000 00:00:1779305919.719126  139931 bfc_allocator.cc:1105] InUse at 70b476700 of size 256 next 22
I0000 00:00:1779305919.719129  139931 bfc_allocator.cc:1105] InUse at 70b476800 of size 256 next 25
I0000 00:00:1779305919.719133  139931 bfc_allocator.cc:1105] InUse at 70b476900 of size 256 next 66
I0000 00:00:1779305919.719136  139931 bfc_allocator.cc:1105] InUse at 70b476a00 of size 256 next 27
I0000 00:00:1779305919.719140  139931 bfc_allocator.cc:1105] InUse at 70b476b00 of size 256 next 38
I0000 00:00:1779305919.719143  139931 bfc_allocator.cc:1105] InUse at 70b476c00 of size 256 next 29
I0000 00:00:1779305919.719167  139931 bfc_allocator.cc:1105] InUse at 70b476d00 of size 256 next 30
I0000 00:00:1779305919.719171  139931 bfc_allocator.cc:1105] InUse at 70b476e00 of size 256 next 31
I0000 00:00:1779305919.719175  139931 bfc_allocator.cc:1105] InUse at 70b476f00 of size 256 next 32
I0000 00:00:1779305919.719179  139931 bfc_allocator.cc:1105] InUse at 70b477000 of size 256 next 33
I0000 00:00:1779305919.719182  139931 bfc_allocator.cc:1105] InUse at 70b477100 of size 256 next 34
I0000 00:00:1779305919.719186  139931 bfc_allocator.cc:1105] InUse at 70b477200 of size 256 next 35
I0000 00:00:1779305919.719190  139931 bfc_allocator.cc:1105] InUse at 70b477300 of size 256 next 36
I0000 00:00:1779305919.719195  139931 bfc_allocator.cc:1105] InUse at 70b477400 of size 256 next 124
I0000 00:00:1779305919.719198  139931 bfc_allocator.cc:1105] InUse at 70b477500 of size 256 next 20
I0000 00:00:1779305919.719202  139931 bfc_allocator.cc:1105] InUse at 70b477600 of size 256 next 81
I0000 00:00:1779305919.719206  139931 bfc_allocator.cc:1105] InUse at 70b477700 of size 256 next 104
I0000 00:00:1779305919.719209  139931 bfc_allocator.cc:1105] InUse at 70b477800 of size 256 next 103
I0000 00:00:1779305919.719213  139931 bfc_allocator.cc:1105] InUse at 70b477900 of size 256 next 97
I0000 00:00:1779305919.719217  139931 bfc_allocator.cc:1105] InUse at 70b477a00 of size 256 next 98
I0000 00:00:1779305919.719220  139931 bfc_allocator.cc:1105] InUse at 70b477b00 of size 256 next 83
I0000 00:00:1779305919.719224  139931 bfc_allocator.cc:1105] InUse at 70b477c00 of size 256 next 80
I0000 00:00:1779305919.719227  139931 bfc_allocator.cc:1105] InUse at 70b477d00 of size 256 next 85
I0000 00:00:1779305919.719231  139931 bfc_allocator.cc:1105] InUse at 70b477e00 of size 256 next 135
I0000 00:00:1779305919.719235  139931 bfc_allocator.cc:1105] InUse at 70b477f00 of size 256 next 90
I0000 00:00:1779305919.719238  139931 bfc_allocator.cc:1105] InUse at 70b478000 of size 256 next 127
I0000 00:00:1779305919.719242  139931 bfc_allocator.cc:1105] InUse at 70b478100 of size 256 next 24

64/64 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.4527 - loss: 2.3579 - val_accuracy: 0.5106 - val_loss: 1.8819
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5415 - loss: 1.8408 - val_accuracy: 0.5562 - val_loss: 1.7535
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5759 - loss: 1.7045 - val_accuracy: 0.5751 - val_loss: 1.6734
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5938 - loss: 1.6075 - val_accuracy: 0.6073 - val_loss: 1.6207
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6159 - loss: 1.5066 - val_accuracy: 0.6151 - val_loss: 1.5755
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6431 - loss: 1.4290 - val_accuracy: 0.6207 - val_loss: 1.5367
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6675 - loss: 1.3386 - val_accuracy: 0.6463 - val_loss: 1.4885
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6936 - loss: 1.2228 - val_accuracy: 0.6630 - val_loss: 1.4334
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7135 - loss: 1.1187 - val_accuracy: 0.6685 - val_loss: 1.4435
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7315 - loss: 1.0417 - val_accuracy: 0.6785 - val_loss: 1.3975
Restoring model weights from the end of the best epoch: 10.

W0000 00:00:1779305955.519873  166813 hlo_rematerialization.cc:3204] Can't reduce memory use below 9.11GiB (9777482942 bytes) by rematerialization; only reduced to 23.62GiB (25367328800 bytes), down from 23.62GiB (25367328800 bytes) originally
W0000 00:00:1779305965.598546  139928 bfc_allocator.cc:502] Allocator (GPU_0_bfc) ran out of memory trying to allocate 23.62GiB (rounded to 25363200512)requested by op
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
I0000 00:00:1779305965.598764  139928 bfc_allocator.cc:1049] BFCAllocator dump for GPU_0_bfc
I0000 00:00:1779305965.598778  139928 bfc_allocator.cc:1056] Bin (256): 	Total Chunks: 240, Chunks in use: 240. 60.0KiB allocated for chunks. 60.0KiB in use in bin. 2.7KiB client-requested in use in bin.
I0000 00:00:1779305965.598791  139928 bfc_allocator.cc:1056] Bin (512): 	Total Chunks: 28, Chunks in use: 27. 14.8KiB allocated for chunks. 14.0KiB in use in bin. 13.5KiB client-requested in use in bin.
I0000 00:00:1779305965.598798  139928 bfc_allocator.cc:1056] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
I0000 00:00:1779305965.598805  139928 bfc_allocator.cc:1056] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598813  139928 bfc_allocator.cc:1056] Bin (4096): 	Total Chunks: 1, Chunks in use: 1. 5.8KiB allocated for chunks. 5.8KiB in use in bin. 5.8KiB client-requested in use in bin.
I0000 00:00:1779305965.598819  139928 bfc_allocator.cc:1056] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598825  139928 bfc_allocator.cc:1056] Bin (16384): 	Total Chunks: 10, Chunks in use: 9. 224.5KiB allocated for chunks. 207.0KiB in use in bin. 207.0KiB client-requested in use in bin.
I0000 00:00:1779305965.598832  139928 bfc_allocator.cc:1056] Bin (32768): 	Total Chunks: 1, Chunks in use: 1. 35.5KiB allocated for chunks. 35.5KiB in use in bin. 32.0KiB client-requested in use in bin.
I0000 00:00:1779305965.598839  139928 bfc_allocator.cc:1056] Bin (65536): 	Total Chunks: 11, Chunks in use: 9. 826.5KiB allocated for chunks. 651.0KiB in use in bin. 576.0KiB client-requested in use in bin.
I0000 00:00:1779305965.598846  139928 bfc_allocator.cc:1056] Bin (131072): 	Total Chunks: 8, Chunks in use: 8. 1.94MiB allocated for chunks. 1.94MiB in use in bin. 1.94MiB client-requested in use in bin.
I0000 00:00:1779305965.598852  139928 bfc_allocator.cc:1056] Bin (262144): 	Total Chunks: 10, Chunks in use: 10. 3.43MiB allocated for chunks. 3.43MiB in use in bin. 3.26MiB client-requested in use in bin.
I0000 00:00:1779305965.598859  139928 bfc_allocator.cc:1056] Bin (524288): 	Total Chunks: 7, Chunks in use: 6. 4.87MiB allocated for chunks. 4.22MiB in use in bin. 3.97MiB client-requested in use in bin.
I0000 00:00:1779305965.598865  139928 bfc_allocator.cc:1056] Bin (1048576): 	Total Chunks: 1, Chunks in use: 0. 1.54MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598871  139928 bfc_allocator.cc:1056] Bin (2097152): 	Total Chunks: 3, Chunks in use: 2. 8.86MiB allocated for chunks. 6.28MiB in use in bin. 6.28MiB client-requested in use in bin.
I0000 00:00:1779305965.598877  139928 bfc_allocator.cc:1056] Bin (4194304): 	Total Chunks: 2, Chunks in use: 2. 14.71MiB allocated for chunks. 14.71MiB in use in bin. 11.57MiB client-requested in use in bin.
I0000 00:00:1779305965.598884  139928 bfc_allocator.cc:1056] Bin (8388608): 	Total Chunks: 5, Chunks in use: 5. 75.25MiB allocated for chunks. 75.25MiB in use in bin. 70.63MiB client-requested in use in bin.
I0000 00:00:1779305965.598890  139928 bfc_allocator.cc:1056] Bin (16777216): 	Total Chunks: 4, Chunks in use: 4. 92.92MiB allocated for chunks. 92.92MiB in use in bin. 81.00MiB client-requested in use in bin.
I0000 00:00:1779305965.598896  139928 bfc_allocator.cc:1056] Bin (33554432): 	Total Chunks: 1, Chunks in use: 0. 40.31MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598908  139928 bfc_allocator.cc:1056] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598913  139928 bfc_allocator.cc:1056] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598919  139928 bfc_allocator.cc:1056] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 9.05GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
I0000 00:00:1779305965.598925  139928 bfc_allocator.cc:1072] Bin for 23.62GiB was 256.00MiB, Chunk State:
I0000 00:00:1779305965.598931  139928 bfc_allocator.cc:1078]   Size: 9.05GiB | Requested Size: 51.27MiB | in_use: 0 | bin_num: 20, prev:   Size: 15.75MiB | Requested Size: 15.75MiB | in_use: 1 | bin_num: -1
I0000 00:00:1779305965.598943  139928 bfc_allocator.cc:1085] Next region of size 9970909184
I0000 00:00:1779305965.598951  139928 bfc_allocator.cc:1105] InUse at 70b400000 of size 1280 next 1
I0000 00:00:1779305965.598956  139928 bfc_allocator.cc:1105] InUse at 70b400500 of size 256 next 2
I0000 00:00:1779305965.598959  139928 bfc_allocator.cc:1105] InUse at 70b400600 of size 256 next 3
I0000 00:00:1779305965.598962  139928 bfc_allocator.cc:1105] InUse at 70b400700 of size 256 next 4
I0000 00:00:1779305965.598966  139928 bfc_allocator.cc:1105] InUse at 70b400800 of size 256 next 5
I0000 00:00:1779305965.598969  139928 bfc_allocator.cc:1105] InUse at 70b400900 of size 256 next 6
I0000 00:00:1779305965.598973  139928 bfc_allocator.cc:1105] InUse at 70b400a00 of size 240128 next 7
I0000 00:00:1779305965.598978  139928 bfc_allocator.cc:1105] InUse at 70b43b400 of size 23552 next 148
I0000 00:00:1779305965.598982  139928 bfc_allocator.cc:1105] InUse at 70b441000 of size 89344 next 28
I0000 00:00:1779305965.598986  139928 bfc_allocator.cc:1105] InUse at 70b456d00 of size 256 next 111
I0000 00:00:1779305965.598989  139928 bfc_allocator.cc:1105] InUse at 70b456e00 of size 256 next 93
I0000 00:00:1779305965.598992  139928 bfc_allocator.cc:1105] InUse at 70b456f00 of size 256 next 92
I0000 00:00:1779305965.598995  139928 bfc_allocator.cc:1105] InUse at 70b457000 of size 256 next 102
I0000 00:00:1779305965.598999  139928 bfc_allocator.cc:1105] InUse at 70b457100 of size 256 next 162
I0000 00:00:1779305965.599002  139928 bfc_allocator.cc:1105] InUse at 70b457200 of size 256 next 19
I0000 00:00:1779305965.599005  139928 bfc_allocator.cc:1105] InUse at 70b457300 of size 256 next 15
I0000 00:00:1779305965.599008  139928 bfc_allocator.cc:1105] InUse at 70b457400 of size 256 next 77
I0000 00:00:1779305965.599011  139928 bfc_allocator.cc:1105] InUse at 70b457500 of size 256 next 128
I0000 00:00:1779305965.599015  139928 bfc_allocator.cc:1105] InUse at 70b457600 of size 256 next 171
I0000 00:00:1779305965.599018  139928 bfc_allocator.cc:1105] InUse at 70b457700 of size 256 next 91
I0000 00:00:1779305965.599021  139928 bfc_allocator.cc:1105] InUse at 70b457800 of size 23552 next 169
I0000 00:00:1779305965.599025  139928 bfc_allocator.cc:1105] InUse at 70b45d400 of size 256 next 178
I0000 00:00:1779305965.599028  139928 bfc_allocator.cc:1105] InUse at 70b45d500 of size 256 next 88
I0000 00:00:1779305965.599031  139928 bfc_allocator.cc:1105] InUse at 70b45d600 of size 256 next 134
I0000 00:00:1779305965.599034  139928 bfc_allocator.cc:1105] InUse at 70b45d700 of size 256 next 179
I0000 00:00:1779305965.599037  139928 bfc_allocator.cc:1105] InUse at 70b45d800 of size 256 next 180
I0000 00:00:1779305965.599041  139928 bfc_allocator.cc:1105] InUse at 70b45d900 of size 256 next 163
I0000 00:00:1779305965.599044  139928 bfc_allocator.cc:1105] InUse at 70b45da00 of size 256 next 182
I0000 00:00:1779305965.599047  139928 bfc_allocator.cc:1105] InUse at 70b45db00 of size 256 next 156
I0000 00:00:1779305965.599052  139928 bfc_allocator.cc:1105] InUse at 70b45dc00 of size 256 next 185
I0000 00:00:1779305965.599056  139928 bfc_allocator.cc:1105] InUse at 70b45dd00 of size 256 next 100
I0000 00:00:1779305965.599059  139928 bfc_allocator.cc:1105] InUse at 70b45de00 of size 256 next 181
I0000 00:00:1779305965.599062  139928 bfc_allocator.cc:1105] InUse at 70b45df00 of size 256 next 190
I0000 00:00:1779305965.599065  139928 bfc_allocator.cc:1105] InUse at 70b45e000 of size 256 next 189
I0000 00:00:1779305965.599069  139928 bfc_allocator.cc:1105] InUse at 70b45e100 of size 256 next 118
I0000 00:00:1779305965.599072  139928 bfc_allocator.cc:1105] InUse at 70b45e200 of size 256 next 187
I0000 00:00:1779305965.599075  139928 bfc_allocator.cc:1105] InUse at 70b45e300 of size 256 next 194
I0000 00:00:1779305965.599078  139928 bfc_allocator.cc:1105] InUse at 70b45e400 of size 256 next 166
I0000 00:00:1779305965.599081  139928 bfc_allocator.cc:1105] InUse at 70b45e500 of size 256 next 195
I0000 00:00:1779305965.599085  139928 bfc_allocator.cc:1105] InUse at 70b45e600 of size 256 next 191
I0000 00:00:1779305965.599088  139928 bfc_allocator.cc:1105] InUse at 70b45e700 of size 256 next 200
I0000 00:00:1779305965.599091  139928 bfc_allocator.cc:1105] InUse at 70b45e800 of size 256 next 183
I0000 00:00:1779305965.599094  139928 bfc_allocator.cc:1105] InUse at 70b45e900 of size 512 next 142
I0000 00:00:1779305965.599098  139928 bfc_allocator.cc:1105] InUse at 70b45eb00 of size 256 next 188
I0000 00:00:1779305965.599101  139928 bfc_allocator.cc:1105] InUse at 70b45ec00 of size 256 next 228
I0000 00:00:1779305965.599104  139928 bfc_allocator.cc:1105] InUse at 70b45ed00 of size 256 next 253
I0000 00:00:1779305965.599107  139928 bfc_allocator.cc:1105] InUse at 70b45ee00 of size 256 next 201
I0000 00:00:1779305965.599110  139928 bfc_allocator.cc:1105] InUse at 70b45ef00 of size 256 next 259
I0000 00:00:1779305965.599114  139928 bfc_allocator.cc:1105] InUse at 70b45f000 of size 256 next 258
I0000 00:00:1779305965.599117  139928 bfc_allocator.cc:1105] InUse at 70b45f100 of size 512 next 206
I0000 00:00:1779305965.599120  139928 bfc_allocator.cc:1105] InUse at 70b45f300 of size 512 next 199
I0000 00:00:1779305965.599123  139928 bfc_allocator.cc:1105] InUse at 70b45f500 of size 256 next 223
I0000 00:00:1779305965.599127  139928 bfc_allocator.cc:1105] InUse at 70b45f600 of size 512 next 209
I0000 00:00:1779305965.599137  139928 bfc_allocator.cc:1105] InUse at 70b45f800 of size 512 next 192
I0000 00:00:1779305965.599140  139928 bfc_allocator.cc:1105] InUse at 70b45fa00 of size 256 next 237
I0000 00:00:1779305965.599144  139928 bfc_allocator.cc:1105] InUse at 70b45fb00 of size 256 next 198
I0000 00:00:1779305965.599147  139928 bfc_allocator.cc:1105] InUse at 70b45fc00 of size 256 next 208
I0000 00:00:1779305965.599150  139928 bfc_allocator.cc:1105] InUse at 70b45fd00 of size 256 next 232
I0000 00:00:1779305965.599153  139928 bfc_allocator.cc:1105] InUse at 70b45fe00 of size 256 next 248
I0000 00:00:1779305965.599156  139928 bfc_allocator.cc:1105] InUse at 70b45ff00 of size 256 next 260
I0000 00:00:1779305965.599159  139928 bfc_allocator.cc:1105] InUse at 70b460000 of size 256 next 174
I0000 00:00:1779305965.599163  139928 bfc_allocator.cc:1105] InUse at 70b460100 of size 256 next 225
I0000 00:00:1779305965.599166  139928 bfc_allocator.cc:1105] InUse at 70b460200 of size 256 next 207
I0000 00:00:1779305965.599169  139928 bfc_allocator.cc:1105] InUse at 70b460300 of size 256 next 243
I0000 00:00:1779305965.599172  139928 bfc_allocator.cc:1105] InUse at 70b460400 of size 256 next 219
I0000 00:00:1779305965.599175  139928 bfc_allocator.cc:1105] InUse at 70b460500 of size 256 next 224
I0000 00:00:1779305965.599179  139928 bfc_allocator.cc:1105] InUse at 70b460600 of size 256 next 221
I0000 00:00:1779305965.599182  139928 bfc_allocator.cc:1105] InUse at 70b460700 of size 256 next 229
I0000 00:00:1779305965.599185  139928 bfc_allocator.cc:1105] InUse at 70b460800 of size 256 next 227
I0000 00:00:1779305965.599190  139928 bfc_allocator.cc:1105] InUse at 70b460900 of size 256 next 226
I0000 00:00:1779305965.599193  139928 bfc_allocator.cc:1105] InUse at 70b460a00 of size 256 next 234
I0000 00:00:1779305965.599196  139928 bfc_allocator.cc:1105] InUse at 70b460b00 of size 256 next 244
I0000 00:00:1779305965.599199  139928 bfc_allocator.cc:1105] InUse at 70b460c00 of size 256 next 247
I0000 00:00:1779305965.599203  139928 bfc_allocator.cc:1105] InUse at 70b460d00 of size 256 next 246
I0000 00:00:1779305965.599206  139928 bfc_allocator.cc:1105] InUse at 70b460e00 of size 256 next 250
I0000 00:00:1779305965.599209  139928 bfc_allocator.cc:1105] InUse at 70b460f00 of size 256 next 193
I0000 00:00:1779305965.599212  139928 bfc_allocator.cc:1105] InUse at 70b461000 of size 256 next 256
I0000 00:00:1779305965.599215  139928 bfc_allocator.cc:1105] InUse at 70b461100 of size 256 next 265
I0000 00:00:1779305965.599218  139928 bfc_allocator.cc:1105] InUse at 70b461200 of size 256 next 249
I0000 00:00:1779305965.599222  139928 bfc_allocator.cc:1105] InUse at 70b461300 of size 256 next 289
I0000 00:00:1779305965.599225  139928 bfc_allocator.cc:1105] InUse at 70b461400 of size 256 next 261
I0000 00:00:1779305965.599228  139928 bfc_allocator.cc:1105] InUse at 70b461500 of size 256 next 252
I0000 00:00:1779305965.599231  139928 bfc_allocator.cc:1105] InUse at 70b461600 of size 512 next 257
I0000 00:00:1779305965.599235  139928 bfc_allocator.cc:1105] InUse at 70b461800 of size 256 next 290
I0000 00:00:1779305965.599238  139928 bfc_allocator.cc:1105] InUse at 70b461900 of size 256 next 277
I0000 00:00:1779305965.599241  139928 bfc_allocator.cc:1105] Free  at 70b461a00 of size 768 next 285
I0000 00:00:1779305965.599250  139928 bfc_allocator.cc:1105] InUse at 70b461d00 of size 768 next 220
I0000 00:00:1779305965.599253  139928 bfc_allocator.cc:1105] InUse at 70b462000 of size 256 next 184
I0000 00:00:1779305965.599257  139928 bfc_allocator.cc:1105] InUse at 70b462100 of size 256 next 236
I0000 00:00:1779305965.599260  139928 bfc_allocator.cc:1105] InUse at 70b462200 of size 256 next 231
I0000 00:00:1779305965.599263  139928 bfc_allocator.cc:1105] InUse at 70b462300 of size 256 next 241
I0000 00:00:1779305965.599266  139928 bfc_allocator.cc:1105] InUse at 70b462400 of size 256 next 222
I0000 00:00:1779305965.599270  139928 bfc_allocator.cc:1105] InUse at 70b462500 of size 256 next 217
I0000 00:00:1779305965.599273  139928 bfc_allocator.cc:1105] InUse at 70b462600 of size 256 next 216
I0000 00:00:1779305965.599276  139928 bfc_allocator.cc:1105] InUse at 70b462700 of size 256 next 210
I0000 00:00:1779305965.599279  139928 bfc_allocator.cc:1105] InUse at 70b462800 of size 256 next 215
I0000 00:00:1779305965.599282  139928 bfc_allocator.cc:1105] InUse at 70b462900 of size 512 next 242
I0000 00:00:1779305965.599285  139928 bfc_allocator.cc:1105] InUse at 70b462b00 of size 512 next 203
I0000 00:00:1779305965.599289  139928 bfc_allocator.cc:1105] InUse at 70b462d00 of size 512 next 213
I0000 00:00:1779305965.599292  139928 bfc_allocator.cc:1105] InUse at 70b462f00 of size 768 next 58
I0000 00:00:1779305965.599295  139928 bfc_allocator.cc:1105] InUse at 70b463200 of size 256 next 154
I0000 00:00:1779305965.599374  139928 bfc_allocator.cc:1105] InUse at 70b463300 of size 256 next 52
I0000 00:00:1779305965.599384  139928 bfc_allocator.cc:1105] InUse at 70b463400 of size 512 next 53
I0000 00:00:1779305965.599387  139928 bfc_allocator.cc:1105] InUse at 70b463600 of size 512 next 51
I0000 00:00:1779305965.599391  139928 bfc_allocator.cc:1105] InUse at 70b463800 of size 512 next 167
I0000 00:00:1779305965.599395  139928 bfc_allocator.cc:1105] InUse at 70b463a00 of size 512 next 50
I0000 00:00:1779305965.599399  139928 bfc_allocator.cc:1105] InUse at 70b463c00 of size 74240 next 8
I0000 00:00:1779305965.599603  139928 bfc_allocator.cc:1105] InUse at 70b475e00 of size 256 next 9
I0000 00:00:1779305965.599613  139928 bfc_allocator.cc:1105] InUse at 70b475f00 of size 256 next 10
I0000 00:00:1779305965.599622  139928 bfc_allocator.cc:1105] InUse at 70b476000 of size 256 next 12
I0000 00:00:1779305965.599629  139928 bfc_allocator.cc:1105] InUse at 70b476100 of size 256 next 13
I0000 00:00:1779305965.599634  139928 bfc_allocator.cc:1105] InUse at 70b476200 of size 256 next 70
I0000 00:00:1779305965.599637  139928 bfc_allocator.cc:1105] InUse at 70b476300 of size 256 next 14
I0000 00:00:1779305965.599641  139928 bfc_allocator.cc:1105] InUse at 70b476400 of size 256 next 17
I0000 00:00:1779305965.599644  139928 bfc_allocator.cc:1105] InUse at 70b476500 of size 256 next 11
I0000 00:00:1779305965.599718  139928 bfc_allocator.cc:1105] InUse at 70b476600 of size 256 next 21
I0000 00:00:1779305965.599728  139928 bfc_allocator.cc:1105] InUse at 70b476700 of size 256 next 22
I0000 00:00:1779305965.599736  139928 bfc_allocator.cc:1105] InUse at 70b476800 of size 256 next 25
I0000 00:00:1779305965.599742  139928 bfc_allocator.cc:1105] InUse at 70b476900 of size 256 next 66
I0000 00:00:1779305965.599746  139928 bfc_allocator.cc:1105] InUse at 70b476a00 of size 256 next 27
I0000 00:00:1779305965.599749  139928 bfc_allocator.cc:1105] InUse at 70b476b00 of size 256 next 38
I0000 00:00:1779305965.599752  139928 bfc_allocator.cc:1105] InUse at 70b476c00 of size 256 next 29
I0000 00:00:1779305965.599755  139928 bfc_allocator.cc:1105] InUse at 70b476d00 of size 256 next 30
I0000 00:00:1779305965.599759  139928 bfc_allocator.cc:1105] InUse at 70b476e00 of size 256 next 31
I0000 00:00:1779305965.599762  139928 bfc_allocator.cc:1105] InUse at 70b476f00 of size 256 next 32
I0000 00:00:1779305965.599765  139928 bfc_allocator.cc:1105] InUse at 70b477000 of size 256 next 33
I0000 00:00:1779305965.599768  139928 bfc_allocator.cc:1105] InUse at 70b477100 of size 256 next 34
I0000 00:00:1779305965.599772  139928 bfc_allocator.cc:1105] InUse at 70b477200 of size 256 next 35
I0000 00:00:1779305965.599775  139928 bfc_allocator.cc:1105] InUse at 70b477300 of size 256 next 36
I0000 00:00:1779305965.599778  139928 bfc_allocator.cc:1105] InUse at 70b477400 of size 256 next 124
I0000 00:00:1779305965.599781  139928 bfc_allocator.cc:1105] InUse at 70b477500 of size 256 next 20
I0000 00:00:1779305965.599784  139928 bfc_allocator.cc:1105] InUse at 70b477600 of size 256 next 81
I0000 00:00:1779305965.599788  139928 bfc_allocator.cc:1105] InUse at 70b477700 of size 256 next 104
I0000 00:00:1779305965.599791  139928 bfc_allocator.cc:1105] InUse at 70b477800 of size 256 next 103
I0000 00:00:1779305965.599794  139928 bfc_allocator.cc:1105] InUse at 70b477900 of size 256 next 97
I0000 00:00:1779305965.599797  139928 bfc_allocator.cc:1105] InUse at 70b477a00 of size 256 next 98
I0000 00:00:1779305965.599801  139928 bfc_allocator.cc:1105] InUse at 70b477b00 of size 256 next 83
I0000 00:00:1779305965.599804  139928 bfc_allocator.cc:1105] InUse at 70b477c00 of size 256 next 80
I0000 00:00:1779305965.599807  139928 bfc_allocator.cc:1105] InUse at 70b477d00 of size 256 next 85
I0000 00:00:1779305965.599810  139928 bfc_allocator.cc:1105] InUse at 70b477e00 of size 256 next 135
I0000 00:00:1779305965.599813  139928 bfc_allocator.cc:1105] InUse at 70b477f00 of size 256 next 90
I0000 00:00:1779305965.599817  139928 bfc_allocator.cc:1105] InUse at 70b478000 of size 256 next 127
I0000 00:00:1779305965.599820  139928 bfc_allocator.cc:1105] InUse at 70b478100 of size 256 next 24
I0000 00:00:1779305965.599823  139928 bfc_allocator.cc:1105] InUse at 70b478200 of size 256 next 129
I0000 00:00:1779305965.599826  139928 bfc_allocator.cc:1105] InUse at 70b478300 of size 256 next 18

Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_clf_frozen_confusion.png
  test_acc=0.6701  macro_f1=0.1302  coverage=58.9%

--- Reuters finetune | run_id=cbow_30k_win2_emb300_ep5_vocab30000 | emb_dim=300 ---
Epoch 1/10

I0000 00:00:1779305998.969928  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26568835__.31

62/64 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3805 - loss: 2.7283

I0000 00:00:1779306001.691289  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26568835__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 6s 51ms/step - accuracy: 0.4613 - loss: 2.3181 - val_accuracy: 0.5172 - val_loss: 1.8229
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5645 - loss: 1.7480 - val_accuracy: 0.6007 - val_loss: 1.5973
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6245 - loss: 1.5041 - val_accuracy: 0.6752 - val_loss: 1.4232
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6942 - loss: 1.2565 - val_accuracy: 0.7086 - val_loss: 1.2458
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7433 - loss: 1.0451 - val_accuracy: 0.7330 - val_loss: 1.1870
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7798 - loss: 0.8771 - val_accuracy: 0.7419 - val_loss: 1.1710
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8054 - loss: 0.7585 - val_accuracy: 0.7486 - val_loss: 1.2088
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8248 - loss: 0.6806 - val_accuracy: 0.7319 - val_loss: 1.2669
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 6.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_30k_win2_emb300_ep5_vocab30000_clf_finetune_confusion.png
  test_acc=0.7346  macro_f1=0.1938  coverage=58.9%

--- Reuters frozen | run_id=cbow_100k_win2_emb100_ep5_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306014.029329  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26575088__.29

63/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3777 - loss: 2.7058

I0000 00:00:1779306015.723820  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26575088__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.4477 - loss: 2.3850 - val_accuracy: 0.4972 - val_loss: 1.9554
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5215 - loss: 1.9239 - val_accuracy: 0.5517 - val_loss: 1.7822
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5672 - loss: 1.7412 - val_accuracy: 0.5784 - val_loss: 1.6951
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5914 - loss: 1.6288 - val_accuracy: 0.5951 - val_loss: 1.6371
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6114 - loss: 1.5454 - val_accuracy: 0.6051 - val_loss: 1.6302
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6326 - loss: 1.4702 - val_accuracy: 0.6151 - val_loss: 1.6063
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 1.3949 - val_accuracy: 0.6285 - val_loss: 1.5200
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6709 - loss: 1.3110 - val_accuracy: 0.6285 - val_loss: 1.5267
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6931 - loss: 1.2265 - val_accuracy: 0.6529 - val_loss: 1.4744
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7109 - loss: 1.1535 - val_accuracy: 0.6707 - val_loss: 1.4497
Restoring model weights from the end of the best epoch: 10.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb100_ep5_vocab50000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb100_ep5_vocab50000_clf_frozen_confusion.png
  test_acc=0.6585  macro_f1=0.1099  coverage=69.7%

--- Reuters finetune | run_id=cbow_100k_win2_emb100_ep5_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306026.334310  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26582121__.31

61/64 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3684 - loss: 2.7232

I0000 00:00:1779306028.416035  139929 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26582121__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.4535 - loss: 2.3322 - val_accuracy: 0.5195 - val_loss: 1.8338
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5551 - loss: 1.7666 - val_accuracy: 0.5951 - val_loss: 1.6634
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6082 - loss: 1.5715 - val_accuracy: 0.6218 - val_loss: 1.5509
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6477 - loss: 1.4136 - val_accuracy: 0.6563 - val_loss: 1.4251
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6973 - loss: 1.2256 - val_accuracy: 0.6919 - val_loss: 1.3225
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7397 - loss: 1.0471 - val_accuracy: 0.7030 - val_loss: 1.2723
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7699 - loss: 0.9067 - val_accuracy: 0.7075 - val_loss: 1.2524
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7899 - loss: 0.8077 - val_accuracy: 0.7119 - val_loss: 1.2864
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7988 - loss: 0.7510 - val_accuracy: 0.7241 - val_loss: 1.3357
Epoch 9: early stopping
Restoring model weights from the end of the best epoch: 7.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb100_ep5_vocab50000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb100_ep5_vocab50000_clf_finetune_confusion.png
  test_acc=0.7155  macro_f1=0.1514  coverage=69.7%

--- Reuters frozen | run_id=cbow_100k_win5_emb100_ep5_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306038.314753  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26588710__.29

54/64 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3514 - loss: 2.8531

I0000 00:00:1779306040.383174  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26588710__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.4380 - loss: 2.4206 - val_accuracy: 0.5039 - val_loss: 1.9443
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5247 - loss: 1.9143 - val_accuracy: 0.5640 - val_loss: 1.7541
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5650 - loss: 1.7494 - val_accuracy: 0.5840 - val_loss: 1.6925
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5903 - loss: 1.6539 - val_accuracy: 0.5962 - val_loss: 1.6538
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6107 - loss: 1.5663 - val_accuracy: 0.6196 - val_loss: 1.5867
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6246 - loss: 1.4964 - val_accuracy: 0.6340 - val_loss: 1.5187
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 1.4138 - val_accuracy: 0.6474 - val_loss: 1.4633
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6686 - loss: 1.3272 - val_accuracy: 0.6541 - val_loss: 1.4287
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6844 - loss: 1.2544 - val_accuracy: 0.6563 - val_loss: 1.4153
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7010 - loss: 1.1878 - val_accuracy: 0.6529 - val_loss: 1.4376
Restoring model weights from the end of the best epoch: 9.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep5_vocab50000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep5_vocab50000_clf_frozen_confusion.png
  test_acc=0.6509  macro_f1=0.1026  coverage=69.7%

--- Reuters finetune | run_id=cbow_100k_win5_emb100_ep5_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306048.760547  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26595743__.31

60/64 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3714 - loss: 2.6894

I0000 00:00:1779306050.831220  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26595743__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.4507 - loss: 2.3150 - val_accuracy: 0.5206 - val_loss: 1.8409
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5581 - loss: 1.7750 - val_accuracy: 0.5873 - val_loss: 1.6461
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6018 - loss: 1.5821 - val_accuracy: 0.6118 - val_loss: 1.5401
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6452 - loss: 1.4059 - val_accuracy: 0.6741 - val_loss: 1.4219
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6985 - loss: 1.2165 - val_accuracy: 0.6941 - val_loss: 1.3296
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7414 - loss: 1.0369 - val_accuracy: 0.7052 - val_loss: 1.2932
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7711 - loss: 0.9158 - val_accuracy: 0.7030 - val_loss: 1.3124
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7909 - loss: 0.8108 - val_accuracy: 0.7130 - val_loss: 1.3022
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 6.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep5_vocab50000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep5_vocab50000_clf_finetune_confusion.png
  test_acc=0.7039  macro_f1=0.1360  coverage=69.7%

--- Reuters frozen | run_id=cbow_100k_win2_emb300_ep5_vocab50000 | emb_dim=300 ---
Epoch 1/10

I0000 00:00:1779306060.474587  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26601996__.29

59/64 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3730 - loss: 2.7003

I0000 00:00:1779306062.528767  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26601996__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.4615 - loss: 2.3140 - val_accuracy: 0.5306 - val_loss: 1.8399
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5531 - loss: 1.8073 - val_accuracy: 0.5806 - val_loss: 1.6826
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5961 - loss: 1.6344 - val_accuracy: 0.5984 - val_loss: 1.6030
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6426 - loss: 1.4948 - val_accuracy: 0.6529 - val_loss: 1.4895
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6676 - loss: 1.3581 - val_accuracy: 0.6808 - val_loss: 1.4149
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7062 - loss: 1.2335 - val_accuracy: 0.6874 - val_loss: 1.3789
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7226 - loss: 1.1366 - val_accuracy: 0.6986 - val_loss: 1.4080
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7395 - loss: 1.0510 - val_accuracy: 0.6852 - val_loss: 1.4669
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 6.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb300_ep5_vocab50000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb300_ep5_vocab50000_clf_frozen_confusion.png
  test_acc=0.6736  macro_f1=0.1127  coverage=69.7%

--- Reuters finetune | run_id=cbow_100k_win2_emb300_ep5_vocab50000 | emb_dim=300 ---
Epoch 1/10

I0000 00:00:1779306071.408828  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26608339__.31

62/64 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3703 - loss: 2.6658

I0000 00:00:1779306073.846092  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26608339__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.4586 - loss: 2.2587 - val_accuracy: 0.5273 - val_loss: 1.8040
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.5742 - loss: 1.7068 - val_accuracy: 0.6018 - val_loss: 1.6277
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6389 - loss: 1.4878 - val_accuracy: 0.6696 - val_loss: 1.4481
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7004 - loss: 1.2201 - val_accuracy: 0.7197 - val_loss: 1.2717
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7458 - loss: 1.0139 - val_accuracy: 0.7297 - val_loss: 1.2015
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7850 - loss: 0.8550 - val_accuracy: 0.7453 - val_loss: 1.2476
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8044 - loss: 0.7514 - val_accuracy: 0.7430 - val_loss: 1.1913
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.8267 - loss: 0.6722 - val_accuracy: 0.7364 - val_loss: 1.1695
Restoring model weights from the end of the best epoch: 8.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb300_ep5_vocab50000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win2_emb300_ep5_vocab50000_clf_finetune_confusion.png
  test_acc=0.7502  macro_f1=0.2243  coverage=69.7%

--- Reuters frozen | run_id=cbow_100k_win5_emb100_ep10_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306086.254976  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26614610__.29

61/64 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3718 - loss: 2.6731

I0000 00:00:1779306088.110910  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26614610__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.4511 - loss: 2.3288 - val_accuracy: 0.5095 - val_loss: 1.9140
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5262 - loss: 1.8800 - val_accuracy: 0.5539 - val_loss: 1.7760
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5602 - loss: 1.7417 - val_accuracy: 0.5862 - val_loss: 1.6982
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5905 - loss: 1.6430 - val_accuracy: 0.5940 - val_loss: 1.6280
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6141 - loss: 1.5608 - val_accuracy: 0.6207 - val_loss: 1.5798
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6349 - loss: 1.4719 - val_accuracy: 0.6418 - val_loss: 1.5075
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6621 - loss: 1.3848 - val_accuracy: 0.6463 - val_loss: 1.4684
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6767 - loss: 1.3009 - val_accuracy: 0.6674 - val_loss: 1.4358
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6948 - loss: 1.2304 - val_accuracy: 0.6785 - val_loss: 1.3842
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7077 - loss: 1.1568 - val_accuracy: 0.6863 - val_loss: 1.4252
Restoring model weights from the end of the best epoch: 9.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep10_vocab50000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep10_vocab50000_clf_frozen_confusion.png
  test_acc=0.6687  macro_f1=0.1112  coverage=69.7%

--- Reuters finetune | run_id=cbow_100k_win5_emb100_ep10_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306097.679710  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26621643__.31

63/64 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3709 - loss: 2.7052

I0000 00:00:1779306099.818902  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26621643__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.4518 - loss: 2.3184 - val_accuracy: 0.5139 - val_loss: 1.8799
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5489 - loss: 1.7995 - val_accuracy: 0.5840 - val_loss: 1.6775
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6047 - loss: 1.5904 - val_accuracy: 0.6129 - val_loss: 1.5585
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6515 - loss: 1.4314 - val_accuracy: 0.6318 - val_loss: 1.5057
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6903 - loss: 1.2710 - val_accuracy: 0.6730 - val_loss: 1.3731
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7310 - loss: 1.0913 - val_accuracy: 0.6930 - val_loss: 1.2969
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7557 - loss: 0.9734 - val_accuracy: 0.6986 - val_loss: 1.2885
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7797 - loss: 0.8649 - val_accuracy: 0.6897 - val_loss: 1.3168
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7990 - loss: 0.7931 - val_accuracy: 0.7175 - val_loss: 1.3342
Epoch 9: early stopping
Restoring model weights from the end of the best epoch: 7.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep10_vocab50000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win5_emb100_ep10_vocab50000_clf_finetune_confusion.png
  test_acc=0.7044  macro_f1=0.1385  coverage=69.7%

--- Reuters frozen | run_id=cbow_100k_win8_emb100_ep5_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306109.945545  139931 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26628232__.29

60/64 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3675 - loss: 2.7123

I0000 00:00:1779306112.121113  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26628232__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - accuracy: 0.4480 - loss: 2.3623 - val_accuracy: 0.5161 - val_loss: 1.9531
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5249 - loss: 1.9213 - val_accuracy: 0.5628 - val_loss: 1.7870
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5556 - loss: 1.7642 - val_accuracy: 0.5773 - val_loss: 1.7133
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5842 - loss: 1.6678 - val_accuracy: 0.5940 - val_loss: 1.6624
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6023 - loss: 1.5838 - val_accuracy: 0.6040 - val_loss: 1.6286
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6270 - loss: 1.5088 - val_accuracy: 0.6185 - val_loss: 1.5861
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6409 - loss: 1.4212 - val_accuracy: 0.6274 - val_loss: 1.5463
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6564 - loss: 1.3567 - val_accuracy: 0.6407 - val_loss: 1.5168
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6775 - loss: 1.2924 - val_accuracy: 0.6474 - val_loss: 1.5254
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6926 - loss: 1.2227 - val_accuracy: 0.6518 - val_loss: 1.5187
Epoch 10: early stopping
Restoring model weights from the end of the best epoch: 8.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win8_emb100_ep5_vocab50000_clf_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win8_emb100_ep5_vocab50000_clf_frozen_confusion.png
  test_acc=0.6327  macro_f1=0.0898  coverage=69.7%

--- Reuters finetune | run_id=cbow_100k_win8_emb100_ep5_vocab50000 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306121.914643  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26635247__.31

61/64 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3732 - loss: 2.7488

I0000 00:00:1779306124.121048  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26635247__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - accuracy: 0.4570 - loss: 2.3520 - val_accuracy: 0.5128 - val_loss: 1.9038
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5421 - loss: 1.8293 - val_accuracy: 0.5717 - val_loss: 1.7275
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5927 - loss: 1.6335 - val_accuracy: 0.5973 - val_loss: 1.6068
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6259 - loss: 1.4922 - val_accuracy: 0.6385 - val_loss: 1.5082
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6835 - loss: 1.2966 - val_accuracy: 0.6885 - val_loss: 1.3342
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7234 - loss: 1.1238 - val_accuracy: 0.7052 - val_loss: 1.2743
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7471 - loss: 0.9809 - val_accuracy: 0.7197 - val_loss: 1.2483
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7748 - loss: 0.8632 - val_accuracy: 0.7264 - val_loss: 1.2063
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7858 - loss: 0.8067 - val_accuracy: 0.7297 - val_loss: 1.2443
Epoch 10/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8096 - loss: 0.7314 - val_accuracy: 0.7341 - val_loss: 1.1938
Restoring model weights from the end of the best epoch: 10.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win8_emb100_ep5_vocab50000_clf_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/cbow_100k_win8_emb100_ep5_vocab50000_clf_finetune_confusion.png
  test_acc=0.7297  macro_f1=0.2013  coverage=69.7%

=== Reuters results ===

,run_id,setup,embedding_dim,reuters_vocab_size,coverage_pct,test_loss,test_accuracy,test_macro_f1,train_time_s
0,baseline_random,baseline,100,20000,0.00,1.380337,0.675423,0.111392,46.24
1,cbow_30k_win2_emb100_ep5_vocab30000,frozen,100,20000,58.90,1.476238,0.650935,0.100247,8.52
2,cbow_30k_win2_emb100_ep5_vocab30000,finetune,100,20000,58.90,1.287970,0.695904,0.116998,9.68
3,cbow_30k_win5_emb100_ep5_vocab30000,frozen,100,20000,58.90,1.501186,0.625557,0.086002,8.37
4,cbow_30k_win5_emb100_ep5_vocab30000,finetune,100,20000,58.90,1.176466,0.748887,0.231991,11.17
5,cbow_30k_win2_emb300_ep5_vocab30000,frozen,300,20000,58.90,1.398689,0.670080,0.130235,91.57
6,cbow_30k_win2_emb300_ep5_vocab30000,finetune,300,20000,58.90,1.149938,0.734639,0.193830,12.97
7,cbow_100k_win2_emb100_ep5_vocab50000,frozen,100,20000,69.67,1.473702,0.658504,0.109912,9.04
8,cbow_100k_win2_emb100_ep5_vocab50000,finetune,100,20000,69.67,1.235080,0.715494,0.151416,9.89
9,cbow_100k_win5_emb100_ep5_vocab50000,frozen,100,20000,69.67,1.451453,0.650935,0.102582,8.40
10,cbow_100k_win5_emb100_ep5_vocab50000,finetune,100,20000,69.67,1.290830,0.703918,0.136043,9.61
11,cbow_100k_win2_emb300_ep5_vocab50000,frozen,300,20000,69.67,1.395064,0.673642,0.112681,8.68
12,cbow_100k_win2_emb300_ep5_vocab50000,finetune,300,20000,69.67,1.165155,0.750223,0.224347,12.65
13,cbow_100k_win5_emb100_ep10_vocab50000,frozen,100,20000,69.67,1.414992,0.668744,0.111165,8.58
14,cbow_100k_win5_emb100_ep10_vocab50000,finetune,100,20000,69.67,1.273242,0.704363,0.138492,10.13
15,cbow_100k_win8_emb100_ep5_vocab50000,frozen,100,20000,69.67,1.501016,0.632680,0.089797,9.75
16,cbow_100k_win8_emb100_ep5_vocab50000,finetune,100,20000,69.67,1.220763,0.729742,0.201260,11.67

## 9.  Public Embeddings Comparison

Pre-trained **GloVe** (`glove-wiki-gigaword-100`, 100-d) mapped into the Reuters vocabulary.
Trains **frozen** and **fine-tune** classifiers; rows are appended to `reuters_results.csv`
with `run_id=public_glove-wiki-gigaword-100` and `setup=public_glove_*`.

In [11]:
import gensim.downloader as api

PUBLIC_EMBEDDING_NAME = "glove-wiki-gigaword-100"
PUBLIC_RUN_ID = f"public_{PUBLIC_EMBEDDING_NAME}"


def build_public_embedding_matrix(
    kv,
    reuters_index_to_word: dict[int, str],
    reuters_vocab_size: int = REUTERS_VOCAB_SIZE,
) -> tuple[np.ndarray, float]:
    """Map GloVe (or other KeyedVectors) into Reuters embedding matrix."""
    emb_dim = kv.vector_size
    matrix = np.random.normal(0, 0.1, (reuters_vocab_size, emb_dim)).astype(np.float32)
    found, total = 0, 0
    for rid in range(3, reuters_vocab_size):
        total += 1
        rw = reuters_index_to_word.get(rid, "")
        if not rw:
            continue
        cw = clean_sentence(rw)
        if cw in kv:
            matrix[rid] = kv[cw]
            found += 1
    coverage = 100.0 * found / total if total else 0.0
    return matrix, coverage


def ensure_reuters_data_loaded() -> None:
    """§8 must be run first; load Reuters arrays if this section runs standalone."""
    required = ("X_rt_tr", "X_rt_val", "X_rt_test", "y_rt_train_cat", "y_rt_val_cat", "y_rt_test_cat", "y_rt_test", "reuters_index_to_word")
    missing = [n for n in required if n not in globals()]
    if missing:
        raise RuntimeError(
            f"Run §8 Reuters Classification first (missing: {missing})."
        )


ensure_reuters_data_loaded()

print(f"Loading public embeddings: {PUBLIC_EMBEDDING_NAME} ...")
glove_kv = api.load(PUBLIC_EMBEDDING_NAME)
print(f"  vectors={glove_kv.vectors.shape[0]:,}  dim={glove_kv.vector_size}")

glove_matrix, glove_coverage = build_public_embedding_matrix(glove_kv, reuters_index_to_word)
print(f"  Reuters coverage: {glove_coverage:.1f}%")

public_rows: list[dict] = []
for setup_suffix, trainable in [("frozen", False), ("finetune", True)]:
    setup = f"public_glove_{setup_suffix}"
    row = train_and_evaluate_reuters(
        PUBLIC_RUN_ID,
        setup,
        glove_matrix.copy(),
        trainable,
        coverage_pct=glove_coverage,
        skip_if_exists=True,
    )
    if row:
        public_rows.append(row)

reuters_df_public = pd.read_csv(REUTERS_RESULTS_PATH)
cbow_finetune = reuters_df_public[
    reuters_df_public["setup"].eq("finetune") & ~reuters_df_public["run_id"].str.startswith("public_")
]
best_cbow = cbow_finetune.loc[cbow_finetune["test_accuracy"].idxmax()]
public_finetune = reuters_df_public[
    (reuters_df_public["run_id"] == PUBLIC_RUN_ID)
    & reuters_df_public["setup"].str.startswith("public_glove_finetune")
]
if len(public_finetune):
    pub_acc = float(public_finetune["test_accuracy"].iloc[-1])
else:
    pub_acc = float("nan")

print("\n=== Public vs best CBOW (fine-tune) ===")
print(f"  Best CBOW:  {best_cbow['run_id']}  acc={best_cbow['test_accuracy']:.4f}")
print(f"  GloVe:      {PUBLIC_RUN_ID}  acc={pub_acc:.4f}")
if not np.isnan(pub_acc):
    delta = pub_acc - best_cbow["test_accuracy"]
    print(f"  Delta (GloVe − best CBOW): {delta:+.4f}")

Loading public embeddings: glove-wiki-gigaword-100 ...
  vectors=400,000  dim=100
  Reuters coverage: 89.0%

--- Reuters public_glove_frozen | run_id=public_glove-wiki-gigaword-100 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306153.094395  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26642190__.29

58/64 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3974 - loss: 2.5966

I0000 00:00:1779306154.959389  139932 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26642190__.29

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.4825 - loss: 2.1774 - val_accuracy: 0.5884 - val_loss: 1.6810
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.6071 - loss: 1.6389 - val_accuracy: 0.6474 - val_loss: 1.4674
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6687 - loss: 1.4138 - val_accuracy: 0.6908 - val_loss: 1.3122
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6995 - loss: 1.2484 - val_accuracy: 0.7186 - val_loss: 1.2116
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7245 - loss: 1.1374 - val_accuracy: 0.7319 - val_loss: 1.1311
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7401 - loss: 1.0538 - val_accuracy: 0.7375 - val_loss: 1.1102
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7605 - loss: 0.9544 - val_accuracy: 0.7531 - val_loss: 1.1133
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7741 - loss: 0.8862 - val_accuracy: 0.7330 - val_loss: 1.1548
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 6.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/public_glove-wiki-gigaword-100_clf_public_glove_frozen_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/public_glove-wiki-gigaword-100_clf_public_glove_frozen_confusion.png
  test_acc=0.7204  macro_f1=0.1574  coverage=89.0%

--- Reuters public_glove_finetune | run_id=public_glove-wiki-gigaword-100 | emb_dim=100 ---
Epoch 1/10

I0000 00:00:1779306163.912205  139928 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26648533__.31

60/64 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3576 - loss: 2.7424

I0000 00:00:1779306165.943236  139930 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26648533__.31

64/64 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.4591 - loss: 2.2955 - val_accuracy: 0.5673 - val_loss: 1.7349
Epoch 2/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5883 - loss: 1.6954 - val_accuracy: 0.6518 - val_loss: 1.5138
Epoch 3/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6540 - loss: 1.4566 - val_accuracy: 0.7008 - val_loss: 1.3195
Epoch 4/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7007 - loss: 1.2657 - val_accuracy: 0.7175 - val_loss: 1.2242
Epoch 5/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7336 - loss: 1.1168 - val_accuracy: 0.7319 - val_loss: 1.1908
Epoch 6/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7539 - loss: 1.0039 - val_accuracy: 0.7519 - val_loss: 1.1064
Epoch 7/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7798 - loss: 0.8942 - val_accuracy: 0.7608 - val_loss: 1.0313
Epoch 8/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7996 - loss: 0.7925 - val_accuracy: 0.7653 - val_loss: 1.0551
Epoch 9/10
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8186 - loss: 0.7047 - val_accuracy: 0.7653 - val_loss: 1.1162
Epoch 9: early stopping
Restoring model weights from the end of the best epoch: 7.
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/public_glove-wiki-gigaword-100_clf_public_glove_finetune_curves.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/public_glove-wiki-gigaword-100_clf_public_glove_finetune_confusion.png
  test_acc=0.7529  macro_f1=0.1936  coverage=89.0%

=== Public vs best CBOW (fine-tune) ===
  Best CBOW:  cbow_100k_win2_emb300_ep5_vocab50000  acc=0.7502
  GloVe:      public_glove-wiki-gigaword-100  acc=0.7529
  Delta (GloVe − best CBOW): +0.0027

## 10. Results Aggregation

Load `experiments.csv`, `reuters_results.csv`, and `corpus_stats.csv`; render summary
tables and parameter-effect plots (saved under `artifacts/plots/`).

In [12]:
EXPERIMENTS_CSV_PATH = DIR_TABLES / "experiments.csv"
REUTERS_RESULTS_PATH = DIR_TABLES / "reuters_results.csv"
CORPUS_STATS_PATH = DIR_TABLES / "corpus_stats.csv"

HAND_PICKED_WORDS = ["friday", "september", "monday", "water", "president"]


def load_deduped_experiments() -> pd.DataFrame:
    if not EXPERIMENTS_CSV_PATH.exists():
        raise FileNotFoundError(f"Missing {EXPERIMENTS_CSV_PATH} — run §9 Experiment Runner first.")
    return pd.read_csv(EXPERIMENTS_CSV_PATH).drop_duplicates(subset=["run_id"], keep="last")


def load_reuters_results() -> pd.DataFrame:
    if not REUTERS_RESULTS_PATH.exists():
        raise FileNotFoundError(f"Missing {REUTERS_RESULTS_PATH} — run §8 Reuters Classification first.")
    return pd.read_csv(REUTERS_RESULTS_PATH)


def merge_experiments_reuters(exp_df: pd.DataFrame, rt_df: pd.DataFrame) -> pd.DataFrame:
    cbow_rt = rt_df[
        rt_df["run_id"].str.startswith("cbow_") & rt_df["setup"].isin(["frozen", "finetune"])
    ].copy()
    return cbow_rt.merge(exp_df, on="run_id", how="left", suffixes=("", "_exp"))


def plot_reuters_accuracy_bars(rt_df: pd.DataFrame) -> Path:
    plot_df = rt_df.copy()
    plot_df["label"] = plot_df["run_id"].str.replace("cbow_", "", regex=False).str[:28]
    plot_df.loc[plot_df["run_id"] == "baseline_random", "label"] = "baseline"
    plot_df.loc[plot_df["run_id"].str.startswith("public_"), "label"] = plot_df["run_id"].str.replace("public_", "pub:", regex=False)

    order = (
        plot_df.groupby("label")["test_accuracy"]
        .max()
        .sort_values(ascending=False)
        .index.tolist()
    )
    plt.figure(figsize=(14, 6))
    hue_order = [s for s in ["baseline", "frozen", "finetune", "public_glove_frozen", "public_glove_finetune"] if s in plot_df["setup"].unique()]
    sns.barplot(
        data=plot_df,
        x="label",
        y="test_accuracy",
        hue="setup",
        order=order,
        hue_order=hue_order,
    )
    plt.xticks(rotation=60, ha="right")
    plt.ylabel("Reuters test accuracy")
    plt.xlabel("Run")
    plt.legend(title="setup", bbox_to_anchor=(1.02, 1), loc="upper left")
    plt.title("Reuters test accuracy by embedding source and setup")
    return save_fig("reuters_test_accuracy_all_setups")


def plot_param_effect(
    merged: pd.DataFrame,
    param: str,
    title: str,
    filename: str,
    *,
    setup: str = "finetune",
    filters: dict | None = None,
) -> Path | None:
    df = merged[merged["setup"] == setup].copy()
    if filters:
        for col, val in filters.items():
            df = df[df[col] == val]
    if df[param].nunique() < 2:
        print(f"Skip {filename}: need ≥2 values for {param} (n={df[param].nunique()})")
        return None
    agg = df.groupby(param)["test_accuracy"].agg(["mean", "std", "count"]).reset_index()
    agg.columns = [param, "mean_acc", "std_acc", "n"]
    plt.figure(figsize=(7, 4))
    yerr = agg["std_acc"].fillna(0)
    plt.errorbar(agg[param], agg["mean_acc"], yerr=yerr, marker="o", capsize=4)
    for _, r in agg.iterrows():
        plt.annotate(f"n={int(r['n'])}", (r[param], r["mean_acc"]), textcoords="offset points", xytext=(0, 6), ha="center", fontsize=8)
    plt.xlabel(param)
    plt.ylabel(f"Reuters test accuracy ({setup})")
    plt.title(title)
    return save_fig(filename)


def plot_frozen_finetune_delta(merged: pd.DataFrame) -> Path:
    pivot = merged.pivot_table(index="run_id", columns="setup", values="test_accuracy", aggfunc="first")
    if not {"frozen", "finetune"}.issubset(pivot.columns):
        print("Skip frozen_vs_finetune_delta: missing frozen/finetune rows")
        return None
    pivot["delta"] = pivot["finetune"] - pivot["frozen"]
    pivot = pivot.sort_values("delta", ascending=True)
    plt.figure(figsize=(10, max(4, 0.35 * len(pivot))))
    colors = ["#c44e52" if d < 0 else "#55a868" for d in pivot["delta"]]
    plt.barh(pivot.index.str.replace("cbow_", "", regex=False), pivot["delta"], color=colors)
    plt.axvline(0, color="black", linewidth=0.8)
    plt.xlabel("Δ test accuracy (fine-tune − frozen)")
    plt.title("Reuters: benefit of fine-tuning pretrained embeddings")
    return save_fig("reuters_frozen_vs_finetune_delta")


def show_cosine_tables_for_run(run_id: str, words: list[str]) -> None:
    cosine_path = DIR_TABLES / f"cosine_{run_id}.csv"
    if not cosine_path.exists():
        print(f"No cosine table: {cosine_path}")
        return
    cdf = pd.read_csv(cosine_path)
    for w in words:
        sub = cdf[(cdf["target_word"] == w)].sort_values("rank").head(10)
        if sub.empty:
            print(f"  [{w}] not in cosine table for {run_id}")
            continue
        print(f"\n### Top-10 neighbors: {w} ({run_id})")
        display(sub[["rank", "neighbor", "cosine"]])


# --- Load tables ---
exp_df = load_deduped_experiments()
rt_df = load_reuters_results()
merged_rt = merge_experiments_reuters(exp_df, rt_df)

print("=== Corpus statistics ===")
if CORPUS_STATS_PATH.exists():
    display(pd.read_csv(CORPUS_STATS_PATH))
else:
    print(f"(missing {CORPUS_STATS_PATH})")

print("\n=== CBOW experiments (deduplicated) ===")
display(exp_df.sort_values(["corpus", "window_size", "embedding_dim", "epochs"]))

print("\n=== Reuters classification results ===")
display(rt_df.sort_values(["run_id", "setup"]))

# Coverage per CBOW run (from frozen row — same matrix as finetune)
coverage_df = (
    rt_df[rt_df["run_id"].str.startswith("cbow_") & rt_df["setup"].eq("frozen")]
    .merge(exp_df[["run_id", "corpus", "vocab_size"]], on="run_id", how="left")
    [["run_id", "corpus", "vocab_size", "coverage_pct", "embedding_dim"]]
    .sort_values("coverage_pct", ascending=False)
    .rename(columns={"vocab_size": "cbow_vocab_size"})
)
print("\n=== Reuters coverage by CBOW vocabulary ===")
display(coverage_df)
coverage_df.to_csv(DIR_TABLES / "reuters_coverage_by_cbow.csv", index=False)
print(f"Saved {DIR_TABLES / 'reuters_coverage_by_cbow.csv'}")

# Best runs summary
cbow_ft = rt_df[rt_df["setup"].eq("finetune") & rt_df["run_id"].str.startswith("cbow_")]
best_cbow_row = cbow_ft.loc[cbow_ft["test_accuracy"].idxmax()]
public_ft = rt_df[rt_df["setup"].str.startswith("public_glove_finetune")]
print("\n=== Best fine-tuned Reuters accuracy ===")
display(pd.DataFrame([best_cbow_row]))
if len(public_ft):
    print("\n=== Public GloVe (fine-tune) ===")
    display(public_ft.tail(1))

# Hand-picked cosine tables (best CBOW by val_top1_acc on CBOW task)
best_qual_row = exp_df.loc[exp_df["val_top1_acc"].idxmax()]
print(f"\n=== Cosine neighbors (best CBOW val_top1: {best_qual_row['run_id']}) ===")
show_cosine_tables_for_run(best_qual_row["run_id"], HAND_PICKED_WORDS)

# --- Plots (saved + displayed) ---
plot_reuters_accuracy_bars(rt_df)
plot_frozen_finetune_delta(merged_rt)

plot_param_effect(
    merged_rt,
    "embedding_dim",
    "Effect of embedding dimension (100K, win=2, ep=5)",
    "reuters_effect_embedding_dim",
    filters={"corpus": "100k", "window_size": 2, "epochs": 5},
)
plot_param_effect(
    merged_rt,
    "window_size",
    "Effect of context window (100K, emb=100, ep=5)",
    "reuters_effect_window_size",
    filters={"corpus": "100k", "embedding_dim": 100, "epochs": 5},
)
plot_param_effect(
    merged_rt,
    "corpus",
    "Effect of corpus size (win=2, emb=100, ep=5)",
    "reuters_effect_corpus_size",
    filters={"window_size": 2, "embedding_dim": 100, "epochs": 5},
)
plot_param_effect(
    merged_rt,
    "epochs",
    "Effect of CBOW training epochs (100K, win=5, emb=100)",
    "reuters_effect_epochs",
    filters={"corpus": "100k", "window_size": 5, "embedding_dim": 100},
)

# Public vs best CBOW bar
compare_rows = []
if len(cbow_ft):
    compare_rows.append(
        {
            "source": "best_cbow_finetune",
            "run_id": best_cbow_row["run_id"],
            "test_accuracy": best_cbow_row["test_accuracy"],
        }
    )
if len(public_ft):
    compare_rows.append(
        {
            "source": "public_glove_finetune",
            "run_id": public_ft.iloc[-1]["run_id"],
            "test_accuracy": public_ft.iloc[-1]["test_accuracy"],
        }
    )
if len(rt_df[rt_df["run_id"] == "baseline_random"]):
    bl = rt_df[rt_df["run_id"] == "baseline_random"].iloc[-1]
    compare_rows.append(
        {"source": "baseline_random", "run_id": "baseline_random", "test_accuracy": bl["test_accuracy"]}
    )
if compare_rows:
    cmp_df = pd.DataFrame(compare_rows)
    plt.figure(figsize=(6, 4))
    sns.barplot(data=cmp_df, x="source", y="test_accuracy", hue="source", legend=False, palette="muted")
    plt.ylabel("Reuters test accuracy")
    plt.title("Baseline vs best CBOW vs public GloVe (fine-tune)")
    for _, r in cmp_df.iterrows():
        plt.text(
            list(cmp_df["source"]).index(r["source"]),
            r["test_accuracy"] + 0.005,
            f"{r['test_accuracy']:.3f}",
            ha="center",
            fontsize=9,
        )
    save_fig("reuters_public_vs_best_cbow")

print("\nResults aggregation complete. Figures under artifacts/plots/.")

=== Corpus statistics ===

,corpus,subset,n_sentences,avg_chars,avg_whitespace_tokens,unique_whitespace_tokens,debug
0,30k,full,30000,116.620667,19.699567,79520,False
1,30k,active_subset,30000,116.620667,19.699567,79520,False
2,100k,full,100000,116.967910,19.753540,172454,False
3,100k,active_subset,100000,116.967910,19.753540,172454,False

=== CBOW experiments (deduplicated) ===

,run_id,corpus,n_sentences,window_size,embedding_dim,vocab_size,epochs,batch_size,train_loss,val_loss,val_top1_acc,val_top5_acc,train_time_s
3,cbow_100k_win2_emb100_ep5_vocab50000,100k,99065,2,100,50000,5,256,5.141646,6.165301,0.183741,0.335743,246.45
5,cbow_100k_win2_emb300_ep5_vocab50000,100k,99065,2,300,50000,5,256,4.795797,6.152708,0.187480,0.338889,295.47
4,cbow_100k_win5_emb100_ep5_vocab50000,100k,99065,5,100,50000,5,256,5.854170,6.623945,0.137074,0.270567,150.32
6,cbow_100k_win5_emb100_ep10_vocab50000,100k,99065,5,100,50000,6,256,5.585392,6.620987,0.138319,0.271658,185.04
7,cbow_100k_win8_emb100_ep5_vocab50000,100k,99065,8,100,50000,5,256,6.295267,6.885544,0.108549,0.236890,98.03
0,cbow_30k_win2_emb100_ep5_vocab30000,30k,29687,2,100,30000,5,256,5.686319,6.477578,0.158483,0.297808,60.48
2,cbow_30k_win2_emb300_ep5_vocab30000,30k,29687,2,300,30000,5,256,5.328689,6.456617,0.162623,0.303978,52.83
1,cbow_30k_win5_emb100_ep5_vocab30000,30k,29687,5,100,30000,5,256,6.384019,6.987684,0.105866,0.233034,35.24

=== Reuters classification results ===

,run_id,setup,embedding_dim,reuters_vocab_size,coverage_pct,test_loss,test_accuracy,test_macro_f1,train_time_s
0,baseline_random,baseline,100,20000,0.00,1.380337,0.675423,0.111392,46.24
8,cbow_100k_win2_emb100_ep5_vocab50000,finetune,100,20000,69.67,1.235080,0.715494,0.151416,9.89
7,cbow_100k_win2_emb100_ep5_vocab50000,frozen,100,20000,69.67,1.473702,0.658504,0.109912,9.04
12,cbow_100k_win2_emb300_ep5_vocab50000,finetune,300,20000,69.67,1.165155,0.750223,0.224347,12.65
11,cbow_100k_win2_emb300_ep5_vocab50000,frozen,300,20000,69.67,1.395064,0.673642,0.112681,8.68
14,cbow_100k_win5_emb100_ep10_vocab50000,finetune,100,20000,69.67,1.273242,0.704363,0.138492,10.13
13,cbow_100k_win5_emb100_ep10_vocab50000,frozen,100,20000,69.67,1.414992,0.668744,0.111165,8.58
10,cbow_100k_win5_emb100_ep5_vocab50000,finetune,100,20000,69.67,1.290830,0.703918,0.136043,9.61
9,cbow_100k_win5_emb100_ep5_vocab50000,frozen,100,20000,69.67,1.451453,0.650935,0.102582,8.40
16,cbow_100k_win8_emb100_ep5_vocab50000,finetune,100,20000,69.67,1.220763,0.729742,0.201260,11.67
15,cbow_100k_win8_emb100_ep5_vocab50000,frozen,100,20000,69.67,1.501016,0.632680,0.089797,9.75
2,cbow_30k_win2_emb100_ep5_vocab30000,finetune,100,20000,58.90,1.287970,0.695904,0.116998,9.68
1,cbow_30k_win2_emb100_ep5_vocab30000,frozen,100,20000,58.90,1.476238,0.650935,0.100247,8.52
6,cbow_30k_win2_emb300_ep5_vocab30000,finetune,300,20000,58.90,1.149938,0.734639,0.193830,12.97
5,cbow_30k_win2_emb300_ep5_vocab30000,frozen,300,20000,58.90,1.398689,0.670080,0.130235,91.57
4,cbow_30k_win5_emb100_ep5_vocab30000,finetune,100,20000,58.90,1.176466,0.748887,0.231991,11.17
3,cbow_30k_win5_emb100_ep5_vocab30000,frozen,100,20000,58.90,1.501186,0.625557,0.086002,8.37
18,public_glove-wiki-gigaword-100,public_glove_finetune,100,20000,88.99,1.045449,0.752894,0.193650,10.16
17,public_glove-wiki-gigaword-100,public_glove_frozen,100,20000,88.99,1.128695,0.720392,0.157435,8.60

=== Reuters coverage by CBOW vocabulary ===

,run_id,corpus,cbow_vocab_size,coverage_pct,embedding_dim
3,cbow_100k_win2_emb100_ep5_vocab50000,100k,50000,69.67,100
6,cbow_100k_win5_emb100_ep10_vocab50000,100k,50000,69.67,100
5,cbow_100k_win2_emb300_ep5_vocab50000,100k,50000,69.67,300
4,cbow_100k_win5_emb100_ep5_vocab50000,100k,50000,69.67,100
7,cbow_100k_win8_emb100_ep5_vocab50000,100k,50000,69.67,100
2,cbow_30k_win2_emb300_ep5_vocab30000,30k,30000,58.90,300
0,cbow_30k_win2_emb100_ep5_vocab30000,30k,30000,58.90,100
1,cbow_30k_win5_emb100_ep5_vocab30000,30k,30000,58.90,100

Saved /home/azaliia/projects/LM/practice/artifacts/tables/reuters_coverage_by_cbow.csv

=== Best fine-tuned Reuters accuracy ===

,run_id,setup,embedding_dim,reuters_vocab_size,coverage_pct,test_loss,test_accuracy,test_macro_f1,train_time_s
12,cbow_100k_win2_emb300_ep5_vocab50000,finetune,300,20000,69.67,1.165155,0.750223,0.224347,12.65

=== Public GloVe (fine-tune) ===

,run_id,setup,embedding_dim,reuters_vocab_size,coverage_pct,test_loss,test_accuracy,test_macro_f1,train_time_s
18,public_glove-wiki-gigaword-100,public_glove_finetune,100,20000,88.99,1.045449,0.752894,0.19365,10.16

=== Cosine neighbors (best CBOW val_top1: cbow_100k_win2_emb300_ep5_vocab50000) ===

### Top-10 neighbors: friday (cbow_100k_win2_emb300_ep5_vocab50000)

    rank   neighbor    cosine
40     1     monday  0.895174
41     2   thursday  0.892725
42     3  wednesday  0.870874
43     4    tuesday  0.858691
44     5   saturday  0.815454
45     6     sunday  0.800753
46     7         et  0.625498
47     8        wbd  0.534172
48     9    sundays  0.529098
49    10      rages  0.526386

### Top-10 neighbors: september (cbow_100k_win2_emb300_ep5_vocab50000)

    rank  neighbor    cosine
50     1     march  0.876956
51     2     april  0.876529
52     3   october  0.856914
53     4  november  0.850531
54     5   january  0.846843
55     6  february  0.843836
56     7      july  0.841538
57     8  december  0.835837
58     9    august  0.824198
59    10      june  0.819639

### Top-10 neighbors: monday (cbow_100k_win2_emb300_ep5_vocab50000)

     rank   neighbor    cosine
120     1   thursday  0.901405
121     2  wednesday  0.895228
122     3     friday  0.895174
123     4    tuesday  0.895000
124     5   saturday  0.823740
125     6     sunday  0.784185
126     7         et  0.577332
127     8    sundays  0.560354
128     9      rages  0.543981
129    10     purdue  0.540544

### Top-10 neighbors: water (cbow_100k_win2_emb300_ep5_vocab50000)

     rank       neighbor    cosine
100     1     pesticides  0.611768
101     2  craftsmanship  0.566066
102     3      subsystem  0.559211
103     4        scratch  0.539577
104     5      defective  0.534964
105     6      passersby  0.532669
106     7       climates  0.528082
107     8        fishers  0.508166
108     9      vacancies  0.506463
109    10        grading  0.498500

### Top-10 neighbors: president (cbow_100k_win2_emb300_ep5_vocab50000)

     rank     neighbor    cosine
500     1      nominee  0.570100
501     2   chancellor  0.561555
502     3     minister  0.556749
503     4  chairperson  0.538217
504     5     chairman  0.527143
505     6       bishop  0.520837
506     7    taoiseach  0.518725
507     8     governor  0.514466
508     9      speaker  0.514420
509    10    inspector  0.512586

Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_test_accuracy_all_setups.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_frozen_vs_finetune_delta.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_effect_embedding_dim.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_effect_window_size.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_effect_corpus_size.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_effect_epochs.png
Saved figure: /home/azaliia/projects/LM/practice/artifacts/plots/reuters_public_vs_best_cbow.png

Results aggregation complete. Figures under artifacts/plots/.

## 12. Conclusions

### Summary

In this project, we trained CBOW word embeddings on two English news corpora containing 30K and 100K sentences. In total, we tested 8 different configurations with different window sizes, embedding dimensions, and training settings.

The embeddings were evaluated in two ways:

- qualitatively, using cosine similarity and t-SNE visualizations
- quantitatively, using Reuters topic classification with a CNN classifier

We compared several initialization strategies:

- random embeddings trained from scratch
- pretrained CBOW embeddings with frozen weights
- pretrained CBOW embeddings with fine-tuning
- public GloVe embeddings (`glove-wiki-gigaword-100`)

Reuters classification was trained for up to 10 epochs with EarlyStopping based on validation metrics.

---

### Main findings

| Setup | Best result | Notes |
|---|---|---|
| Random baseline | 67.5% | Embeddings learned from scratch |
| CBOW + fine-tuning | 75.0% | `cbow_100k_win2_emb300_ep5` |
| CBOW + frozen | 67.0% | Similar to baseline |
| GloVe + fine-tuning | 75.3% | `glove-wiki-gigaword-100` |
| GloVe + frozen | 72.0% | Strong performance without tuning |

Fine-tuning consistently improved performance compared to frozen embeddings. In several experiments, the improvement was around 7–12 percentage points. For example, with the 100K corpus, window size 2, and embedding size 100, frozen embeddings achieved 65.9% accuracy, while fine-tuning reached 71.5%.

Frozen CBOW embeddings alone rarely outperformed the random baseline. One important reason is that only around 59–70% of Reuters vocabulary tokens received pretrained vectors. The remaining words stayed randomly initialized.

Using the larger 100K corpus improved downstream performance. With the same settings (`window=2`, `embedding_dim=100`, `epochs=5`), the 100K corpus achieved 71.5% accuracy after fine-tuning, compared to 69.6% for the 30K corpus.

Embedding dimensionality also had a noticeable impact. On the 100K corpus with window size 2, embeddings with dimension 300 performed better than dimension 100. The larger embeddings achieved 75.0% test accuracy, while the smaller ones reached 71.5%.

Smaller context windows worked better for Reuters classification. Window size 2 produced the strongest results, while window size 8 was weaker. Larger windows likely diluted local semantic information that is important for short-text classification.

Increasing CBOW training epochs from 5 to 10 produced only minor improvements in downstream performance. Once embeddings reached a reasonable quality level, additional CBOW training had limited impact on Reuters accuracy.

Public GloVe embeddings slightly outperformed our best CBOW embeddings. GloVe reached 75.3% test accuracy after fine-tuning, compared to 75.0% for the best CBOW model. This difference is mainly explained by better vocabulary coverage and much larger pretraining data.

---

### Qualitative evaluation

Cosine similarity and t-SNE visualizations showed meaningful semantic groupings.

Calendar-related words such as `friday`, `monday`, `thursday`, and month names formed clear clusters. Political terms such as `president`, `minister`, and `governor` were also grouped together.

Some words, especially more ambiguous ones like `water` or `music`, produced noisier neighbors. This reflects the relatively low CBOW word-prediction accuracy observed during training.

In general:

- embeddings trained on 100K performed better than those trained on 30K
- larger embedding dimensions produced more coherent semantic relationships

---

### Limitations

Several limitations should be noted:

- CBOW word-prediction accuracy remained relatively low (around 16–19% top-1 validation accuracy)
- frozen embeddings alone were usually not strong enough without downstream fine-tuning
- Reuters classes are highly imbalanced, which explains why macro-F1 scores stayed much lower than accuracy
- vocabulary alignment between Reuters, CBOW embeddings, and GloVe embeddings was imperfect, leaving some words randomly initialized
- only one downstream task and one public embedding baseline were tested
- larger experiments on the 100K corpus and higher-dimensional embeddings required significant computation time

Because of this, DEBUG mode was important for quickly validating the pipeline before running full experiments.

---

### Final takeaway

The experiments showed that CBOW embeddings trained on a news corpus can achieve competitive performance when they are fine-tuned on the downstream task.

The best results were obtained with:

- larger training data (100K corpus)
- moderate context size (`window=2`)
- higher embedding dimensionality (`d=300`)
- fine-tuning enabled during Reuters training

GloVe remained a very strong baseline because of its broader vocabulary coverage and large-scale pretraining.

Overall, the results suggest that pretrained embeddings are most useful when they are adapted to the target task, rather than used as fixed representations.